### PR TITLE
Feature/tclune/python spec generator

### PR DESCRIPTION
**Pull request by tclune**
## Description

Added new Python file (in new directory) to replace Perl code generator.

## Related Issue

Corresponding PR in esma_cmake for macro to exercise this ACG.

## Motivation and Context

General preference for Python over Perl going forward.

## How Has This Been Tested?

Exercised against branch of next gen GOCART  DU grid comp.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

New feature but not yet used so trivial 0 diff.

## Checklist:

- [ ] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [x] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by tclune** [comment]
Please do a squash merge when approving.

**Comment by mathomp4** [comment]
> Corresponding PR in esma_cmake for macro to exercise this ACG.

@tclune Am I right in assuming this does not need anything new in ESMA_cmake? I saw you canceled the PR there.

**Comment by tclune** [comment]
@mathomp4 please approve this.   Very important to get this into 2.1

**Comment by mathomp4** [comment]
Approved and merged

**Pull request merged**
