### PR TITLE
fix typo in the range of halo in LatLonGridfactory

### PR DESCRIPTION
**Pull request by weiyuan-jiang**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [ ] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [x] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Review by tclune — APPROVED** [review]

**Comment by mathomp4** [comment]
@tclune @weiyuan-jiang This didn't get into MAPL 2.34. Should I release a 2.35 with this fix?

**Comment by tclune** [comment]
I defer to @weiyuan-jiang as to urgency.     But I wish now I'd been awake enough this morning to realize that this should have probably been a hotfix on main.

**Comment by weiyuan-jiang** [comment]
@mathomp4 , Hold for a while. I am adding the functions that fill the corner of the halo

**Comment by mathomp4** [comment]
@weiyuan-jiang Sounds good!

**Pull request merged**
