### PR TITLE
Remove unguarded FLAP dependencies preventing MAPL from building with BUILD_WITH_FLAP=NO

### PR DESCRIPTION
**Pull request by rmontuoro**
## Description

These changes remove unguarded FLAP dependencies in the build systems added by commit be2fa9bc.
## Related Issue

#780 
## Motivation and Context

These changes address an issue preventing MAPL from building if `BUILD_WITH_FLAP=NO`.
## How Has This Been Tested?

The changes were tested on NOAA RDHPCS platforms.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Trivial change (affects only documentation or cleanup)

## Checklist:

- [ ] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [ ] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)
`CHANGELOG.md` not updated since changes are trivial.

### CODE REVIEW

**Comment by mathomp4** [comment]
@rmontuoro We can't remove these because it would break the build with NAG+FLAP. But let me protect them correctly.

**Review by tclune — APPROVED** [review]

**Comment by mathomp4** [comment]
@rmontuoro I've pushed a change to your branch. Can you give it a try at NOAA and make sure it works (I can't see how it wouldn't).

**Comment by mathomp4** [comment]
Query for @tclune. Do prefer:
```cmake
target_link_libraries(this PRIVATE MPI::MPI_Fortran)
if (BUILD_WITH_FLAP)
  target_link_libraries(this PRIVATE FLAP::FLAP)
endif ()
```
or:
```cmake
target_link_libraries(this PRIVATE MPI::MPI_Fortran $<$<BOOL:${BUILD_WITH_FLAP}>:FLAP::FLAP>)
```
I think either will work.

**Comment by tclune** [comment]
1st - kudos for using advanced cmake-foo.

No strong preference either way.  Mild preference for the generator expression, but maybe split the line, as it is getting long?

**Comment by rmontuoro** [comment]
@mathomp4 - I can confirm the latest changes work with UFS-GOCART.

**Comment by mathomp4** [comment]
> @mathomp4 - I can confirm the latest changes work with UFS-GOCART.

@rmontuoro Thanks. Was it the generator expression version?

**Comment by rmontuoro** [comment]
@mathomp4 - Yes (c867979)

**Review by mathomp4 — APPROVED** [review]

**Comment by tclune** [comment]
I want to revisit this PR.   The original changes from @rmontuoro should actually be ok.   The dependency is really only in base for now.  @mathomp4 let's look at this on Monday.

**Pull request merged**
