### PR TITLE
Fixes #642. Remove/comment out cube string variables

### LINKED ISSUE #642: Two variables in native cube output are broken
This was discovered by @aoloso when testing the compress-and-compare of @wmputman 's DYAMOND2 data. Namely, two variables in the CS native output are garbage. They are defined as variables but never set it looks like, so you get...uninitialized junk in them. Luckily they seem to be variables nothing cares about, but we should fix it.

The big broken variable is `orientation` and the other one I suspect is broken is `cubed_sphere`. To wit:
```console
❯ ncks -L 1 inst_15mn_2d_asm_Mx.20000414_2200z.nc4 compressed.nc4
❯ nccmp -dfsB inst_15mn_2d_asm_Mx.20000414_2200z.nc4 compressed.nc4
DIFFER : VARIABLE : orientation : POSITION : [0,0,0] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [0,0,4] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [0,1,3] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [0,2,2] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [0,3,1] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [1,0,0] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [1,0,4] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [1,1,3] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [1,2,2] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [1,3,1] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [2,0,0] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [2,0,4] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [2,1,3] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [2,2,2] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [2,3,1] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [3,0,0] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [3,0,4] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [3,1,3] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [3,2,2] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [3,3,1] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [4,0,0] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [4,0,4] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [4,1,3] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [4,2,2] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [5,0,0] : VALUES : � <>
DIFFER : VARIABLE : orientation : POSITION : [5,0,1] : VALUES : = <>
DIFFER : VARIABLE : orientation : POSITION : [5,0,2] : VALUES : 7 <>
DIFFER : VARIABLE : orientation : POSITION : [5,0,3] : VALUES : � <>
DIFFER : VARIABLE : orientation : POSITION : [5,0,4] : VALUES : � <>
DIFFER : VARIABLE : orientation : POSITION : [5,1,0] : VALUES : � <>
DIFFER : VARIABLE : orientation : POSITION : [5,1,1] : VALUES : � <>
DIFFER : VARIABLE : orientation : POSITION : [5,1,2] : VALUES : � <>
DIFFER : VARIABLE : orientation : POSITION : [5,1,3] : VALUES : \ <>
DIFFER : VARIABLE : orientation : POSITION : [5,1,4] : VALUES : P <>
DIFFER : VARIABLE : orientation : POSITION : [5,2,0] : VALUES : 5 <>
DIFFER : VARIABLE : orientation : POSITION : [5,2,1] : VALUES : � <>
DIFFER : VARIABLE : orientation : POSITION : [5,2,2] : VALUES : � <>
DIFFER : VARIABLE : orientation : POSITION : [5,2,3] : VALUES : w <>
DIFFER : VARIABLE : orientation : POSITION : [5,2,4] : VALUES : T <>
DIFFER : VARIABLE : orientation : POSITION : [5,3,0] : VALUES : � <>
DIFFER : VARIABLE : orientation : POSITION : [5,3,1] : VALUES : � <>
DIFFER : VARIABLE : orientation : POSITION : [5,3,2] : VALUES : \ <>
DIFFER : VARIABLE : orientation : POSITION : [5,3,3] : VALUES : 3 <>
DIFFER : VARIABLE : orientation : POSITION : [5,3,4] : VALUES : � <>
```
It looks like `ncks` compresses the garbage into *different* garbage, so that `nccmp` says, well, they are different. (I wonder if this is a bug in libz? Seems like zip should be able to compress anything even junk...)

Speaking with @tclune, he looked at this code:
https://github.com/GEOS-ESM/MAPL/blob/8e933d8adf111af0d4215ecf09c7e0dbe1388ff9/base/MAPL_CubedSphereGridFactory.F90#L908-L936
where it looks like `cvar` that was filled back in old Developer Git days (https://developer.nasa.gov/GMAO/GEOSagcm/blob/4efb0f3c6210c84fc2cf1380be34c37104ad591c/src/GMAO_Shared/MAPL_cfio/ESMF_CFIOSdfMod.F90#L2347-L2390) was commented out and then `orientation` was never filled. He suspects maybe this was a GNU compiler issue maybe? Unknown as this code has been commented forever it looks like here in GitHub.

I'm also concerned about the other `char` variable `cubed_sphere` where it is declared:
https://github.com/GEOS-ESM/MAPL/blob/8e933d8adf111af0d4215ecf09c7e0dbe1388ff9/base/MAPL_CubedSphereGridFactory.F90#L888-L893
but I can't see anything ever actually filling it.

### PR DESCRIPTION
**Pull request by mathomp4**
## Description

Updates the CubeSphere factory to not output string variables as pFIO does not seem to support them (see https://github.com/GEOS-ESM/MAPL/issues/642#issuecomment-783676553)

## Related Issue

#642 

## Motivation and Context

With this, you can `nccmp` a native History file and a native History compressed file and it works.

## How Has This Been Tested?

Ran GEOS, output a cube native file, compressed and it works. Before:
```console
$ ncks -L 1 nativeouttest-gcm-2021Feb22-1day-c24.geosgcm_native.20000415_1800z.nc4 compressed.nc4
$ nccmp -dfsB nativeouttest-gcm-2021Feb22-1day-c24.geosgcm_native.20000415_1800z.nc4 compressed.nc4
DIFFER : VARIABLE : orientation : POSITION : [0,0,0] : VALUES :  <> x
DIFFER : VARIABLE : orientation : POSITION : [0,0,1] : VALUES :  <> W
DIFFER : VARIABLE : orientation : POSITION : [0,0,2] : VALUES :  <> w
DIFFER : VARIABLE : orientation : POSITION : [0,0,3] : VALUES :  <> �
DIFFER : VARIABLE : orientation : POSITION : [0,0,4] : VALUES :  <> �
DIFFER : VARIABLE : orientation : POSITION : [0,1,0] : VALUES :  <> *
DIFFER : VARIABLE : orientation : POSITION : [0,1,3] : VALUES :  <> �
DIFFER : VARIABLE : orientation : POSITION : [0,1,4] : VALUES :  <> �
DIFFER : VARIABLE : orientation : POSITION : [0,2,0] : VALUES :  <> P
DIFFER : VARIABLE : orientation : POSITION : [0,2,1] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [0,2,2] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [0,3,1] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [1,0,0] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [1,0,4] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [1,1,3] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [1,2,2] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [1,3,1] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [2,0,0] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [2,0,4] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [2,1,3] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [2,2,2] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [2,3,1] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [3,0,0] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [3,0,4] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [3,1,3] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [3,2,2] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [3,3,1] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [4,0,0] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [4,0,4] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [4,1,3] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [4,2,2] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [5,0,0] : VALUES : 1 <>
DIFFER : VARIABLE : orientation : POSITION : [5,0,1] : VALUES : � <>
DIFFER : VARIABLE : orientation : POSITION : [5,0,3] : VALUES : @ <>
DIFFER : VARIABLE : orientation : POSITION : [5,0,4] : VALUES : � <>
DIFFER : VARIABLE : orientation : POSITION : [5,1,0] : VALUES : 9 <>
DIFFER : VARIABLE : orientation : POSITION : [5,1,1] : VALUES : O <>
DIFFER : VARIABLE : orientation : POSITION : [5,1,2] : VALUES : H <>
DIFFER : VARIABLE : orientation : POSITION : [5,1,3] : VALUES : � <>
DIFFER : VARIABLE : orientation : POSITION : [5,1,4] : VALUES : � <>
DIFFER : VARIABLE : orientation : POSITION : [5,2,0] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [5,2,1] : VALUES : @ <>
DIFFER : VARIABLE : orientation : POSITION : [5,2,2] : VALUES : W <>
DIFFER : VARIABLE : orientation : POSITION : [5,2,3] : VALUES : � <>
DIFFER : VARIABLE : orientation : POSITION : [5,2,4] : VALUES : � <>
DIFFER : VARIABLE : orientation : POSITION : [5,3,0] : VALUES : m <>
DIFFER : VARIABLE : orientation : POSITION : [5,3,1] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [5,3,2] : VALUES : � <>
DIFFER : VARIABLE : orientation : POSITION : [5,3,3] : VALUES : $ <>
DIFFER : VARIABLE : orientation : POSITION : [5,3,4] : VALUES : @ <>
```
After:
```console
$ ncks -L 1 nativeouttest-gcm-2021Feb22-1day-c24.geosgcm_native.20000415_1800z.nc4 compressed.nc4
$ nccmp -dfsB nativeouttest-gcm-2021Feb22-1day-c24.geosgcm_native.20000415_1800z.nc4 compressed.nc4
Files "nativeouttest-gcm-2021Feb22-1day-c24.geosgcm_native.20000415_1800z.nc4" and "compressed.nc4" are identical.
```

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [X] I have tested this change with a run of GEOSgcm (if non-trivial)
- [X] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [ ] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by mathomp4** [comment]
Paging @lizziel and @sdeastham. Will this break anything at Harvard? I'll add a blocking label until you can comment on it.

**Review by tclune — APPROVED** [review]

**Comment by tclune** [comment]
@mathomp4 there are merge conflicts.

**Comment by sdeastham** [comment]
@mathomp4 I don't *think* this will cause issues for us - but would be curious for @LiamBindle 's perspective. While I think there's no near-term issue, in the long term I'm assuming this will cause a roadblock in terms of adopting the gridspec "universal" standard  which I had heard was a goal (https://arxiv.org/pdf/1911.08638.pdf)

**Comment by LiamBindle** [comment]
I don't see any issue. I don't see a good use for them unless (or until) gridspec is formally implemented. It's probably safer for us if they're removed so nobody uses them. 

I find them a nuisance when post-processing with NCO too.

**Review by tclune — DISMISSED** [review]

**Review by tclune — APPROVED** [review]

**Review by tclune — APPROVED** [review]

**Pull request merged**
