### PR TITLE
add --with_io_profiler option

### PR DESCRIPTION
**Pull request by weiyuan-jiang**
Add an option whether or not turn on io_profiler
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [ ] I have tested this change with a run of GEOSgcm (if non-trivial)
- [ ] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [ ] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by tclune** [comment]
We need to wait to merge this until after the next MAPL release.

**Comment by weiyuan-jiang** [comment]
@tclune , I think we should have this option first. It is convenient for me and @bena-nasa to profile the io server. Later on, if we have better solution, we can remove this option

**Comment by tclune** [comment]
You can use it to profile the server on the feature branch ...

**Comment by mathomp4** [comment]
@weiyuan-jiang Is this still a draft?

**Comment by weiyuan-jiang** [comment]
> @weiyuan-jiang Is this still a draft?

No. I think Tom wanted a fix in profiler, not here in the application. Maybe I should close this PR.

**Comment by tclune** [comment]
This ticket will remain in limbo until @weiyuan-jiang has access to ORION and can reproduce the issues seen in USF.

**Comment by mathomp4** [comment]
I've remerged/based this onto `develop`. @weiyuan-jiang did you ever get access to Orion to test this?

**Review by tclune — DISMISSED** [review]

**Comment by mathomp4** [comment]
I did a run with GEOSgcm and this seems zero-diff.

**Pull request merged**
