### PR TITLE
Reorganize PFIO Standalone

### PR DESCRIPTION
**Pull request by JulesKouatchou**
## Description

Reorganized the PFIO standalone program to:

- Break the code into small tasks
- Mimic the steps of MAPL_Cap. This can be used as reference if PFIO is implemented in a non-GEOS model.
- Include FORD tags for documenting the code.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [ ] I have tested this change with a run of GEOSgcm (if non-trivial)
- [ ] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [ ] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Review by tclune — CHANGES_REQUESTED** [review]
Something is very wrong with this PR.  It appears to make changes to unrelated files like the ACG.   

Probably just a PR to the wrong branch?

**Comment by mathomp4** [comment]
> Something is very wrong with this PR. It appears to make changes to unrelated files like the ACG.
> 
> Probably just a PR to the wrong branch?

@tclune I think this just needs to be pulled into `develop` and not `main`. I'm changing the base.

**Comment by JulesKouatchou** [comment]
@mathomp4 Made changes in the CHANGELOG.md file. I am wondering if it will be enough.

**Comment by mathomp4** [comment]
> @mathomp4 Made changes in the CHANGELOG.md file. I am wondering if it will be enough.

@JulesKouatchou I cleaned it up a bit. I think you got a bit of old `develop` into it, so I made it look like it should.

**Review by weiyuan-jiang — APPROVED** [review]

**Pull request merged**
