### PR TITLE
This fixes a bug which caused a crash when creating MOM grid in coupl…

### PR DESCRIPTION
**Pull request by yvikhlya**
Coupled model crashes when it creates tripolar MOM grid without this fix.

### CODE REVIEW

**Comment by mathomp4** [comment]
@yvikhlya After conferring with @tclune, this will (for now) have to wait before merging in. The issue is that the CVS tag `GEOSadas-5_25_0` was itself technically broken in regards to OGCM, so the equivalent in git must be. However, when we replay the Jason tags of @lltakacs, we will then merge this in.

**Comment by tclune** [comment]
Just to expand a bit on Matt's nice summary of our discussion:  There is some minor risk that patching earlier in Git will introduce additional reproducibility surprises as we fold in the additional Jason tags in the next couple of days.    In the mean time, you could/should create a branch in the fixture that points to your patched MAPL to enable further investigation of the coupled system.   That branch can then be  updated when MAPL is tagged followed by a PR to the GCM fixture.

Of course the issue now is that the GCM lacks a gatekeeper/reviewer.     I'll encourage Bill P to take his training.

**Comment by mathomp4** [comment]
I think we might be ready for this now. MAPL 1.1.5 is essentially `Jason-UNSTABLE`. With some tests I'm sure it's fairly simple to accept this.

Then, we could issue a new release and advance the MAPL in the main `Develop.cfg` in `GEOSgcm` to be 1.1.6. This is probably a good effort that I, @sdrabenh, @lltakacs, and @tclune could pursue.

My thinking on how to test this at present would be (@tclune please put in your two cents):
1. Build `GEOSgcm` with `Develop.cfg` and install and run the model so we have a baseline (aka "stock" `Jason-UNSTABLE`...heck, you could *use* a current CVS build).
2. Go to `MAPL` and update to Yuri's branch.
3. Build in a new build/install dir. This would have to be with old-school CMake since there isn't an option for non-standard build dirs in `parallel_build.csh` (yet).

Note that you could just do two clones of the model. One is the "stock" and the other is one where you change the `Develop.cfg` in the second clone to point `MAPL` to:
```
branch = bugfix/yvikhlya/tripolar_grid_fix
```
Not sure of the best workflow yet...

**Comment by mathomp4** [comment]
Actually, this branch was made before the latest MAPL, so *merge* is probably the correct term to use. But if we [look back in time](https://github.com/GEOS-ESM/MAPL/network), I don't think there are any updates since the branch was made that will cause issues with a simple one-day run test.

**Comment by tclune** [comment]
If the master branch has changed, we should rebase this branch off master before testing in the GCM.   It is unfortunate that GitHub is not ideal in its support for the situation.    We can instead work with the GCM gatekeeper to rebase on MAPL's master branch prior to testing.   But if we want a recipe for doing this in GitHub (sort of):

[rebase a branch in GitHub](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request)

**Comment by mathomp4** [comment]
Well, locally, I merged this branch into `master` and git took care of things pretty nicely. There were no conflicts, so we might be good, but it wouldn't be hard to rebase. The tree looks a bit odd:
```
2019-07-29 12:04 -0400 Matthew Thompson M─┐ [master] Merge branch 'bugfix/yvikhlya/tripolar_grid_fix'
2019-07-24 12:31 -0400 Yury Vikhliaev   │ o [bugfix/yvikhlya/tripolar_grid_fix] {origin/bugfix/yvikhlya/tripolar_grid_fix} This fixes a bug which caused a
2019-07-26 14:44 -0400 Ben Auer         M─│─┐ {origin/master} {origin/HEAD} <v1.1.5> Merge pull request #12 from GEOS-ESM/feature/mathomp4/Jason-UNSTABLE-2
2019-07-26 14:43 -0400 Matthew Thompson │ │ o Update to MAPL_TilingRegridder.F90
2019-07-26 13:23 -0400 Ben Auer         M─│─┤ <v1.1.4> Merge pull request #11 from GEOS-ESM/feature/mathomp4/Jason-3_1
2019-07-26 13:18 -0400 Matthew Thompson │ │ o Update to code from Jason-3_1
2019-07-25 11:56 -0400 Ben Auer         M─│─┤ <cvs/GEOSadas-5_25_0> <v1.1.3> Merge pull request #10 from GEOS-ESM/feature/mathomp4/detect-latex-for-docs
2019-07-25 08:54 -0700 Matthew Thompson │ │ o Use LaTeX detection from ESMA_cmake v1.0.9
2019-07-23 13:19 -0400 Ben Auer         M─│─┤ <1.1.2> Merge pull request #5 from GEOS-ESM/feature/mathomp4/add-codeowners
2019-07-23 13:12 -0400 Matthew Thompson │ │ o Add CODEOWNERS for CMakeLists.txt
2019-07-22 09:36 -0400 Tom Clune        M─│─┤ Merge pull request #3 from GEOS-ESM/feature/mathomp4/remove-gnumakefiles
2019-07-18 15:10 -0400 Matthew Thompson │ │ o Remove old GNUmakefiles
2019-07-08 16:48 -0400 Ben Auer         M─┼─┘ <1.1.1> Merge pull request #2 from GEOS-ESM/feature/mathomp4/makefixes-2019Jul08
2019-07-08 16:38 -0400 Matthew Thompson │ o Install perl script. Update version
2019-07-03 13:13 -0400 Tom Clune        o─┘ <1.1.0> High level description of MAPL
```
but it seems only aesthetic.

**Comment by mathomp4** [comment]
Oh, and as expected, this is a zero-diff change as far as AGCM goes. Saw no issues at all.

**Comment by tclune** [comment]
@mathomp4  Was just looking through PR's in various repositories and saw this one.     I was not added as a reviewer, and you've not approved it yet.    Should I approve?

**Comment by sdrabenh** [comment]
Hi Tom,

I don’t mind approving, but first, let me check in with Larry about this tomorrow.

Thanks,
Scott

**Comment by tclune** [comment]
@sdrabenh The comment was directed at @mathomp4.  Unfortunately, when people respond via email, some of these types of nuances are harder to see. 

May need to send out an email asking people to try to respond directly in GitHub instead of via email.

**Pull request merged**
