### PR TITLE
Refactors legacy MAPL_Generic

### PR DESCRIPTION
**Pull request by Gvilla1000-nasa**
## Description
This PR refactors the legacy MAPL_Generic. This includes the following changes:
* Moving MAPL_Generic.F90 and MAPL_GenericCplComp.F90 into generic and removing the MAPL prefix.
* Moving MAPL_ExtDataGridCompMod.F90, MAPL_OrbGridComp.rc, and MAPL_OrbGridCompMod.F90 from base into generic due to their dependency on MAPL_GenericMod.
* Removes mapl.generic dependency from Base. Mapl.generic now depends on mapl.base.
* Moved MaplGrid.F90 to base directory since base depended on it.
 

## Related Issue

#954 

## Motivation and Context
Refactor work of MAPL

## How Has This Been Tested?

Tested by running GEOSgcm for a day and for longer than 5 days and 5hrs because I'm still traumatized lol. No differences were observed in either test.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Trivial change (affects only documentation or cleanup)

## Checklist:

- [x] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [x] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by Gvilla1000-nasa** [comment]
Latest commit addresses the majority of the comments made in this PR. The caveat is that it is currently segfaulting when running. Currently investigating the source. Traceback excerpt is copied below:

```
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
GEOSgcm.x          000000000315136A  Unknown               Unknown  Unknown
libpthread-2.22.s  00002AAAC3E57C10  Unknown               Unknown  Unknown
libMAPL.profiler.  00002AAABDD05CD0  mapl_baseprofiler         143  BaseProfiler.F90
libMAPL.generic.s  00002AAABA20FAA5  mapl_genericmod_m        1862  Generic.F90
libesmf.so         00002AAABF0902E4  _ZN5ESMCI6FTable1     Unknown  Unknown
libesmf.so         00002AAABF093ABF  ESMCI_FTableCallE     Unknown  Unknown
libesmf.so         00002AAABF620D45  _ZN5ESMCI2VM5ente     Unknown  Unknown
libesmf.so         00002AAABF09173A  c_esmc_ftablecall     Unknown  Unknown
libesmf.so         00002AAABF8B0D4D  esmf_compmod_mp_e     Unknown  Unknown
libesmf.so         00002AAABFBB2FE1  esmf_gridcompmod_     Unknown  Unknown
libMAPL.generic.s  00002AAABA27818E  mapl_genericmod_m        1512  Generic.F90
GEOSgcm.x          0000000000504791  geos_agcmgridcomp        1117  GEOS_AgcmGridComp.F90
libesmf.so         00002AAABF0902E4  _ZN5ESMCI6FTable1     Unknown  Unknown
libesmf.so         00002AAABF093ABF  ESMCI_FTableCallE     Unknown  Unknown
libesmf.so         00002AAABF620D45  _ZN5ESMCI2VM5ente     Unknown  Unknown
libesmf.so         00002AAABF09173A  c_esmc_ftablecall     Unknown  Unknown
libesmf.so         00002AAABF8B0D4D  esmf_compmod_mp_e     Unknown  Unknown
libesmf.so         00002AAABFBB2FE1  esmf_gridcompmod_     Unknown  Unknown
libMAPL.generic.s  00002AAABA20F66F  mapl_genericmod_m        1845  Generic.F90
libesmf.so         00002AAABF0902E4  _ZN5ESMCI6FTable1     Unknown  Unknown
libesmf.so         00002AAABF093ABF  ESMCI_FTableCallE     Unknown  Unknown
libesmf.so         00002AAABF620D45  _ZN5ESMCI2VM5ente     Unknown  Unknown
libesmf.so         00002AAABF09173A  c_esmc_ftablecall     Unknown  Unknown
libesmf.so         00002AAABF8B0D4D  esmf_compmod_mp_e     Unknown  Unknown
libesmf.so         00002AAABFBB2FE1  esmf_gridcompmod_     Unknown  Unknown
libMAPL.generic.s  00002AAABA27818E  mapl_genericmod_m        1512  Generic.F90
GEOSgcm.x          000000000047CEF5  geos_gcmgridcompm        1203  GEOS_GcmGridComp.F90
libesmf.so         00002AAABF0902E4  _ZN5ESMCI6FTable1     Unknown  Unknown
libesmf.so         00002AAABF093ABF  ESMCI_FTableCallE     Unknown  Unknown
libesmf.so         00002AAABF620D45  _ZN5ESMCI2VM5ente     Unknown  Unknown
libesmf.so         00002AAABF09173A  c_esmc_ftablecall     Unknown  Unknown
libesmf.so         00002AAABF8B0D4D  esmf_compmod_mp_e     Unknown  Unknown
libesmf.so         00002AAABFBB2FE1  esmf_gridcompmod_     Unknown  Unknown
libMAPL.generic.s  00002AAABA20F66F  mapl_genericmod_m        1845  Generic.F90
libesmf.so         00002AAABF0902E4  _ZN5ESMCI6FTable1     Unknown  Unknown
libesmf.so         00002AAABF093ABF  ESMCI_FTableCallE     Unknown  Unknown
libesmf.so         00002AAABF620D45  _ZN5ESMCI2VM5ente     Unknown  Unknown
libesmf.so         00002AAABF09173A  c_esmc_ftablecall     Unknown  Unknown
libesmf.so         00002AAABF8B0D4D  esmf_compmod_mp_e     Unknown  Unknown
libesmf.so         00002AAABFBB2FE1  esmf_gridcompmod_     Unknown  Unknown
libMAPL.cap.so     00002AAAB97E793E  mapl_capgridcompm         631  MAPL_CapGridComp.F90
libesmf.so         00002AAABF0902E4  _ZN5ESMCI6FTable1     Unknown  Unknown
libesmf.so         00002AAABF093ABF  ESMCI_FTableCallE     Unknown  Unknown
libesmf.so         00002AAABF620D45  _ZN5ESMCI2VM5ente     Unknown  Unknown
libesmf.so         00002AAABF09173A  c_esmc_ftablecall     Unknown  Unknown
libesmf.so         00002AAABF8B0D4D  esmf_compmod_mp_e     Unknown  Unknown
libesmf.so         00002AAABFBB2FE1  esmf_gridcompmod_     Unknown  Unknown
libMAPL.cap.so     00002AAAB97E1D10  mapl_capgridcompm         934  MAPL_CapGridComp.F90
libMAPL.cap.so     00002AAAB97D1666  mapl_capmod_mp_ru         259  MAPL_Cap.F90
libMAPL.cap.so     00002AAAB97CF422  mapl_capmod_mp_ru         218  MAPL_Cap.F90
libMAPL.cap.so     00002AAAB97CD7AD  mapl_capmod_mp_ru         152  MAPL_Cap.F90
libMAPL.cap.so     00002AAAB97CD45A  Unknown               Unknown  Unknown
GEOSgcm.x          000000000046C34F  MAIN__                     34  GEOSgcm.F90
GEOSgcm.x          000000000046A1D2  Unknown               Unknown  Unknown
libc-2.22.so       00002AAAC462C725  __libc_start_main     Unknown  Unknown
GEOSgcm.x          000000000046A0E9  Unknown               Unknown  Unknown
>> Error << /usr/local/intel/2020/compilers_and_libraries_2020.4.304/linux/mpi/intel64/bin/mpirun  -np 24 ./GEOSgcm.x --logging_config logging.yaml: status = 174; at /gpfsm/dnb32/gvillami/GEOSgcm_GenericRefactor/GEOSgcm/build/install/bin/esma_mpirun line 378.
GEOSgcm Run Status: -1
```

**Comment by weiyuan-jiang** [comment]
The crash has nothing to do with the profiler. The compiler messes up without the instruction of "recursive". Add "recursive" before this
https://github.com/GEOS-ESM/MAPL/blob/d4ad08482955b9f0a690c0be56d8de545eec5f00/generic/MAPL_Generic.F90#L1708

**Comment by tclune** [comment]
@Gvilla1000-nasa and @weiyuan-jiang came up with this fix independently in a similar window.    I've also tested on my laptop, so the fix seems to be robust.  There's a bit of a mystery why it "worked" before, but ... maybe this explains the confusion we had with moist before.   (@atrayano to bring to his attention.)

**Comment by tclune** [comment]
Note NAG would have detected this, were we able to run a case that exercise the generic layer ... (@mathomp4 and @bena-nasa maybe we want to create a test gridcomp hierarchy inside MAPL so that we can use NAG - bypassing FMS.)

**Review by mathomp4 — APPROVED** [review]
Approving

**Review by tclune — APPROVED** [review]

**Pull request merged**
