### PR TITLE
Fixes #799. Allow comments in NRL solar file

### LINKED ISSUE #799: MAPL crashes if NRL solar file has comments
This is on me. If you read in an NRL Solar File with comments, MAPL crashes:
```
 Logical Resource Parameter: PERSIST_SOLAR:T
forrtl: severe (59): list-directed I/O syntax error, unit 23, file /discover/nobackup/pnorris/OLRC/IC180RM2/NRLSSI2/output/NRLSSI2.v2020.txt
Image              PC                Routine            Line        Source
GEOSgcm.x          00000000031F29FB  Unknown               Unknown  Unknown
GEOSgcm.x          0000000003231E72  Unknown               Unknown  Unknown
GEOSgcm.x          000000000323089C  Unknown               Unknown  Unknown
libMAPL.base.so    00002AAABA20C2E3  mapl_sunmod_mp_ma        2513  MAPL_sun_uc.F90
GEOSgcm.x          0000000001B5AFE2  geos_surfacegridc        6238  GEOS_SurfaceGridComp.F90
libesmf_fullylink  00002AAABDEC61A4  _ZN5ESMCI6FTable1     Unknown  Unknown
libesmf_fullylink  00002AAABDEC997F  ESMCI_FTableCallE     Unknown  Unknown
libesmf_fullylink  00002AAABE477C05  _ZN5ESMCI2VM5ente     Unknown  Unknown
libesmf_fullylink  00002AAABDEC75FA  c_esmc_ftablecall     Unknown  Unknown
libesmf_fullylink  00002AAABE6C98CD  esmf_compmod_mp_e     Unknown  Unknown
```

Obviously, it should be doable to read a text file with comments. The code needs a serious stare at, though...

### PR DESCRIPTION
**Pull request by mathomp4**
## Description

This PR will allow the use of an NRL solar file with comments (at the beginning?) a la:
```
# NRLSSI2 daily input
# treat daily values as valid at 12:00 GMT
# yyyy doy TSI:W/m2 MgIndex   SBindex
  1882 001 1360.808 0.152777  165.5972
  1882 002 1360.844 0.153383  251.0557
...
```

Note: the code is Ugly, so...might be improvements suggested.

## Related Issue

Closes #799 

## Motivation and Context

The NRL solar file is pretty opaque without the comments that @dr0cloud adds to it. Now we can keep them.

## How Has This Been Tested?

I ran GEOS and it was zero-diff!

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [X] I have tested this change with a run of GEOSgcm (if non-trivial)
- [X] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [X] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Review by atrayano — APPROVED** [review]
Looks OK. One minor suggestion: the comment lines 2528 and 2772 are slightly incorrect. The current code skips a line if the commentChar (#) is anywhere in that line, not just starting. You could consider changing it

**Comment by mathomp4** [comment]
> Looks OK. One minor suggestion: the comment lines 2528 and 2772 are slightly incorrect. The current code skips a line if the commentChar (#) is anywhere in that line, not just starting. You could consider changing it

Ohh. How would I do that? Something like:
```fortran
               if (index (line, commentChar) == 1) cycle
```
I can test that...

**Comment by atrayano** [comment]
Matt, I was trying to say to change the comment, not the code logic

**Comment by tclune** [comment]
Wouldn't @mathomp4's logic be more consistent with how we treat comment characters elsewhere?

**Comment by tclune** [comment]
I guess on its own it would not go far enough.

**Comment by mathomp4** [comment]
Oh. So maybe:
```fortran
if (index(trim(adjustl(line)), commentChar) == 1)
```
I really only care if the first character is a comment. If there is an in-line comment after data, the whole thing will crash, probably.

**Comment by tclune** [comment]
We're supposed to prefer "graceful" termination (i.e., with stack traces) over crashes.   This is esp. true when it comes to processing input data, as such files are per user in some circumstances and not vetted in the repository.         But maybe it is already properly trapped in that case and "crash" is just a rough description of what will happen?

**Pull request merged**
