### PR TITLE
Hotfix/wjiang/free directory win

### PR DESCRIPTION
**Pull request by weiyuan-jiang**
This is a bug. Directory Service needs to release the resources including its component "mutex".  If this fixes the mpi_finalize error, we should remove the suppressor of the mpi_finalize handler

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [x] I have tested this change with a run of GEOSgcm (if non-trivial)
- [ ] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [ ] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by mathomp4** [comment]
Blocking label until I can test.

**Comment by mathomp4** [comment]
Well, good news and bad news. Good news, the self tests are now "fixed" as far as I can tell. So this fixes #347.

Bad news, this doesn't help fix the full model issue:
```
Model Throughput:        0.000 days per day
Abort(806970127) on node 4 (rank 4 in comm 0): Fatal error in PMPI_Finalize: Other MPI error, error stack:
PMPI_Finalize(367)...............: MPI_Finalize failed
PMPI_Finalize(278)...............:
MPID_Finalize(1069)..............:
MPIDI_OFI_mpi_finalize_hook(1626): OFI domain close failed (ofi_init.c:1626:MPIDI_OFI_mpi_finalize_hook:Device or resource busy)
Abort(806970127) on node 2 (rank 2 in comm 0): Fatal error in PMPI_Finalize: Other MPI error, error stack:
PMPI_Finalize(367)...............: MPI_Finalize failed
PMPI_Finalize(278)...............:
MPID_Finalize(1069)..............:
MPIDI_OFI_mpi_finalize_hook(1626): OFI domain close failed (ofi_init.c:1626:MPIDI_OFI_mpi_finalize_hook:Device or resource busy)
>> Error << /usr/local/intel/2020/compilers_and_libraries_2020.0.166/linux/mpi/intel64/bin/mpirun  -np 6 ./GEOSgcm.x : status = 15; at /gpfsm/dswdev/mathomp4/Models/GEOSgcm-SLES12-stock/GEOSgcm/install-Release-Haswell/bin/esma_mpirun line 376.
GEOSgcm Run Status: 0
```

**Comment by bena-nasa** [comment]
I also just tried this branch. Like Matt the error at the end of the model that Matt referenced in the previous reply as I hit that as well.

**Comment by weiyuan-jiang** [comment]
A quick way to find out if it is the issue of  ONE_SIDED_COMM or not,  try TWO_SIDED_COMM and we will see if MAPL_LocstreamMod.F90 has the problem @bena-nasa

**Pull request merged**
