### PR TITLE
Update CircleCI to use both gfortran and ifort

### LINKED ISSUE #830: Update CircleCI to do Intel Builds
This is mainly a "reminder for Matt", but now that we have CircleCI back and being paid for, we can look at running Intel as well as GNU for MAPL.

Query for @tclune: Should I "matrix" what we currently have and do all the tests for both GNU and Intel? Or should we focus our uses (Intel for X,Y,Z, GNU for A,B,C)?

### PR DESCRIPTION
**Pull request by mathomp4**
This PR enables both gfortran and ifort builds of MAPL and GEOSgcm

Closes #830

### CODE REVIEW

**Comment by mathomp4** [comment]
Time to ask CircleCI Forum for help...

**Comment by mathomp4** [comment]
I await the inevitable discussion with @tclune on the commits I made to `MAPL_MemUtils.F90`, but it works!

**Comment by mathomp4** [comment]
Throwing on a blocker until @tclune can see and comment.

**Comment by mathomp4** [comment]
Getting close to undrafting. Frankly, I don't think we miss anything by not building/running GEOSfvdycore, and I think the ability to build/test both GNU and Intel is more important. I'll see what @tclune says.

**Comment by mathomp4** [comment]
Decided to try adding the GEOSadas to the CI. But it looks like we are missing something for MKL in the Docker image. Let's figure that out.

**Comment by mathomp4** [comment]
So, it turns out we can't quite do GEOSadas with MAPL yet. The reason is that GEOSadas is now "behind" GEOSgcm in a crucial way: Baselibs. So, time to make a PR...

**Comment by mathomp4** [comment]
PR to GEOSadas submitted: https://github.com/GEOS-ESM/GEOSadas/pull/103

**Review by tclune — APPROVED** [review]

**Pull request merged**
