### PR TITLE
Fix a bug so that MultigroupServer does not allow a file written by m…

### PR DESCRIPTION
**Pull request by weiyuan-jiang**
…ultiple processes at the same time

The names of files being written are saved. Every time before sending an empty rpocess, it checks the file name first. If it is still being written, it would wait to avoid writing a file in multiple processors.
## Description

This PR replaces the PR #2230 
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [x] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [x] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by mathomp4** [comment]
Blocking this as I need to fix up main...

**Review by tclune — DISMISSED** [review]

**Comment by mathomp4** [comment]
Unblocking. My tests show it works!

**Comment by mathomp4** [comment]
Uh oh. Bug in the UFS-like build. Testing incoming.

**Comment by mathomp4** [comment]
I think I fixed it. We need an *explicit* dependency on gFTL v2. I suppose we were getting that somehow when not building like UFS.

Maybe we should just convert all of MAPL to use v2... but I leave that to @tclune

**Review by mathomp4 — APPROVED** [review]

**Pull request merged**
