### PR TITLE
Feature/wjiang/mapl shared lib

### PR DESCRIPTION
**Pull request by weiyuan-jiang**
This is the first step to build individual GridComp as dynamic library. It should not interrupt the current building and running of the Apps that depends on MAPL. However, more evaluation ( speed, memory) should be done before merging to develop.
## Description

Add SHARED to build shared libs
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [ ] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [ ] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Review by tclune — DISMISSED** [review]

**Comment by tclune** [comment]
Hopefully this goes through smoothly this time.

**Comment by weiyuan-jiang** [comment]
If I merge, the libraries will look like this:
 ls
cmake            libMAPL.cap.so      libMAPL_cfio_r8.so    libMAPL.pfio.so      libMAPL.shared.so  Python
libMAPL.base.so  libMAPL_cfio_r4.so  libMAPL.gridcomps.so  libMAPL.profiler.so  libMAPL.so

And all the app's that uses MAPL will have LD_LIBRARY_PATH set correctly before running

**Comment by tclune** [comment]
@mathomp4 will have to let me know if we should use super powers to do the merge or if the failing tests are a real issue.

**Comment by mathomp4** [comment]
I am working on the fix for the FV3 Standalone. The issue is that it didn't have `${GEOSDIR}/lib` in `LD_LIBRARY_PATH`. It didn't need it in the past because FV3 Standalone didn't care about mom5/mom6. But if MAPL is an so...

**Comment by mathomp4** [comment]
@weiyuan-jiang It looks like we need a Changelog entry for this to (eventually) be accepted once testing is complete and the DNA label is removed.

**Comment by weiyuan-jiang** [comment]
I have tested c720 one day run. 
There is about 0.5% difference for the performance
1) For static libraries build, it takes about 42 minutes 30 seconds ( 3 times) to finish the job.
2) For shared libraries build, it takes about 42 minutes 45 minutes ( 3 times too) to finish the the job. 
 There are no much memory usage difference either.  Here is the output.  
1) static: GCM Date: ........:    40.0% Mem Comm:Used
2)shared: AGCM Date: ......... 40.6% Mem Comm:Used

**Comment by tclune** [comment]
Ugh.   Just enough penalty to be something that Bill will care about.    Could your repeat the measurements once more just to be ascertain the natural variability?   I'll then check with Bill.

**Comment by weiyuan-jiang** [comment]
I run GEOSgcm c720 6 times, here is the Walltime Used to finish the one day job.

static : 
     00:42:30   00:42:36   00:42:02   00:42:28   00:42:58   00:42:20  
     mean 00:42:29 
     std : 18.5
 
shared lib:
     00:42:44   00:42:46   00:42:48   00:42:52   00:42:07   00:42:06  
     mean 00:42:34 
     std : 21.3

Considering the system's variance, there is not much difference between shared build and static build.

**Comment by weiyuan-jiang** [comment]
@tclune ,  Should we move on and merge it?

**Comment by tclune** [comment]
I'm ok with merging if @mathomp4 is ok with the status of the CI tests.

**Comment by mathomp4** [comment]
I think it worked the last time I tested. If nothing else, though, it does need a changelog entry for sure! This will probably lead to MAPL 2.5.0 since it's a pretty big change.

**Comment by mathomp4** [comment]
I have updated `CHANGELOG.md` to add some entries to get past the enforcer

**Review by tclune — APPROVED** [review]

**Comment by mathomp4** [comment]
Some news. I've tested this at NCCS and NAS at it seems happy at least with `Release` build. But, when I tried it on my mac I got:
```
 Character Resource Parameter: RATS_PROVIDER:PCHEM
 Character Resource Parameter: pchem_clim:species.data
 Integer*4 Resource Parameter: pchem_clim_years:39
dyld: lazy symbol binding failed: Symbol not found: _preadv
  Referenced from: /Users/mathomp4/installed/Compiler/gcc-gfortran-10.2.0/openmpi/4.1.0/lib/openmpi/mca_fbtl_posix.so
  Expected in: flat namespace

dyld: Symbol not found: _preadv
  Referenced from: /Users/mathomp4/installed/Compiler/gcc-gfortran-10.2.0/openmpi/4.1.0/lib/openmpi/mca_fbtl_posix.so
  Expected in: flat namespace


Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x125fe6d3d
#1  0x125fe616d
#2  0x7fff6a9055fc
```
I'm going to try building and running this branch on discover with GCC 10/Open MPI. See if it's a macOS thing or...not.

**Comment by mathomp4** [comment]
Oh, and I added the blocker label because I wanted to test this!

**Comment by mathomp4** [comment]
Ah. I get the failure even *without* this branch, so I guess we can't blame it!

**Comment by atrayano** [comment]
@mathomp4 I found this thread discussing preadv on a Mac
https://github.com/facebook/folly/issues/412
See if applies to you

**Comment by mathomp4** [comment]
Well, on the plus side `Release` with GCC 10 works on Discover. So it seems to be a macOS thing...or a Matt thing. As a final check, I'm going to do a `Debug` GCC build on Discover. My guess is, it'll work. If so, may as well take this into MAPL!

**Comment by mathomp4** [comment]
Welp, `Debug` GCC 10 worked as well on Discover. Thus, I blame macOS or me or something. But I think that means this can be moved into `develop`.

I'll make a new Issue on GEOSgcm so I can track the other issue.

As for this, I'll remove the blocking label and this can be merged in.

**Pull request merged**
