### PR TITLE
fixes #2683

### LINKED ISSUE #2683: Multi-dimension coordinate variables are not picking up the deflate level of a collection in History
A user was asking why the cubed-sphere files produced by History were so big compared to a lat-lon output file given a similar number of variables and comparable number of total grid points.  The answer is that the cubed-sphere files have both the centers and corners in the file, in double precision. 

But one thing we did notice, and the point of the issue, is that if the collection set a non-zero deflate level, while the variables were compressed in the output file, the center and corner coordinates were not being compressed.

So this was clearly an oversight on my part and should be fixed. There seems no reason that if the variables are being compressed, that the coordinates should not either for consistency. I've already tested this so just making an issue for the PR.

### PR DESCRIPTION
**Pull request by bena-nasa**
This fixes #2683
It was a silly oversight on my part. If the variables in a collection are compressed, compress the coordinate variables too, just silly not too...

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [X] I have tested this change with a run of GEOSgcm (if non-trivial)
- [X] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [X] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Review by tclune — CHANGES_REQUESTED** [review]
I think we need to do this as a hotfix on whichever release of MAPL R21C is using.

Please check.

**Comment by mathomp4** [comment]
> I think we need to do this as a hotfix on whichever release of MAPL R21C is using.
> 
> Please check.

@tclune R21C has a branch here called `R21C`. It's essentially v2.35.3+more. This is the branch naming scheme preferred by the R21C folks (you'll see the branch in many places).

**Comment by bena-nasa** [comment]
> I think we need to do this as a hotfix on whichever release of MAPL R21C is using.
> 
> Please check.

@tclune 

Don't we also want this in develop so it gets into a future release? That's why I made this here.

I know we also will need to do this as a patch for the MAPL R21C version if that is what Amal wants. I will check on that of course.

**Comment by bena-nasa** [comment]
I was just testing this in ExtDataDriver.x, thought this was a harmless PR, but just tried in model and things crashed. I've put a DNA on for now while I debug

**Comment by mathomp4** [comment]
> I think we need to do this as a hotfix on whichever release of MAPL R21C is using.
> 
> Please check.

Superseded by #2689

**Pull request closed without merging**
