### PR TITLE
Fix to multi day run

### PR DESCRIPTION
**Pull request by Gvilla1000-nasa**
## Description
This PR fixes the Multi-Day GEOS non-zero diff bug. Bug appeared because `base/MAPL_sun_uc.F90` is the only module in MAPL that uses `MAPL_DEGREES_TO_RADIANS` in single precision. Rather than creating a `MAPL_DEGREES_TO_RADIANS_R4`, I went with changing the double precision instances to `MAPL_DEGREES_TO_RADIANS_R8` as there is precedence for other double precision variables. However, I didn't create a `MAPL_RADIANS_TO_DEGREES_R8` because compilation issues would have appeared since this module `Components/@GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/GEOS_MoistGridComp.F90` would still use the old name.

If there are any other recommendations, let me know.

## Related Issue

#961 

## Motivation and Context
Fixes bug that appeared from Constants refactoring

## How Has This Been Tested?
I ran the GEOS-5 model past 5 days and 5hours which was the threshold identified where non-zero diffs started appearing and it was finally zero-diff.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [x] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [x] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Review by tclune — APPROVED** [review]
The next question is whether you should follow up with a PR onto the release/MAPL-v3 branch which eliminates the `_R8`.   Lot of trouble for minimal benefit.

**Comment by mathomp4** [comment]
Oooh. Very nice spot, @Gvilla1000-nasa!

And, yeah, I wonder if perhaps we should instead make a `MAPL_DEGREES_TO_RADIANS_REAL32` as it's the *one* place that needs it? Rather than rename the R8 ones?

**Comment by mathomp4** [comment]
Also, for consistency, should we have something similar for `MAPL_RADIANS_TO_DEGREES`?

**Comment by mathomp4** [comment]
> Also, for consistency, should we have something similar for `MAPL_RADIANS_TO_DEGREES`?

Ahh. I see what you mean about Moist! Never mind. Me dumb :)

**Comment by Gvilla1000-nasa** [comment]
@mathomp4 that was my initial thought to be honest...but went with the way of consistency. 2 file change vs 11 right now. But if that is the preferred method (which would also eliminate the need of doing a new PR to the MAPL-3 branch), I can go ahead and do it.

**Comment by mathomp4** [comment]
> @mathomp4 that was my initial thought to be honest...but went with the way of consistency. 2 file change vs 11 right now. But if that is the preferred method (which would also eliminate the need of doing a new PR to the MAPL-3 branch), I can go ahead and do it.
> 
> EDIT: I am referring to creating a `MAPL_DEGREES_TO_RADIANS_REAL32` and `MAPL_RADIANS_TO_DEGREES_REAL32`

Yeah. I guess it's an @tclune decision (passing the buck... 😄 ). Hmm...

**Comment by mathomp4** [comment]
I just did a test with this branch and turning on Replay and ran for 10 days and it too is zero-diff. Huzzah!

**Pull request merged**
