### PR TITLE
The standalone program `pfio_MAPL_demo.F90` write several time record…

### PR DESCRIPTION
**Pull request by JulesKouatchou**
…s of 2D and 3D arrays.

PFIO utility methods are used to:
- Define dimensions
- Create variables and set variable attributes
- Set global attributes
- Write out data in netCDF files (same collection).

The program has an initialization section and a time stepping section to mimic
the steps needed in a real application.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [ ] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [x] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Review by tclune — CHANGES_REQUESTED** [review]
GitHub is reporting conflicts, which is odd given that this is a new file.   Are you certain you started the branch from the `develop` branch?   Please resolve before resubmitting.

You should add a comment in the CHANGELOG.md file.   Just 1-2 lines stating that a new demo was added and what it demonstrates.

**Comment by mathomp4** [comment]
@JulesKouatchou First, I rebased this PR as it should be against `develop` not against `main` as we usually only take hotfixes to the library against `main` (changes to tests usually aren't considered hotfixes).

Second, it looks like `pfio_MAPL_demo.F90` was changed recently due to changes in MAPL (how we handle command line options) since you made your branch. I've tried to make right edits and merge `develop` into your branch  to fix the conflict. Can you please check to see if the code is still good.

**Comment by weiyuan-jiang** [comment]
The file is not new.  I changed it after we changed the FlapCapOption to FlapCLI. That is why there is conflict.

**Comment by JulesKouatchou** [comment]
@mathomp4 Do you still want me to check the file? I know that it is a little different than the original one created by @weiyuan-jiang but it does the same thing.

**Comment by mathomp4** [comment]
> @mathomp4 Do you still want me to check the file? I know that it is a little different than the original one created by @weiyuan-jiang but it does the same thing.

If you don't see anything big, probably no need, but could you add an entry to the CHANGELOG.md about this? Most MAPL PRs require changing the CHANGELOG to be accepted (if non-trivial)

**Comment by weiyuan-jiang** [comment]
I have tested it and it is good to merge.  I am wondering why I cannot approve this PR. @mathomp4

**Pull request merged**
