### PR TITLE
Add module to process NetCDF datetimes

### PR DESCRIPTION
**Pull request by darianboggs**
## Description

Process NetCDF datetimes in the form of an integer span and a string, containing the time unit and start time, to an ESMF_Time (start time) and an ESMF_TimeInterval (time span), with optional output of the time unit (as a string) and the end time (ESMF_Time). The end time is the time expressed by the NetCDF integer and string

## Motivation and Context

This functionality allow better parsing of datetimes in NetCDF files

## How Has This Been Tested?

The MAPL base and shared test suites completed successfully. This is a new feature, so it doesn't affect existing MAPL.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [x] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [x] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by darianboggs** [comment]
Don't merge yet. Changing branch to merge to.

**Comment by darianboggs** [comment]
OK. `develop` is base branch.

**Review by tclune — CHANGES_REQUESTED** [review]
Problem with branching.

**Comment by darianboggs** [comment]
Abort. New PR. #2121.

**Pull request closed without merging**
