### PR TITLE
Update changelog and version for 2.3.5 release

### PR DESCRIPTION
**Pull request by mathomp4**
This is a preparatory change for pulling `develop` into `main` for a 2.3.5 release.

### CODE REVIEW

**Review by tclune — APPROVED** [review]

**Comment by tclune** [comment]
Note.  Atanas has some fixes related to monthly averages that should be coming in as hotfixes soon.   You may want to wait on those to do the actual release.

**Comment by mathomp4** [comment]
Ah. Okay. I'll add a blocker tag to this for now. If @atrayano pulls against `main` I can up the version number in this. If he pulls against `develop`, I can update this.

**Comment by mathomp4** [comment]
Okay. This PR fixes up the Changelog and CMakeLists for a 2.3.5 release. I've re-requested a review from @GEOS-ESM/mapl-team as my updates dismissed the old review.

**Review by atrayano — APPROVED** [review]
Looks OK

**Review by tclune — APPROVED** [review]

**Pull request merged**
