### PR TITLE
Removes MAPL_IO dependency from CubedSphere and LatLon GridFactories

### PR DESCRIPTION
**Pull request by Gvilla1000-nasa**
## Description
Removes usage of MAPL_IO subroutines in CubedSphere and LatLon Grid Factories. Replaced by usage of the `newunit` clause to `open`. This will allow further refactoring of code inside base.

## Related Issue

#1196 

## Motivation and Context

Making this change allows for further refactoring of code such as separating the MAPL_IO code away from the base directory.

## How Has This Been Tested?

The modified code is only executed by GEOSldas, therefore a nightly test of ldas with these MAPL edits was performed. All suggested cases (conus, global, globalcs, globalcnclm4) passed and were zero diff. For sanity purposes, GEOSgcm was tested in normal and REPLAY modes and both instances were zero diff.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [x] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [x] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Review by atrayano — APPROVED** [review]
Looks reasonable

**Comment by Gvilla1000-nasa** [comment]
I'm looking into why this failed on intel. I looked at the CI build log and couldn't see anything immediately pop out.

**Comment by Gvilla1000-nasa** [comment]
I just tested a local build with intel and it compiled without issue. The changes done here are also only related to MAPL and MAPL built successfully according to the tests. I'm unsure what went wrong with the CI GEOSgcm ifort test.

**Comment by atrayano** [comment]
@Gvilla1000-nasa CI build uses gfortran. I think I found the actual error in the log file (see below)
/root/project/GEOSgcm/src/Components/@GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphysics_GridComp/@GEOSchem_GridComp/MAMchem_GridComp/microphysics/abortutils.F90(6): error #7005: Error in reading the compiled module file.   [PFIO_MULTICOMMSERVERMOD]

**Comment by mathomp4** [comment]
Those are some weird errors:
```
/root/project/GEOSgcm/src/Components/@GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphysics_GridComp/@GEOSchem_GridComp/MAMchem_GridComp/microphysics/abortutils.F90(6): error #7005: Error in reading the compiled module file.   [PFIO_MULTICOMMSERVERMOD]
  use MAPL
------^
/root/project/GEOSgcm/src/Components/@GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphysics_GridComp/@GEOSchem_GridComp/MAMchem_GridComp/microphysics/abortutils.F90(5): error #6580: Name in only-list does not exist or is not accessible.   [IULOG]
  use cam_logfile, only: iulog
-------------------------^
```

I'm going to re-run the build test. I can't see why that would happen...

**Comment by mathomp4** [comment]
Looks like a CircleCI blip or something.

**Comment by tclune** [comment]
Those look like something switched compilers mid build.   Hard to see how that would happen with the automated tests though.  (I see it frequently on my laptop, but we all know how careful I can be ...)

**Pull request merged**
