### PR TITLE
Feature/tclune/#1474 new yafyaml interface

### PR DESCRIPTION
**Pull request by tclune**
## Description

Updated code that uses yaFyaml due to new interfaces.

## Related Issue

This is for MAPL v3 - which needs additional functionality provided in the more recent yaFyaml version.
## How Has This Been Tested?

Has only been compiled on OSX - has not been run.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)
- [x] Updated internal interfaces.
## Checklist:

- [ ] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [ ] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by tclune** [comment]
@bena-nasa Note that the regression tests can't work until @mathomp4 updates baselibs and the CI for MAPL-v3

**Comment by tclune** [comment]
Also this branch includes other broken MAPL-3 changes.   I'll update this branch once I work through those.

**Comment by bena-nasa** [comment]
@tclune has Matt made a baselibs with the new yafyaml interfaces on Discover yet?

**Comment by mathomp4** [comment]
Okay. A few things. 

First, you can find the GFE Baselibs here:
```
/discover/swdev/gmao_SIteam/Baselibs/TmpBaselibs/ESMA-Baselibs-6.2.13-with-GFErepo/x86_64-pc-linux-gnu/ifort_2021.3.0-intelmpi_2021.3.0
```

Second, I then tried to build this branch. From mepo:
```
$ mepo status
Checking status...
GEOSgcm                | (b) release/MAPL-v3 (DH, b005d8a)
env                    | (t) v3.13.0 (DH)
   | g5_modules: modified, not staged
cmake                  | (t) v3.12.0 (DH)
ecbuild                | (t) geos/v1.2.0 (DH)
NCEP_Shared            | (t) v1.2.0 (DH)
GMAO_Shared            | (t) v1.5.3 (DH)
MAPL                   | (b) feature/tclune/#1474-new-yafyaml-interface
FMS                    | (t) geos/2019.01.02+noaff.8 (DH)
GEOSgcm_GridComp       | (b) release/MAPL-v3 (DH, 4b5cbc03)
FVdycoreCubed_GridComp | (b) release/MAPL-v3 (DH, 778bb15)
fvdycore               | (t) geos/v1.3.0 (DH)
GEOSchem_GridComp      | (t) v1.9.1 (DH)
HEMCO                  | (t) geos/v2.2.3 (DH)
geos-chem              | (t) geos/v13.0.0-rc1 (DH)
GOCART                 | (t) v2.0.5 (DH)
GEOS_OceanGridComp     | (t) v1.1.0 (DH)
mom                    | (t) geos/5.1.0+1.2.0 (DH)
mom6                   | (t) geos/v2.0.3 (DH)
cice6                  | (t) geos/v0.0.1 (DH)
sis2                   | (t) geos/v0.0.1 (DH)
RRTMGP                 | (t) geos/v1.5+1.0.0 (DH)
GEOSgcm_App            | (b) release/MAPL-v3 (DH, 642e246)
UMD_Etc                | (t) v1.1.0 (DH)
CPLFCST_Etc            | (t) v1.0.1 (DH)
```

However, a build with this fails with:
```
[100%] Building Fortran object src/Shared/@MAPL/generic3g/CMakeFiles/MAPL.generic3g.dir/UserSetServices.F90.o
/discover/swdev/mathomp4/Models/GEOSgcm-MAPL3-UseGFEBaselibs-TomMAPLBranch/GEOSgcm/src/Shared/@MAPL/generic3g/UserSetServices.F90(76): error #8191: The procedure target must be a procedure or a procedure pointer.   [USERROUTINE]
      proc_setservices%userRoutine => userRoutine
--------------------------------------^
/discover/swdev/mathomp4/Models/GEOSgcm-MAPL3-UseGFEBaselibs-TomMAPLBranch/GEOSgcm/src/Shared/@MAPL/generic3g/UserSetServices.F90(72): error #6404: This name does not have a type, and must have an explicit type.   [USERROUTINE]
   function new_proc_setservices(userRoutine) result(proc_setservices)
---------------------------------^
compilation aborted for /discover/swdev/mathomp4/Models/GEOSgcm-MAPL3-UseGFEBaselibs-TomMAPLBranch/GEOSgcm/src/Shared/@MAPL/generic3g/UserSetServices.F90 (code 1)
src/Shared/@MAPL/generic3g/CMakeFiles/MAPL.generic3g.dir/build.make:87: recipe for target 'src/Shared/@MAPL/generic3g/CMakeFiles/MAPL.generic3g.dir/UserSetServices.F90.o' failed
```

**Comment by tclune** [comment]
yay - more compiler workarounds to find.    I have a more advanced branch on my laptop that builds with NAG and even runs some new unit tests.    But I think ifort worked when I pushed this one.  It is now failing on my advanced branch.

**Comment by tclune** [comment]
@mathomp4 and @bena-nasa I think I've fixed the typo above.  Must have fixed no my end after pushing and then forgot.

**Comment by mathomp4** [comment]
> @mathomp4 and @bena-nasa I think I've fixed the typo above. Must have fixed no my end after pushing and then forgot.

Can confirm. Intel is now happy to compile generic3g

**Comment by bena-nasa** [comment]
@tclune This branch is out of date with ExtData2G due to the rapid development in the last several weeks that is now on develop due to syntax changes I made in the file so I can't confirm it works fully. It was able to load the yaml file and start to process the configuration (yaml_node) but crashed because the syntax this branch is expecting is now out of date, so I suspect the yaml changes are working

**Comment by tclune** [comment]
ok - how do you want to proceed?     I don't think we can avoid the painful merge no matter what, as my subsequent MAPL 3 development has been on top of this branch.   Easiest would probably be to overwrite your files on this branch with your new version and then manually update the YAML.  Should not take long, esp. if you use the existing delta on this branch as a guide.

**Comment by mathomp4** [comment]
Oh wow. Up to four conflicted files now! A couple seem pretty trivial to fix, but the others seem more complicated.

**Comment by bena-nasa** [comment]
Closing this PR, ended up fixing the conflicts on a new branch

**Pull request closed without merging**
