### PR TITLE
Fixes #2767- change default vertical dim spec

### LINKED ISSUE #2767: Change default for vertical dim spec
Current default is VERTICAL_DIM_NONE (eg surface vars).   A better default is VERTICAL_DIM_UNDEF.  This is a small change, except that many/most of the scenario unit tests will need to be addressed as a consequence.

### PR DESCRIPTION
**Pull request by tclune**
## Types of change(s)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist
- [ ] Tested this change with a run of GEOSgcm
- [x] Ran the Unit Tests (`make tests`)

## Description

Lots of other tangential changes.  But mostly propagating changes in the yaml files in tests.

### CODE REVIEW

**Review by bena-nasa — DISMISSED** [review]

**Review by bena-nasa — DISMISSED** [review]

**Review by bena-nasa — APPROVED** [review]

**Review by mathomp4 — APPROVED** [review]
Approve!

**Review by mathomp4 — APPROVED** [review]
Approve again

**Review by mathomp4 — APPROVED** [review]
Approve for cmake

**Comment by tclune** [comment]
Git hub confused. Created a new PR that worked fine.

**Pull request closed without merging**
