### PR TITLE
Fix perpetual year timers

### LINKED ISSUE #795: Perpetual Year runs can have weird during-run timer output
As seen when I was looking at one of @sanAkel's runs looking at #762, his log output looked weird. So I did some experiments. Here is a normal C24 run:
```
 AGCM Date: 2000/04/15  Time: 03:00:00  Throughput(days/day)[Avg Tot Run]: 1911.8  474.3 2043.5  TimeRemaining(Est) 000:00:33   22.8% :  10.7% Mem Comm:Used
 AGCM Date: 2000/04/15  Time: 03:15:00  Throughput(days/day)[Avg Tot Run]: 1946.0 3420.3 3553.2  TimeRemaining(Est) 000:00:32   22.8% :  10.6% Mem Comm:Used
 AGCM Date: 2000/04/15  Time: 03:30:00  Throughput(days/day)[Avg Tot Run]: 1975.5 3185.9 3283.7  TimeRemaining(Est) 000:00:31   22.8% :  10.6% Mem Comm:Used
 AGCM Date: 2000/04/15  Time: 03:45:00  Throughput(days/day)[Avg Tot Run]: 2006.4 3398.6 3510.5  TimeRemaining(Est) 000:00:30   22.8% :  10.6% Mem Comm:Used
```
and now a run with `PERPETUAL_YEAR: 2000`:
```
 AGCM Date: 2000/04/15  Time: 03:00:00  Throughput(days/day)[Avg Tot Run]: 1944.5  514.8 2037.8  TimeRemaining(Est) 000:00:33   22.8% :  10.6% Mem Comm:Used
 AGCM Date: 2000/04/15  Time: 03:15:00  Throughput(days/day)[Avg Tot Run]: 1978.0 3384.5 3553.8  TimeRemaining(Est) 000:00:32   22.8% :  10.6% Mem Comm:Used
 AGCM Date: 2000/04/15  Time: 03:30:00  Throughput(days/day)[Avg Tot Run]: 2006.0 3107.5 3249.5  TimeRemaining(Est) 000:00:31   22.8% :  10.6% Mem Comm:Used
 AGCM Date: 2000/04/15  Time: 03:45:00  Throughput(days/day)[Avg Tot Run]: 2036.0 3342.2 3557.9  TimeRemaining(Est) 000:00:30   22.8% :  10.6% Mem Comm:Used
```
So not bad as my restarts are from 2000.

Now let's try `PERPETUAL_YEAR: 2012`:
```
 AGCM Date: 2012/04/15  Time: 03:00:00  Throughput(days/day)[Avg Tot Run]: ******  528.1 2025.2  TimeRemaining(Est) ***:59:48   22.8% :  10.7% Mem Comm:Used
 AGCM Date: 2012/04/15  Time: 03:15:00  Throughput(days/day)[Avg Tot Run]: ****** 3332.1 3497.5  TimeRemaining(Est) ***:59:48   22.8% :  10.6% Mem Comm:Used
 AGCM Date: 2012/04/15  Time: 03:30:00  Throughput(days/day)[Avg Tot Run]: ****** 3098.0 3240.5  TimeRemaining(Est) ***:59:48   22.8% :  10.6% Mem Comm:Used
 AGCM Date: 2012/04/15  Time: 03:45:00  Throughput(days/day)[Avg Tot Run]: ****** 3353.6 3520.3  TimeRemaining(Est) ***:59:48   22.8% :  10.6% Mem Comm:Used
```
So yeah. MAPL realizes it might take a while for my Year 2000 restarts to make it to the year 2012? And because I was curious, I went to MAPL and did:
```diff
index ef94ff7..ae4b938 100644
--- a/gridcomps/Cap/MAPL_CapGridComp.F90
+++ b/gridcomps/Cap/MAPL_CapGridComp.F90
@@ -1313,7 +1313,7 @@ contains
                                       LOOP_THROUGHPUT,INST_THROUGHPUT,RUN_THROUGHPUT,HRS_R,MIN_R,SEC_R,&
                                       mem_committed_percent,mem_used_percent
     1000 format(1x,'AGCM Date: ',i4.4,'/',i2.2,'/',i2.2,2x,'Time: ',i2.2,':',i2.2,':',i2.2, &
-                2x,'Throughput(days/day)[Avg Tot Run]: ',f6.1,1x,f6.1,1x,f6.1,2x,'TimeRemaining(Est) ',i3.3,':'i2.2,':',i2.2,2x, &
+                2x,'Throughput(days/day)[Avg Tot Run]: ',f0.1,1x,f0.1,1x,f0.1,2x,'TimeRemaining(Est) ',i0.0,':'i2.2,':',i2.2,2x, &
                 f5.1,'% : ',f5.1,'% Mem Comm:Used')

         _RETURN(_SUCCESS)
```
and:
```
 AGCM Date: 2012/04/15  Time: 03:00:00  Throughput(days/day)[Avg Tot Run]: 34240506.7 524.5 2041.2  TimeRemaining(Est) -1:59:48   22.7% :  10.6% Mem Comm:Used
 AGCM Date: 2012/04/15  Time: 03:15:00  Throughput(days/day)[Avg Tot Run]: 33419221.7 3320.0 3483.2  TimeRemaining(Est) -1:59:48   22.7% :  10.6% Mem Comm:Used
 AGCM Date: 2012/04/15  Time: 03:30:00  Throughput(days/day)[Avg Tot Run]: 32578703.1 3086.3 3226.2  TimeRemaining(Est) -1:59:48   22.7% :  10.6% Mem Comm:Used
 AGCM Date: 2012/04/15  Time: 03:45:00  Throughput(days/day)[Avg Tot Run]: 31838810.1 3341.4 3507.0  TimeRemaining(Est) -1:59:48   22.7% :  10.6% Mem Comm:Used
```
On the plus side, I can now say I can make the model ~16000x faster (or I guess, infinitely faster according to the TimeRemaining). 😄 

Not sure of the "right thing" to do here. Suppress some prints if perpetual year? Or maybe figure out a way to massage the clocks it's looking at so that it works? Though I suppose things might go really nutty if I was in December and the year boundary was crossed.

### PR DESCRIPTION
**Pull request by mathomp4**
## Description

This fixes an issue (#795) seen during perpetual year runs. 

## Related Issue

Closes #795 

## Motivation and Context

Makes the timers more generally useful.

## How Has This Been Tested?

Runs of GEOSgcm in both AMIP and Perpetual Year (2012 for 2000 restarts)

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [X] I have tested this change with a run of GEOSgcm (if non-trivial)
- [X] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [X] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by mathomp4** [comment]
Note: I think this is good, but if @sanAkel could maybe test it with one of his "real world" perpetual year runs, that'd probably be a Good Thing™

**Comment by mathomp4** [comment]
I'm also currently really debating making `set_step_counter(this,n)` to just `initialize_step_counter(this)` where it puts it at zero. That way all three new functions have essentially no inputs (other than `this`). I'll let @tclune weigh in.

**Review by tclune — APPROVED** [review]

**Comment by tclune** [comment]
I think it is useful to be able to set it to another value.  E.g., we might someday want to capture n in checkpoint restart and then restore to the value at the end of the previous run.

**Comment by sanAkel** [comment]
Is there a need for _my_ testing?

**Comment by tclune** [comment]
@sanAkel  - the logic is fairly simple, but we have only tested it under an ordinary run.   So testing (by someone) in a perpetual year scenario would be of some value.    Not sure if more than a year's run would be needed to check everything or not ...   

Maybe don't do a special test, but the next time you start such a run, grab this MAPL first.  (And it may me moot by then - it will have been merged into a release.)

**Comment by sanAkel** [comment]
@tclune I may start a new run next week, didn't intend it to be _perpetual_, but I could. If it is merged, that's okay, I will pay attention to the timers and let you guys know if I see something odd as @mathomp4 saw in https://github.com/GEOS-ESM/MAPL/issues/795

**Comment by mathomp4** [comment]
I did test in perpetual run, but not in a "real" one. Just me changing the value in CAP.rc. But I think it's good. We'll find out tonight during my tests if I broke anything :)

**Comment by sanAkel** [comment]
@mathomp4 , @tclune, reporting on this:

1. a swap in `MAPL`: from `v2.6.6` to `v2.6.7` is **zero-diff** (MOM6 coupled model)
2. I see better timing info, more _meaningful_ in a perpetual year ran that what I got with  `MAPL v2.6.6`

**Pull request merged**
