### PR TITLE
add pflogger stub to skip pflogger library

### PR DESCRIPTION
**Pull request by weiyuan-jiang**
add pflogger stub to skip pflogger library.  If cmake command line is with -DBUILD_WITH_PFLOGGER=OFF, a stub is created to replace the pflogger
## Description

add pflogger_stub subdirectory
## Related Issue

This PR resolves issue #787 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [x] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [ ] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by weiyuan-jiang** [comment]
I added DNA label because two more changes are needed : 1) component.yaml for new ESMA_cmake and 2) CHANGELOG.md

**Comment by weiyuan-jiang** [comment]
CHANGELOG.md updated. Now it needs components.yaml.

**Comment by mathomp4** [comment]
> CHANGELOG.md updated. Now it needs components.yaml.

I've released ESMA_cmake v3.3.9. and pushed an update. I'm still a bit concerned that the GitHub Actions failed...

**Comment by mathomp4** [comment]
Oy. Okay. The GEOSgcm build will fail until https://github.com/GEOS-ESM/GEOSgcm/pull/281 is pulled into GEOSgcm because it needs ESMA_cmake v3.3.9

**Comment by mathomp4** [comment]
@tclune @weiyuan-jiang Now I'm a bit interested in this. Why would this fail? Okay, without ESMA_cmake v3.3.9, then the GEOSgcm build would not see the `BUILD_WITH_PFLOGGER` as `ON` and so default to `OFF`. But doesn't this mean that the stub would take over?

**Review by tclune — DISMISSED** [review]

**Comment by mathomp4** [comment]
```
CMake Error at @cmake/@ecbuild/cmake/ecbuild_add_library.cmake:268 (add_library):
  add_library cannot create target "pflogger" because an imported target with
  the same name already exists.
Call Stack (most recent call first):
  @cmake/@ecbuild/cmake/ecbuild_add_library.cmake:576 (ecbuild_add_library_impl)
  @cmake/esma_add_library.cmake:93 (ecbuild_add_library)
  src/Shared/@MAPL/pflogger_stub/CMakeLists.txt:12 (esma_add_library)
```
@tclune is this some Baselibs thing? pFlogger is "magically" in the CMake chain because Baselibs 6.1.0 doesn't have the latest version of some library which is implicitly bringing in the pflogger target?

**Comment by tclune** [comment]
Ugh.  Good point.   This is the advantage of using the opposite sentiment.   I think there might be a way to check to see if an option exists at all, and maybe we should add that to the other pflogger PR's.   I.e.,  if the option exists _and_ it is OFF then use the stub.

**Comment by tclune** [comment]
But yes - the stub should have taken over, which should not have failed presuming the stub has all the necessary interfaces.   I suspect @weiyuan-jiang and myself may have missed a few.  E.g., there is a function that returns the severity level of a logger so that you can skip entire blocks of logging.    (That should always return something very high - CRITICAL in the stub.)

**Comment by tclune** [comment]
This happens when `find_package()` is finding the baselibs package despite the intended guards.  So either the option was not set early enough, or it is not being used in advance of that find_package.

**Comment by weiyuan-jiang** [comment]
@tclune I actually added function isEnableFor() as always .false.  The issue here is not the stub, it is probably about cmake. I guess we need to move the option BUILD_WITH_PFLOGGER way up

**Comment by weiyuan-jiang** [comment]
Is that  possible that cmake is too smart so it detects pflogger automatically in the baselib?

**Comment by tclune** [comment]
No that does not happen.   It can be too smart about finding it in the wrong directory,  but it will only "find" it if an explicit `find_package()` is used.

**Comment by mathomp4** [comment]
Okay. Scott has merged. Let me make a trivial edit to force new builds.

**Comment by mathomp4** [comment]
Okay. Trivial commit in and it looks like the GCM CMake is happier thanks to @sdrabenh. 

The next issue is that some of the "act like pflogger" bits disappeared. I'm looking at how:
```cmake
add_library (${this} STATIC ${SRCS})
add_library(PFLOGGER::pflogger ALIAS pflogger)

set (dest "PFLOGGER-${PFLOGGER_VERSION_MAJOR}.${PFLOGGER_VERSION_MINOR}")

target_include_directories(${this} PUBLIC
  $<BUILD_INTERFACE:${PFLOGGER_BINARY_DIR}/include>
  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>
  $<INSTALL_INTERFACE:${dest}/include>
  )

target_link_libraries(${this} PUBLIC GFTL_SHARED::gftl-shared GFTL::gftl)

install (TARGETS pflogger EXPORT PFLOGGER DESTINATION ${dest}/lib)
install (DIRECTORY  ${PROJECT_BINARY_DIR}/include/ DESTINATION ${dest}/include)
install (FILES  ${PROJECT_SOURCE_DIR}/src/error_handling_macros.fh DESTINATION ${dest}/include)
```
became:
```cmake
if (ESMA_USE_GFE_NAMESPACE)
   esma_add_library (${this} SRCS ${srcs} DEPENDENCIES GFTL_SHARED::gftl-shared TYPE SHARED)
else ()
   esma_add_library (${this} SRCS ${srcs} DEPENDENCIES gftl-shared TYPE SHARED)
endif ()

target_include_directories (${this} PUBLIC $<BUILD_INTERFACE:${MAPL_SOURCE_DIR}/include>)
```

I think we might need some combination?

And should the pflogger stub be a `TYPE SHARED` library?

**Comment by weiyuan-jiang** [comment]
I think in the baselib, pflogger should be type SHARED, or at least we should have both STATIC and SHARED

**Comment by mathomp4** [comment]
I removed the Contingent flag as this seems to be good...though for some stupid reason that triggered new CI? Ugh. Time to stare at the CI yaml...

**Comment by mathomp4** [comment]
Passed. I'm re-requesting the @tclune review. I think we are close to new MAPL release!

**Review by tclune — APPROVED** [review]

**Pull request merged**
