### PR TITLE
release logger mpi resource before mpi_finalize

### PR DESCRIPTION
**Pull request by weiyuan-jiang**
Free pFlogger mpi resources before mpi_finalize. This should go with the new pflogger lib.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [x] I have tested this change with a run of GEOSgcm (if non-trivial)
- [ ] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [ ] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by weiyuan-jiang** [comment]
This pull request requires new pflogger base lib

**Comment by mathomp4** [comment]
I've added a blocker to this so I can update the CI on the branch as well.

**Comment by mathomp4** [comment]
I wonder if we should remove the workaround now for MPI_comm_set_errhandler? If this "solves" all the issues we were seeing for a while?

**Comment by tclune** [comment]
If it solves the known issues, then yes you should remove the bandaid.  That way we'll know if a similar issue is (re) introduced down the road.

**Comment by mathomp4** [comment]
All seems good to me. @tclune can you look over the changes? If you approve, we can get a new release out to Scott, et al.

**Pull request merged**
