### PR TITLE
Feature/wjiang/non blocking from front to back

### PR DESCRIPTION
**Pull request by weiyuan-jiang**
The front end should be able to respond to client faster by changing to non-blocking sending
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [x] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [x] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Review by tclune — APPROVED** [review]

**Review by tclune — COMMENTED** [review]
Does this PR include improvements to the profile output beyond what was shown Monday morning?   If so, could you post a sample output in the discussion part of this PR for us to see?

**Comment by weiyuan-jiang** [comment]
It is interesting that after adding this line https://github.com/GEOS-ESM/MAPL/blob/cacb094db6620c6b6a4fc243c69b27e67b3ecac3/profiler/FormattedTextColumn.F90#L113 

The run time error in debug mode disappeared. 

forrtl: error (63): output conversion error, unit -5, file Internal Formatted Write
Image              PC                Routine            Line        Source             
GEOSgcm.x          0000000010154C2B  Unknown               Unknown  Unknown
GEOSgcm.x          00000000101AFCC0  Unknown               Unknown  Unknown
GEOSgcm.x          00000000101ADA83  Unknown               Unknown  Unknown
libMAPL.profiler.  00002AAACF5F2784  mapl_formattedtex         117  FormattedTextColumn.F90

**Comment by weiyuan-jiang** [comment]
The ioserver profiler report looks like
Final profile
=============
Name                 Inclusive % Incl Exclusive % Excl Max Excl  Min Excl  Max PE Min PE
ioserver             98.097792 100.00 93.666391  95.48 93.923265 93.455536  0000   0071
--receive_data        0.306931   0.31  0.014745   0.02  0.029699  0.008789  0008   0024
----collection_1      0.008227   0.01  0.008227   0.01  0.022581  0.003207  0023   0063
----collection_2      0.051304   0.05  0.051304   0.05  0.112131  0.025835  0008   0033
----collection_7      0.000254   0.00  0.000254   0.00  0.000449  0.000166  0056   0034
----collection_8      0.001608   0.00  0.001608   0.00  0.003144  0.000928  0002   0027
----collection_15     0.006274   0.01  0.006274   0.01  0.012527  0.003193  0065   0007
----collection_16     0.000106   0.00  0.000106   0.00  0.000190  0.000063  0047   0003
----collection_17     0.014214   0.01  0.014214   0.01  0.030965  0.006703  0005   0024
----collection_18     0.065493   0.07  0.065493   0.07  0.133438  0.031862  0056   0021
----collection_19     0.014351   0.01  0.014351   0.01  0.029065  0.007099  0056   0031
----collection_20     0.000614   0.00  0.000614   0.00  0.001245  0.000323  0047   0043
----collection_21     0.002953   0.00  0.002953   0.00  0.005929  0.001471  0008   0034
----collection_22     0.033877   0.03  0.033877   0.03  0.075542  0.016586  0053   0033
----collection_23     0.000281   0.00  0.000281   0.00  0.000555  0.000146  0014   0022
--forward_data        4.098850   4.18  3.978390   4.06  4.144788  0.001092  0069   0000
----collection_1      0.007279   0.01  0.007279   0.01  0.012630  0.001359  0061   0062
----collection_2      0.044299   0.05  0.044299   0.05  0.054453  0.026798  0006   0026
----collection_7      0.001536   0.00  0.001536   0.00  0.001990  0.000780  0000   0026
----collection_8      0.004328   0.00  0.004328   0.00  0.005650  0.001903  0000   0035
----collection_15     0.001698   0.00  0.001698   0.00  0.001983  0.000991  0000   0021
----collection_16     0.000757   0.00  0.000757   0.00  0.000997  0.000343  0047   0027
----collection_17     0.002316   0.00  0.002316   0.00  0.002696  0.001872  0009   0059
----collection_18     0.004882   0.00  0.004882   0.00  0.005561  0.003827  0001   0071
----collection_19     0.002091   0.00  0.002091   0.00  0.002289  0.001725  0000   0035
----collection_20     0.000867   0.00  0.000867   0.00  0.001042  0.000557  0000   0026
----collection_21     0.001304   0.00  0.001304   0.00  0.001732  0.001010  0068   0059
----collection_22     0.002867   0.00  0.002867   0.00  0.003458  0.001653  0064   0009
----collection_23     0.000725   0.00  0.000725   0.00  0.001008  0.000428  0063   0015
--clean up            0.025620   0.03  0.025620   0.03  0.029982  0.013860  0049   0021

@tclune

**Comment by tclune** [comment]
OK - this is an improvement, but we're still only seeing a small fraction of the time at any granularity.   Any idea where the 93s of exclusive time in the main timer is being spent?    My guess is at some barrier.

**Review by tclune — APPROVED** [review]
Approving.    But further improvement should be implemented.

**Pull request merged**
