### PR TITLE
Fixes #800. Move to use Solar Cycle 24 for non-persist

### LINKED ISSUE #800: Should we update non-persist NRL Solar read
Before we did our current default of `PersistSolar` in using the NRL Solar file (which just persists the last value at the end of the table when you fall off it), I coded in a scheme where, if you fall off the table, you use a similar position in the last complete solar cycle using some "magic numbers" to know when Solar Cycle 23 was:
```fortran
         OUT_OF_TABLE_AND_CYCLE: if ( outOfTable .and. (.not. PersistSolar_) ) then

            ! Create an ESMF_Time at start of Cycle 23
            ! ----------------------------------------
            call ESMF_TimeSet( startCycle23, YY = 1996,  &
                                             MM = 8,     &
                                             DD = 1,     &
                                              H = 12,    &
                                              M = 00,    &
                                              S = 00,    &
                                             RC = STATUS )
            _VERIFY(STATUS)

            ! Create an ESMF_Time at start of Cycle 24
            ! ----------------------------------------
            call ESMF_TimeSet( startCycle24, YY = 2008,  &
                                             MM = 12,    &
                                             DD = 1,     &
                                              H = 12,    &
                                              M = 00,    &
                                              S = 00,    &
                                             RC = STATUS )
            _VERIFY(STATUS)
```
But, [we are now in Solar Cycle 25](https://www.nasa.gov/press-release/solar-cycle-25-is-here-nasa-noaa-scientists-explain-what-that-means/), so therefore we have a complete Solar Cycle 24. The question is: Should I update the non-persist code to use Solar Cycle 24 instead of 23?

So, I ask @dr0cloud and @wmputman to weigh in on this. Not a crucial question at all, but just something I thought of. 

I mean, it's not the default (and no one besides me or @dr0cloud probably know how to use it) so my guess is ***no one*** would care. It's just, well, I wrote this code and learned a lot about `ESMF_Time` from it, so it's sort of my baby. :smile:

### PR DESCRIPTION
**Pull request by mathomp4**
## Description

This moves the `PERSIST_SOLAR: .FALSE.` mode of NRL Solar to use Solar Cycle 24.

## Related Issue

Closes #800 

## Motivation and Context

We should use the last complete solar cycle? 

## How Has This Been Tested?

Ran GEOS, didn't crash.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [X] I have tested this change with a run of GEOSgcm (if non-trivial)
- [X] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [x] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Review by atrayano — APPROVED** [review]
Looks OK

**Review by dr0cloud — APPROVED** [review]
Looks OK

**Comment by mathomp4** [comment]
Note: The `non-zero-diff` label is because it is non-zero-diff if you were running the code before. But no one was, so it's really zero-diff. 

We'd probably want @dr0cloud to really pore over this code before it goes operational, but I think it is right. I know he helped me fix a lot of it the first time out!

I might also ping/bug @tclune at some point to help me make some of the debugging prints in this code:
https://github.com/GEOS-ESM/MAPL/blob/169c3f5a7e42c9b5f7a9bf242f0c1d4f2104da06/base/MAPL_sun_uc.F90#L2620-L2633
use pFlogger instead. It's a perfect use case for it!

**Review by tclune — DISMISSED** [review]

**Comment by mathomp4** [comment]
I'll ask @tclune to make sure the logging looks good to him. It seems to work:
```
0000: MAPL.SUN: DEBUG: Off the end of table, moving into last complete cycle
0000: MAPL.SUN: DEBUG:   Original Year-Mon-Day to Find: 2021-02-15
0000: MAPL.SUN: DEBUG:   Original Day of Year: 46
0000: MAPL.SUN: DEBUG:   New Year-Mon-Day to Find: 2010-02-16
0000: MAPL.SUN: DEBUG:   New Day of Year: 47
0000: MAPL.SUN: DEBUG:   First DOY to Find:      47
0000: MAPL.SUN: DEBUG:     file_index for date:  46798
0000: MAPL.SUN: DEBUG:     yearTable(date):     2010
0000: MAPL.SUN: DEBUG:     doyTable(date):       47
0000: MAPL.SUN: DEBUG:     tsi(date):           1360.960
0000: MAPL.SUN: DEBUG:     mgindex(date):       0.153700
0000: MAPL.SUN: DEBUG:     sbindex(date):        124.7500
0000: MAPL.SUN: DEBUG:   Second DOY to Find:     48
0000: MAPL.SUN: DEBUG:     file_index for date:  46799
0000: MAPL.SUN: DEBUG:     yearTable(date):     2010
0000: MAPL.SUN: DEBUG:     doyTable(date):       48
0000: MAPL.SUN: DEBUG:     tsi(date):           1360.963
0000: MAPL.SUN: DEBUG:     mgindex(date):       0.153800
0000: MAPL.SUN: DEBUG:     sbindex(date):        144.0400
0000: MAPL.SUN: DEBUG:   Interpolation Factor:  0.625000
```
so I don't think I broke anything 😄

**Comment by tclune** [comment]
If it runs, then the only way it can be wrong is to not produce the desired output (or to produce extra undesired output).  So I think this is fine.

**Review by tclune — APPROVED** [review]

**Comment by mathomp4** [comment]
> If it runs, then the only way it can be wrong is to not produce the desired output (or to produce extra undesired output). So I think this is fine.

The real question is how long until I spend a day getting the spacing/alignment just right and all the fun with that (do you align on the decimal? left justify?...)

**Comment by tclune** [comment]
If you preserved their edit descriptors, it should be the same as the original modulo the annotation at the beginning of the line.   I suppose there might be issues with spaces that need to be handled with the tilde character.

I would not spend much time unless you think the alignment before was crucial to understanding.   These are _debug_ statements after all.  And can be subsequently improved by someone that cares enough.

**Pull request merged**
