### PR TITLE
fix for debug. When passed in an empty string and attemped to step ou…

### PR DESCRIPTION
**Pull request by weiyuan-jiang**
…t of the boundary , the debug would crash

Avoid passing in an empty string which attempt to step out of bound for "debugging"

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [x] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [ ] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by weiyuan-jiang** [comment]
Address #315

**Comment by mathomp4** [comment]
Checking now!

**Comment by mathomp4** [comment]
@weiyuan-jiang Well, it fixes that issue, but I'm now getting another one (with Intel, haven't tested GCC):
```
(1090)(master) $ ctest -R 'MAPL_Profiler_tests$' --output-on-failure
Test project /discover/swdev/mathomp4/Models/GEOSgcm-SLES12-MAPL21-Intel/GEOSgcm/build-Debug
    Start 5: MAPL_Profiler_tests
1/1 Test #5: MAPL_Profiler_tests ..............***Failed  Error regular expression found in output. Regex=[Encountered 1 or more failures/errors during testing]  0.45 sec
srun: cluster configuration lacks support for cpu binding
................ BaseProfiler.F90         162 stop called on non-bottom timertimer_1
..................F..
Time:         0.004 seconds

Failure
 in:
test_DistributedMeter_suite.test_get_min[npes=2][npes=2]
  Location:
[test_DistributedMeter.pf:91]
AssertEqual failure:
      Expected: <1>
        Actual: <0>
    Difference: <-1> (PE=0)

 FAILURES!!!
Tests run: 36, Failures: 1, Errors: 0
, Disabled: 0
*** Encountered 1 or more failures/errors during testing. ***


0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.46 sec

The following tests FAILED:
	  5 - MAPL_Profiler_tests (Failed)
Errors while running CTest
```

**Comment by weiyuan-jiang** [comment]
It is interesting. My Intel debug tests passed. ( by "make tests" )  . I will take another look

**Comment by tclune** [comment]
Hmm.   That's a weird one to fail.

**Comment by weiyuan-jiang** [comment]
Both Intel (18.x)  and gfortran (9.1) debugs' tests pass for me. Are you on sles12? I did it on sles 11

**Comment by mathomp4** [comment]
> Both Intel (18.x) and gfortran (9.1) debugs' tests pass for me. Are you on sles12? I did it on sles 11

Oh. Yeah I am on SLES 12. I guess I didn't think about that. Still, surprised it would make a difference!

**Comment by tclune** [comment]
It's a bit scary given the nature of what the calculations are doing at that point.   Very simple min/max/sum ;  granted with OO wrapping them.

**Comment by tclune** [comment]
I think I see a bug that might be relevant: 

https://github.com/GEOS-ESM/MAPL/blob/8ee2d3b1d0f414422a69502386e02dbae3246655/MAPL_Profiler/DistributedMeter.F90#L176-L182

The middle branch seems wrong.

**Comment by tclune** [comment]
Line 178 should swap the order.  (Or I need more caffeine.)

**Comment by mathomp4** [comment]
That seems to help! It now passes for me with that fix. Weird that SLES12 exposes it but not SLES 11?!

**Comment by mathomp4** [comment]
@weiyuan-jiang I'll wait for you to do a final test as it's your code. Unless you'd like me to push that patch onto your branch now?

**Comment by weiyuan-jiang** [comment]
@mathomp4 Since it already passed the test, please push it and merge it. Thanks

**Pull request merged**
