### PR TITLE
Update ServerManager.F90

### PR DESCRIPTION
**Pull request by weiyuan-jiang**
typo and bug fix

### CODE REVIEW

**Comment by weiyuan-jiang** [comment]
This has been "fixed" in many branches of mine. I realize it may take some time to push my branches so I fixed it here.

**Comment by weiyuan-jiang** [comment]
The build is not supposed to fail. @mathomp4 , is this caused by Discover?

**Comment by mathomp4** [comment]
Ah. You are merging into `main` which does not have a CircleCI configuration to look for. The real question is: is there where you mean to merge into? If you meant `develop` then I think both @tclune and myself would say to _nuke this branch from orbit_ and restart fresh from `develop` make a new branch that you are sure is against `develop` and make a PR.

We are afraid sometimes of "changing base" on PRs...

**Comment by mathomp4** [comment]
I added a blocking label until that is resolved...

**Comment by weiyuan-jiang** [comment]
merge to wrong branch.  replaced with #534

**Pull request closed without merging**
