### PR TITLE
Move some sun orbital system parameters to PhysicalConstants

### PR DESCRIPTION
**Pull request by weiyuan-jiang**
Move some sun orbital system parameters to PhysicalConstants 
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Trivial change (affects only documentation or cleanup)

## Checklist:

- [ ] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [x] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by weiyuan-jiang** [comment]
@dr0cloud , Hi Peter, I have moved some orbital system properties to PhysicalConstants as part of an effort to cleanup our GEOSldas. Any comment to this PR? Thanks

**Comment by dr0cloud** [comment]
Weiyuan, Lets discuss these changes with Tom before proceeding. I have some concerns. Thanks, Peter.

**Review by tclune — CHANGES_REQUESTED** [review]
@weiyuan-jiang 

After discussion with @dr0cloud  we would prefer that this logic and the physical parameters be relocated instead to the module in `./base/MAPL_sun_uc.F90`.   This keeps everything close to where it is used.

@dr0cloud  also has some feedback about preserving some important comments when the literals are relocated.  He'll provide that separately.

We also may want to rename some of these to be more explicit. This is because things like "year length" have lots of different definitions due to real world perturbations.

Please take a first crack at relocating in the file above, and then add @dr0cloud as a reviewer.

**Comment by dr0cloud** [comment]
@tclune @weiyuan-jiang I'm actually wondering if it wouldn't be better for me to have a crack at this myself? Since I'm not great at git, I would probably start a new feature branch to do this and out you two as reviewers. P.

**Comment by tclune** [comment]
> @tclune @weiyuan-jiang I'm actually wondering if it wouldn't be better for me to have a crack at this myself? Since I'm not great at git, I would probably start a new feature branch to do this and out you two as reviewers. P.

No problem.

**Comment by tclune** [comment]
I will close this PR then.

**Comment by dr0cloud** [comment]
@tclune @weiyuan-jiang Sorry was in a meeting. Yes, I will work open this and submit a new PR, probably early next week. Thanks both. P.

**Pull request closed without merging**
