### PR TITLE
Fixes #1405. Marks connections with specific 'reserved' keyword as used

### LINKED ISSUE #1405: MAPL_Terminate all imports from a particular child fails
When we exercised the wave model, where we call MAPL_DoNotConnectAnyImport, we get the following error
        GENERIC: ERROR: SRC_NAME: <MAPL_AnyChildImport>  DST_NAME: <MAPL_AnyChildImport> is not satisfied
 DO_NOT_CONNECT ERRORS FOUND in OGCM

### PR DESCRIPTION
**Pull request by atrayano**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [x] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [x] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Review by tclune — APPROVED** [review]
Hmm. This line looks like the one you showed me yesterday.   Must be in a different place?

**Comment by atrayano** [comment]
Yes, it is very similar to what I showed you yesterday, but this line is a different procedure (this on is in APPEND, which puts the items in the container). Yesterday, I had similar logic inside varIsListed

**Comment by mathomp4** [comment]
Running tests with this now after merging in #1411

**Comment by mathomp4** [comment]
This looks to be zero-diff as well. Tested at C48, AMIP and Replay.

**Review by mathomp4 — APPROVED** [review]

**Pull request merged**
