### PR TITLE
Feature/wjiang/io 2nd layer

### PR DESCRIPTION
**Pull request by weiyuan-jiang**
Address issue #467 .   

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [ ] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [x] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by tclune** [comment]
We need to schedule another walkthrough.  Not sure there is still time today, and I am on vacation next week.   Maybe I'll take a break from vacation for this though.

**Comment by weiyuan-jiang** [comment]
@tclune I would like to merge this branch. Otherwise, it is hard to catch up with develop branch. I did a lot of tests and they seems fine

**Comment by tclune** [comment]
Is there any performance degradation with the default settings?  That is the primary concern.

**Comment by weiyuan-jiang** [comment]
No degradation. The default will be the same. Actually, my last PR that refactored WRITE_RESTART_BY_OSERVER  improve the performance

**Comment by weiyuan-jiang** [comment]
Does it need another approve? @mathomp4

**Review by mathomp4 — APPROVED** [review]
This seems good. I had forgotten about it as @tclune and I were trying to figure out a gfortran issue. He thinks he's solved it so I'll bring this in.

**Pull request merged**
