### PR TITLE
Fixes #433 - wildcard in specs

### LINKED ISSUE #433: Allow wildcard in short name in ACG for grid comp specs
In GOCART carbonaceous components, different sources for fields come from different entries in ExtData.   Since ExtData does not know the component name, the information must instead be encoded in the actual field.

```
foo*
```
Should be expanded as
```
foo<gc-name>
```
(cc'ing @gmao-esherman )

### PR DESCRIPTION
**Pull request by tclune**
Previous commit was not quite right.   Ultimately, I think the name
mangling should be pushed into the Fortran layer.

### CODE REVIEW

**Comment by mathomp4** [comment]
Well that's an odd error:
```
/__w/MAPL/MAPL/src/Components/@GEOSgcm_GridComp/GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/MOM_GEOS5PlugMod/MOM_GEOS5PlugMod.F90:2117:52:

 2117 |     doRecord = MAPL_RecordAlarmIsRinging(MAPL, MODE=MAPL_Write2Disk, RC=status)
      |                                                    1
Error: Keyword argument ‘mode’ at (1) is not in the procedure
```
I know Atanas fixed that. I'm going to try clicking the `Update branch` button

**Comment by mathomp4** [comment]
@tclune It looks like all the checks passed, so `Update branch` did it. I assume this script doesn't affect regular GEOS runs since I think we still use the Perl generator by default? (Aka I don't need to do a test run of GEOSgcm?)

**Comment by tclune** [comment]
Test run does not exercise this - only GOCART2G.   I decided your PR was a higher priority and got that in.   Waiting for CI to run again ...

**Comment by mathomp4** [comment]
> Test run does not exercise this - only GOCART2G. I decided your PR was a higher priority and got that in. Waiting for CI to run again ...

Okay. When this passes (as it will), I'll merge it in.

**Pull request merged**
