### PR TITLE
Fixes #1230. Update mapl_tree.py

### LINKED ISSUE #1230: mapl_tree.py doesn't work
@amdasilva asked on OTRS about `mapl_tree.py`. I thought I'd tried `mapl_tree.py` long ago (see #775), but I can't find my notes. And when I try to use it, it doesn't work. So, we need to make it work.

Note that I think we might have to remove/add to a lot of the assumptions made in this code. We have directory structures now that never existed in the past. So, we might want flags, etc. that will say "Yes, give me every directory." or "No, just the important ones and stop drilling down if you are at, say, ecbuild"

### PR DESCRIPTION
**Pull request by mathomp4**
## Description

An attempt to fix `mapl_tree.py`

## Related Issue

Closes #1230 

## Motivation and Context

Makes a code that used to work in CVS days, work again.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Trivial change (affects only documentation or cleanup)

## Checklist:

- [ ] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [x] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by mathomp4** [comment]
I might need to discuss this with @tclune and others. I'm not sure the `chname` variant of this should exist. It's...very fragile.

**Comment by tclune** [comment]
We may need 2 different spellings for the various GC directories to be future-safe.   One of the things we wanted to do with Git was to reconcile GC names and dir names.   E.g.,  `GEOS_AgcmGridComp`  should always have been in `GEOS_AgcmGridComp` directory, but due to a miscommunication, it is in `GEOSagcm_GridComp` directory

This is true of most gridcomps.   I think we have either corrected it in one place or introduced a new component "correctly".

**Comment by mathomp4** [comment]
Okay. What I have here seems to work in the `dirname` case. It is still quite broken for the `chname` case. As such, for now I've made it pretty much default to use `dirname` without options. At this point, the only required argument is `--rootdir`. It also defaults to `ascii`. 

Now, I think there are still issues with `--color` and `--link`. It's hard to test since FreeMi nd is nigh-dead. The `mindmap` output does work in, say, XMind, but I don't think XMind cares about links and colors when it imports a FreeMind file.

Still, you do get something:
GEOSgcm

**Comment by mathomp4** [comment]
I just did a sweep and cleaned up some comments. EditorConfig did a bit of whitespace cleaning as well. This does seem to work for now, so I think we are safe to pull into MAPL. Always better to have working code that might not be perfect than code we know doesn't work!

Thanks to @amdasilva for extra additions and cleanup

**Comment by amdasilva** [comment]
Matt,

    I just committed to the same branch another patch to show the hierarchy of repositories (option –repo):

***@***.***


I was surprised how most repositories hang right off the main fixture. The only place with hierarchy is off GEOSgcm, most are terminal repositories.

      Arlindo


From: Matthew Thompson ***@***.***>
Reply-To: GEOS-ESM/MAPL ***@***.***>
Date: Tuesday, December 14, 2021 at 3:22 PM
To: GEOS-ESM/MAPL ***@***.***>
Cc: "DA SILVA, ARLINDO M (GSFC-6101)" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [GEOS-ESM/MAPL] Fixes #1230. Update mapl_tree.py (PR #1231)


I just did a sweep and cleaned up some comments. EditorConfig did a bit of whitespace cleaning as well. This does seem to work for now, so I think we are safe to pull into MAPL. Always better to have working code that might not be perfect than code we know doesn't work!

Thanks to @amdasilva<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Famdasilva&data=04%7C01%7Carlindo.m.dasilva%40nasa.gov%7C232476ffecf148a2a9b608d9bf3f7986%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637751101609471945%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HEFShA3%2FDmCtEXShB9tm7noHxLmcu7mO2eSbXztyFb8%3D&reserved=0> for extra additions and cleanup

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGEOS-ESM%2FMAPL%2Fpull%2F1231%23issuecomment-993950070&data=04%7C01%7Carlindo.m.dasilva%40nasa.gov%7C232476ffecf148a2a9b608d9bf3f7986%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637751101609471945%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JPvg2asLdkG%2F%2B9Ux8UEmuQcTLMb4QwsLiw0mc5aCMpk%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAH5LTY6DUD3BBKBBUNY6SXTUQ6RQXANCNFSM5J7J4ZOA&data=04%7C01%7Carlindo.m.dasilva%40nasa.gov%7C232476ffecf148a2a9b608d9bf3f7986%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637751101609628595%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=lXwKvLAjVZvXlkM16WPfs8VCVHWFQR4ioxfm7YivBtk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Carlindo.m.dasilva%40nasa.gov%7C232476ffecf148a2a9b608d9bf3f7986%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637751101609628595%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QlQGnLtj%2B%2FQwRFlrf7PWoIbmDA35mT7hsrn7aVXCuGQ%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Carlindo.m.dasilva%40nasa.gov%7C232476ffecf148a2a9b608d9bf3f7986%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637751101609628595%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6E7vCU7eH3k64VcSlHLmKC3MLHwmLWBEJMolF1pWi5Y%3D&reserved=0>.

**Pull request merged**
