### PR TITLE
Fearure/wjiang/remove gfortran workaround

### LINKED ISSUE #493: what if  __GFORTRAN__  is defined
https://github.com/GEOS-ESM/MAPL/blob/9585c00fd79b388006585067fb07c5d67b311b14/base/MAPL_LocStreamMod.F90#L236-L258

What if __GFORTRAN__  is defined  and both tilelons and tilelats are present?  It ends up allocate a pointer twice. There are a handful of places like this in the subroutine.

### PR DESCRIPTION
**Pull request by weiyuan-jiang**
This workaround which introduces memory leak is not necessary with newer gfortran compiler (9.3 and above). close #493 
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [ ] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [x] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by mathomp4** [comment]
I'm not sure this is trivial. Let me make sure things work with this gone!

**Comment by mathomp4** [comment]
Putting a blocker on this. Model didn't run for me.

**Comment by mathomp4** [comment]
From a debug run:
```
 Bootstrapping aiau_import_rst
 Character Resource Parameter: FILTER_TYPE:NULL
 Real*4 Resource Parameter: OCEAN_DT:900.000000

Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x2aaac8bc8fdf in ???
#1  0x2aaac8bc8f67 in ???
#2  0x2aaac8bca339 in ???
#3  0x2aaac8c080f3 in ???
#4  0x2aaac8c0d645 in ???
#5  0x2aaac8c0e392 in ???
#6  0x6910a32 in initialize
        at /discover/swdev/mathomp4/Models/GEOSgcm-MAPLNoGCCWorkAround/GEOSgcm/src/Components/@GEOSgcm_GridComp/GEOSogcm_GridComp/GEOS_OgcmGridComp.F90:1384
```

And oh dear. From Ogcm GC:
```fortran
#ifdef __GFORTRAN__
    deallocate(gnames, gridim, gridjm)
#endif
```
And I see something similar in Route GC:
```fortran
#ifdef __GFORTRAN__
    deallocate(tile_area_src)
#endif
```

Let me try removing those and rebuilding...

**Comment by mathomp4** [comment]
Good news: with the removal of the `__GFORTRAN__` bit in OGCM GC, the model runs. Yay! 

Odd news: the answer is non-zero-diff. Not big non-zero-diff, but still.

@atrayano @tclune Would you expect that? Surprising to me (though maybe it points to a memory issue somewhere).

**Review by tclune — DISMISSED** [review]

**Comment by tclune** [comment]
No.  This change causing any diffs in the result is not good and suggests a deeper (probably unrelated) issue.  Sigh.

**Comment by mathomp4** [comment]
Note: I've created a PR on GCM GC here: https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/412

This PR will be contingent on that code change making it into a GEOSgcm release.

**Pull request merged**
