### PR TITLE
Update CircleCI to use xlarge

### PR DESCRIPTION
**Pull request by mathomp4**
This updates the CI to use the newly re-enabled xlarge resource class on CircleCI.

### CODE REVIEW

**Comment by mathomp4** [comment]
Let's get some timings.

With `medium` resource:

- build-and-test-MAPL: 11m 40s
- build-GEOSgcm: 45m 41s
- make-FV3-experiment: 51s
- run-FV3-standalone:  2m 6s

With `xlarge` resource:

- build-and-test-MAPL: 
- build-GEOSgcm: 
- make-FV3-experiment: 
- run-FV3-standalone:

**Review by tclune — APPROVED** [review]

**Review by tclune — APPROVED** [review]

**Comment by tclune** [comment]
BTW, this looks like it goes _from_ XLARGE _to_ MEDIUM.  Not the other way around.

**Comment by mathomp4** [comment]
> BTW, this looks like it goes _from_ XLARGE _to_ MEDIUM. Not the other way around.

Yeah. I know. The `#MEDIUM#` looks impressive, but I like the "labeled" comment so if we need to revert, that makes it easy.

**Comment by mathomp4** [comment]
@tclune  So, it looks like we might want to focus our attention on the GNU build's tall poles. I think `MAPL_HistoryGridComp.F90` is still the big gun in the GNU Debug build. All that extra parallelism and the MAPL build only goes down by 1 minute (compared to GEOSgcm being 3x faster).

**Pull request merged**
