### PR TITLE
Feature/atrayano/wildcard

### PR DESCRIPTION
**Pull request by atrayano**
Adds support for wildcard expansion in History (as requested by Harvard collaborators)
## Description

This is a beta version of a new feature (requested by Harvard) to enable wildcard expansion in History
## Motivation and Context

Simplifies syntax in History by allowing regex expressions
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [x] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [x] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by mathomp4** [comment]
Give me a bit to test this on macOS. Just to make sure macOS can see regex.h, etc.

**Comment by mathomp4** [comment]
Welp, it built on macOS. And then my laptop lost all internet and VPN, but I think it's good!

**Comment by atrayano** [comment]
Glad to hear it builds on MacOS. My internet was somewhat flaky too (but did not loose VPN)

**Comment by mathomp4** [comment]
I have tested this PR (along with all the others in progress) at C48 and the run was zero-diff as well as all MAPL tests successful.

**Pull request merged**
