### PR TITLE
add message for rc code

### PR DESCRIPTION
**Pull request by weiyuan-jiang**
Get error message for VERIFY and RETURN #394 
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [ ] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [ ] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by mathomp4** [comment]
Looks like there's a build issue:
```
/baselibs/6.0.13/x86_64-unknown-linux-gnu/gfortran_9.3.0-openmpi_4.0.3/Linux/GFTL-1.2/include/templates/error_codes.inc:11:35:

   11 |       integer, parameter :: SUCCESS = 0
      |                                   1
Error: Symbol ‘success’ at (1) conflicts with symbol from module ‘mapl_errorhandlingmod’, use-associated at (2)
make[2]: *** [base/CMakeFiles/MAPL.base.dir/FileMetadataUtilitiesVector.F90.o] Error 1
```

**Comment by weiyuan-jiang** [comment]
The error code name conflict is resolved

**Comment by atrayano** [comment]
@weiyuan-jiang Please correct the error message (see my previous comment)

**Comment by weiyuan-jiang** [comment]
The error message is corrected. @atrayano

**Pull request merged**
