### PR TITLE
change logical internal storage to integer in pFIO_Utilities

### PR DESCRIPTION
**Pull request by weiyuan-jiang**
Change the internal representation of logical type  in pFIO_Utilities
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [x] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [x] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Review by bena-nasa — APPROVED** [review]

**Comment by mathomp4** [comment]
Hmm. NAG seems to have *more* issues that look similar:
```console
❯ make install
[  3%] Built target MAPL_cfio_r4
[  6%] Built target MAPL_cfio_r8
[ 13%] Built target MAPL.shared
[ 13%] Building Fortran object pfio/CMakeFiles/MAPL.pfio.dir/MpiMutex.F90.o
NAG Fortran Compiler Release 7.0(Yurakucho) Build 7036
Warning: /Users/mathomp4/Models/MAPL-NAG-Fix/MAPL/pfio/MpiMutex.F90, line 175: INT64 explicitly imported into PFIO_MPIMUTEXMOD but not used
Error: /Users/mathomp4/Models/MAPL-NAG-Fix/MAPL/pfio/MpiMutex.F90, line 67: Argument ONE_LOGICAL to C_SIZEOF function in intrinsic module ISO_C_BINDING is of non-interoperable type LOGICAL
Extension: /Users/mathomp4/Models/MAPL-NAG-Fix/MAPL/pfio/MpiMutex.F90, line 71: C_F_POINTER array argument FPTR has non-interoperable type LOGICAL
Extension: /Users/mathomp4/Models/MAPL-NAG-Fix/MAPL/pfio/MpiMutex.F90, line 169: C_F_POINTER array argument FPTR has non-interoperable type LOGICAL
[NAG Fortran Compiler error termination, 1 error, 3 warnings]
make[2]: *** [pfio/CMakeFiles/MAPL.pfio.dir/build.make:563: pfio/CMakeFiles/MAPL.pfio.dir/MpiMutex.F90.o] Error 2
make[1]: *** [CMakeFiles/Makefile2:1736: pfio/CMakeFiles/MAPL.pfio.dir/all] Error 2
make: *** [Makefile:182: all] Error 2
```

**Comment by mathomp4** [comment]
Adding blocking label for now.

**Comment by weiyuan-jiang** [comment]
Hmm, I may borrow MpiLock.F90 from pFlogger.

**Comment by weiyuan-jiang** [comment]
Would you try NAG again? @mathomp4

**Comment by tclune** [comment]
I actually have a branch where I got past the NAG issues and even eliminated a number of warnings.  (see other ticket).   Unfortunately, I got bogged down on the OpenMP + CMake issue.

**Comment by tclune** [comment]
@weiyuan-jiang  It is the same MpiLock.F90 in both projects.   We copied it from pFlogger into pFIO.    We must have subsequently fixed issues in one project and failed to propagate them to the other.

**Comment by weiyuan-jiang** [comment]
There is slight difference. I am probably the one who introduced this incompatibility.

**Comment by mathomp4** [comment]
> I actually have a branch where I got past the NAG issues and even eliminated a number of warnings. (see other ticket). Unfortunately, I got bogged down on the OpenMP + CMake issue.

After taking the fix from @weiyuan-jiang, I'm guessing this:
```
Error: /Users/mathomp4/Models/MAPL-NAG-Fix/MAPL/base/MAPL_LlcGridFactory.F90, line 264: KIND value (8) does not specify a valid representation method
Error: /Users/mathomp4/Models/MAPL-NAG-Fix/MAPL/base/MAPL_LlcGridFactory.F90, line 265: KIND value (8) does not specify a valid representation method
```
is one of the things you found. Maybe we can hold off until the @tclune branch is ready.

**Comment by weiyuan-jiang** [comment]
This error is new to me. We may wait for Tom's fix.

**Comment by tclune** [comment]
I'll go ahead and push my branch up to the repo,  but you should be careful merging it in.    I was in the middle of further changes and don't recall just where I left things.   And because of a big deadline, cannot touch this again until next week.

**Comment by tclune** [comment]
See `feature/tclune/#653-nag-portability`

**Comment by weiyuan-jiang** [comment]
Two  ways to get the logical size:
1)        call MPI_Type_extent(MPI_LOGICAL, sizeof_logical, ierror)
           sz = lock%npes * sizeof_logical

2)       logical(kind=c_bool) :: one_logical
           sizeof_logical = c_sizeof(one_logical)
           sz = lock%npes * sizeof_logical  

Which is better? @tclune

**Comment by mathomp4** [comment]
> See `feature/tclune/#653-nag-portability`

Yeah, okay. That is definitely happier with NAG. And I think I'm hitting the same [CMake/NAG/OpenMP bug](https://gitlab.kitware.com/cmake/cmake/-/issues/21280) @tclune saw:
```
[ 92%] Linking Fortran executable ../bin/pfio_collective_demo.x
NAG Fortran Compiler Release 7.0(Yurakucho) Build 7036
duplicate symbol '___NAGf90_laDeAlloc' in:
    /Users/mathomp4/installed/Core/nag/7.0_7036/lib/NAG_Fortran/safefit.o
duplicate symbol '___NAGf90_aDeAlloc' in:
    /Users/mathomp4/installed/Core/nag/7.0_7036/lib/NAG_Fortran/safefit.o
duplicate symbol '___NAGf90_oDeAlloc' in:
    /Users/mathomp4/installed/Core/nag/7.0_7036/lib/NAG_Fortran/safefit.o
...
```

**Comment by tclune** [comment]
It really depends on context.  Are you getting the size so that you can compute the buffer size for an MPI call?   Or are you trying to ensure interoperability with C.    Note that in theory the answers could even differ between the 2 approaches.   But that's unlikely on any existing compilers.

All other things equal, I guess a prefer a Fortran solution over an MPI solution.   But it really is marginal.

**Comment by weiyuan-jiang** [comment]
I have merged Tom's branch. Would you try again? @mathomp4

**Review by tclune — DISMISSED** [review]

**Comment by mathomp4** [comment]
Thanks to @tclune, I think I have this branch at a point where @weiyuan-jiang can do some tests on discover. So, if you can @weiyuan-jiang:
```
mepo clone -b feature/wjiang/fix_logical_type git@github.com:GEOS-ESM/MAPL.git
cd MAPL
cp /gpfsm/dhome/mathomp4/GitG5Modules/SLES12/6.0.27/g5_modules.nag7 ESMA_env/g5_modules
```
That should get you this branch and the NAG 7 module file. After that, you'll need to run CMake with an extra flag:
```
mkdir build-Debug
cd build-Debug
cmake .. -DBUILD_WITH_FLAP=NO .....
```
because we don't have FLAP for NAG.  Then:
```
make -j4 install
make -j4 tests
```
should fail with the first test and:
```
ctest -R MAPL.pfio.tests --output-on-failure
```
will provide more info

**Comment by weiyuan-jiang** [comment]
Indeed there is a bug in MultiCommServer.F90. Also I have fixed the complaining from LocalMemReference.F90. Now the successful tests are using mpiexec and the failed ones are using mpirun. The error  message: error while loading shared libraries: libfabric.so.1: cannot open shared object file: No such file or directory

**Comment by mathomp4** [comment]
We might need the NAG knowledge of @tclune now. All the tests pass except for `MAPL.base.tests` which just segfaults:
```
[gs6101-parcel:88126] *** Process received signal ***
[gs6101-parcel:88126] Signal: Segmentation fault: 11 (11)
[gs6101-parcel:88126] Signal code: Address not mapped (1)
[gs6101-parcel:88126] Failing at address: 0x0
[gs6101-parcel:88126] [ 0] 0   libsystem_platform.dylib            0x00007fff6fdc65fd _sigtramp + 29
[gs6101-parcel:88126] [ 1] 0   libf70rts.dylib                     0x00000001113f478b J_runtime_error_prefix + 8267
[gs6101-parcel:88126] [ 2] 0   MAPL.base.tests                     0x000000010bd4f2b4 wraptest_latlon_gridfactory_MP_makecustomtest + 1268
[gs6101-parcel:88126] [ 3] 0   MAPL.base.tests                     0x000000010bd5ab4b test_latlon_gridfactory_suite_ + 13115
[gs6101-parcel:88126] [ 4] 0   MAPL.base.tests                     0x000000010bdafe20 main_IP_load_tests + 17328
[gs6101-parcel:88126] [ 5] 0   MAPL.base.tests                     0x000000010bf89337 funit_MP_generic_run + 9127
[gs6101-parcel:88126] [ 6] 0   MAPL.base.tests                     0x000000010bdb4a18 pfunit_MP_run + 904
[gs6101-parcel:88126] [ 7] 0   MAPL.base.tests                     0x000000010bdb603a funit_main_ + 42
[gs6101-parcel:88126] [ 8] 0   MAPL.base.tests                     0x000000010bdaba4f main_ + 159
[gs6101-parcel:88126] [ 9] 0   MAPL.base.tests                     0x000000010bdab99a main + 42
[gs6101-parcel:88126] [10] 0   libdyld.dylib                       0x00007fff6fbcdcc9 start + 1
[gs6101-parcel:88126] [11] 0   ???                                 0x0000000000000001 0x0 + 1
[gs6101-parcel:88126] *** End of error message ***
```
Maybe there are NAG options to use? I tried using `-g90` to use `dbx90` but that led to 30+ GB `.g90` files.

**Comment by mathomp4** [comment]
Maybe @tclune knows how to read NAG tracebacks?

**Comment by tclune** [comment]
Please manually run the tests with the -d flag.   This will let me know which test is failing so that I can look at it in more detail.
```
$ mpirun -np 8   ./base/tests/mapl.base.tests
```
or something very similar to that.

**Comment by mathomp4** [comment]
Well, this is annoying. It seems to just crash before the `-d` flag can do anything?
```console
❯ mpirun -np 8 /Users/mathomp4/Models/MAPL-NAG-WeiyuanFix/MAPL/build-Debug/base/tests/MAPL.base.tests -d
[gs6101-parcel:72843] *** Process received signal ***
[gs6101-parcel:72843] Signal: Segmentation fault: 11 (11)
[gs6101-parcel:72843] Signal code: Address not mapped (1)
[gs6101-parcel:72843] Failing at address: 0xfffffffffffffffc
[gs6101-parcel:72843] [ 0] 0   libsystem_platform.dylib            0x00007fff700055fd _sigtramp + 29
[gs6101-parcel:72843] [ 1] 0   ???                                 0x0000000000000001 0x0 + 1
[gs6101-parcel:72843] [ 2] [gs6101-parcel:72846] *** Process received signal ***
```

**Comment by mathomp4** [comment]
Did some tests with @tclune and we found that it seems to be the LatLon tests that trigger this. If you don't build them, the other tests pass!

**Comment by mathomp4** [comment]
New issue. Intel does not pass the tests:
```
1: Test command: /usr/local/intel/2020/compilers_and_libraries_2020.4.304/linux/mpi/intel64/bin/mpirun "-np" "8" "/discover/swdev/mathomp4/Models/MAPL-Intel-WeiyuanBranch/MAPL/build-Debug/pfio/tests/MAPL.pfio.tests"
1: Test timeout computed to be: 1500
1: srun: cluster configuration lacks support for cpu binding
1: .......forrtl: severe (408): fort: (7): Attempt to use pointer INT32PTR when it is not associated with a target
1:
1: Image              PC                Routine            Line        Source
1: MAPL.pfio.tests    0000000000A799EF  Unknown               Unknown  Unknown
1: libMAPL.pfio.so    00002AAAAB64331E  pfio_localmemrefe         114  LocalMemReference.F90
1: MAPL.pfio.tests    00000000004DB08A  test_localmemrefe         106  Test_LocalMemReference.pf
1: MAPL.pfio.tests    00000000006AF706  pf_testmethod_mp_          89  TestMethod.F90
1: MAPL.pfio.tests    000000000068A25E  pf_testcase_mp_ru         136  TestCase.F90
1: MAPL.pfio.tests    000000000068A596  pf_testcase_mp_ru         146  TestCase.F90
1: MAPL.pfio.tests    00000000006B5C70  pf_testresult_mp_         237  TestResult.F90
1: MAPL.pfio.tests    0000000000689E19  pf_testcaserun_mp         121  TestCase.F90
1: MAPL.pfio.tests    00000000006897BB  pf_testcase_mp_ru         108  TestCase.F90
1: MAPL.pfio.tests    00000000006BAF44  pf_testsuite_mp_r         108  TestSuite.F90
1: MAPL.pfio.tests    00000000006BAF44  pf_testsuite_mp_r         108  TestSuite.F90
1: MAPL.pfio.tests    000000000099DDBB  pf_testrunner_mp_         139  TestRunner.F90
1: MAPL.pfio.tests    000000000099CF6F  pf_testrunner_mp_         117  TestRunner.F90
1: MAPL.pfio.tests    000000000097CD92  funit_mp_generic_         118  FUnit.F90
1: MAPL.pfio.tests    00000000006146A7  pfunit_mp_run_            106  pFUnit.F90
1: MAPL.pfio.tests    000000000060EB38  funit_main_                16  pfunit_main.F90
1: MAPL.pfio.tests    000000000060A2D0  MAIN__                     50  driver.F90
1: MAPL.pfio.tests    00000000004BB092  Unknown               Unknown  Unknown
1: libc-2.22.so       00002AAAB342A725  __libc_start_main     Unknown  Unknown
1: MAPL.pfio.tests    00000000004BAFA9  Unknown               Unknown  Unknown
```

**Comment by mathomp4** [comment]
Testing after @weiyuan-jiang fix:

- [ ] Intel Debug
- [ ] Intel Release
- [ ] GCC Debug
- [ ] GCC Release
- [ ] NAG Debug
- [ ] NAG Release
- [ ] GEOSgcm with this branch - Release
- [ ] GEOSgcm with this branch - Debug

**Comment by mathomp4** [comment]
Oh. Wait. I think I have a thought. You are doing:
```fortran
         if (.not. c_associated(reference%base_address)) then
            _RETURN(_SUCCESS)
         endif
```
but the test has:
```fortran
      @assertFalse(associated(iptr))
```
So, perhaps you should `_RETURN(_FAILURE)`?

**Comment by weiyuan-jiang** [comment]
The  call
call c_f_pointer(c_null_ptr, j_ptr)
would  compile in Intel but not in Nag.  It would crash though. In the LocalMemReference.F90. Nag can compile the line 
call c_f_pointer(a%base_address, iptr,a%shape)
I guess at that point Nag does not know a%base_address is c_null_ptr.  so Nag build and pass.  Intel should build and crash ( it fails instead of crashes, cofused ....)

**Comment by weiyuan-jiang** [comment]
Nag and Intel produce different results for this call . Nag get F, intel get T. Obviously, Nag wins.
call c_f_pointer(c_null_ptr, j_ptr, [0])
print*, associated(j_ptr)

**Comment by weiyuan-jiang** [comment]
I removed those asserts

**Comment by mathomp4** [comment]
Okay. I passed with Intel! Now for comprehensive testing:

- [ ] Intel Debug
- [ ] Intel Release
- [ ] GNU Debug
- [ ] GNU Release
- [ ] NAG Debug
- [ ] NAG Release
- [ ] GEOSgcm

**Comment by mathomp4** [comment]
I believe this is now good to go.

**Comment by mathomp4** [comment]
I'm re-requesting review from @tclune and @bena-nasa on this. It seems safe to take. 

Not sure what's going on with the GitHub Actions build. Seems...slow. But it's working.

**Comment by mathomp4** [comment]
Wooo! It all passed! 😄

**Review by tclune — APPROVED** [review]

**Pull request merged**
