### PR TITLE
Eliminate (almost) all Intel warnings

### PR DESCRIPTION
**Pull request by tclune**
Eliminated all warnings when building MAPL with Intel 2021.1.1,
except:

   - fpp warning from gFTL about redefining some macros
     (will be fixed soon)

   - remark about
       "All symbols from this module are already visible  ... "
     This is a workaround we have for a long standing issue with
     Intel.  We think it is a compiler defect, but it might be
     something funny we are doing with modules.

## Description

Lots of little changes to eliminate unused variables.  Also a few nonstandard constructs in C code.

## Types of changes

- [X] Cleanup
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

I have not tested ...

### CODE REVIEW

**Review by atrayano — DISMISSED** [review]
The changes look OK to me. Most of them are fairly obvious. I have a small concern about changing the interface of MAPL_GetHorzIJIndex. I understand some of the arguments were not used (neither set or read) but I am not sure how is this code used outside of GEOS. @bena, any thoughts? Or simply we were thinking of using the edge vars but decided not to.

**Comment by mathomp4** [comment]
It looks like gfortran threw a rod with the unit tests:
```
    Start  1: MAPL.pfio.tests
1/5 Test  #1: MAPL.pfio.tests ..................***Failed    1.37 sec
.....
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7f414d4d7bd0 in ???
#1  0x7f414d4d6e25 in ???
#2  0x7f414cf5d20f in ???
#3  0x7f414cfb4870 in ???
#4  0x7f414fd6cffe in __pfio_unlimitedentitymod_MOD_set
	at /root/project/MAPL/pfio/UnlimitedEntity.F90:235
#5  0x7f414fd6096d in deserialize
	at /root/project/MAPL/pfio/UnlimitedEntity.F90:649
#6  0x7f414fd63aa6 in __pfio_unlimitedentitymod_MOD_unlimitedentity_deserialize
	at /root/project/MAPL/pfio/UnlimitedEntity.F90:591
#7  0x40b85e in __test_unlimitedentity_MOD_test_serialize
	at /root/project/MAPL/pfio/tests/Test_UnlimitedEntity.pf:160
#8  0x5c6764 in __pf_testmethod_MOD_runmethod
	at /baselibs/v6.0.27/ESMA-Baselibs/pFUnit/src/funit/core/TestMethod.F90:89
#9  0x5c5117 in __pf_testcase_MOD_runbare
	at /baselibs/v6.0.27/ESMA-Baselibs/pFUnit/src/funit/core/TestCase.F90:136
#10  0x5c50cc in __pf_testcase_MOD_runbare_surrogate
	at /baselibs/v6.0.27/ESMA-Baselibs/pFUnit/src/funit/core/TestCase.F90:146
#11  0x7ae904 in __pf_testresult_MOD_run
	at /baselibs/v6.0.27/ESMA-Baselibs/pFUnit/src/funit/core/TestResult.F90:237
#12  0x5c52a1 in inner_run
	at /baselibs/v6.0.27/ESMA-Baselibs/pFUnit/src/funit/core/TestCase.F90:121
#13  0x5c5364 in __pf_testcase_MOD_run
	at /baselibs/v6.0.27/ESMA-Baselibs/pFUnit/src/funit/core/TestCase.F90:108
#14  0x5cb032 in __pf_testsuite_MOD_run
	at /baselibs/v6.0.27/ESMA-Baselibs/pFUnit/src/funit/core/TestSuite.F90:108
#15  0x5cb032 in __pf_testsuite_MOD_run
	at /baselibs/v6.0.27/ESMA-Baselibs/pFUnit/src/funit/core/TestSuite.F90:108
#16  0x7b1bad in __pf_testrunner_MOD_runwithresult
	at /baselibs/v6.0.27/ESMA-Baselibs/pFUnit/src/funit/core/TestRunner.F90:139
#17  0x7b54b9 in __pf_testrunner_MOD_run
	at /baselibs/v6.0.27/ESMA-Baselibs/pFUnit/src/funit/core/TestRunner.F90:117
#18  0x7778bd in __funit_MOD_generic_run
	at /baselibs/v6.0.27/ESMA-Baselibs/pFUnit/src/funit/FUnit.F90:118
#19  0x5ae003 in __pfunit_MOD_run
	at /baselibs/v6.0.27/ESMA-Baselibs/pFUnit/src/pfunit/pFUnit.F90:106
#20  0x5ac83a in funit_main_
	at /baselibs/v6.0.27/ESMA-Baselibs/pFUnit/src/pfunit/pfunit_main.F90:16
#21  0x5ac3d5 in MAIN__
	at /baselibs/v6.0.27/g*******_10.2.0-openmpi_4.0.5/Linux/PFUNIT-4.1/include/driver.F90:50
#22  0x5ac42d in main
	at /baselibs/v6.0.27/g*******_10.2.0-openmpi_4.0.5/Linux/PFUNIT-4.1/include/driver.F90:20
```

I think @atrayano wanted @bena-nasa 😄

**Comment by tclune** [comment]
Hmm.  Causes nonzero diffs.  Sigh.

**Comment by tclune** [comment]
I was mistaken.  The diffs were due to an upgrade in the BCs.   This PR is ready for merge.

**Comment by atrayano** [comment]
This is excellent news!

**Review by atrayano — DISMISSED** [review]
Looks reasonable

**Review by mathomp4 — COMMENTED** [review]
This does seem zero-diff in my tests (well, as zero-diff as `develop` is). Approving!

**Review by mathomp4 — APPROVED** [review]

**Pull request merged**
