### PR TITLE
add option BUILD_SHARED_MAPL to build shared or static library

### PR DESCRIPTION
**Pull request by weiyuan-jiang**
Add option to build static library
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [ ] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [x] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by weiyuan-jiang** [comment]
This PR is alternative of #876

**Comment by rmontuoro** [comment]
Looks good and works with the UFS weather model.

One possible tiny improvement could be adding a message stating whether MAPL is being built as static or shared. For example:

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index a6be3a0..1bbeacb 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -53,6 +53,7 @@ if (BUILD_SHARED_MAPL)
 else ()
   set (MAPL_TYPE STATIC)
 endif()
+message (STATUS "Building MAPL as ${MAPL_TYPE}")
 
 option(BUILD_WITH_FLAP "Use FLAP for command line processing" ON)
 if (BUILD_WITH_FLAP)
```

**Comment by weiyuan-jiang** [comment]
The message is added.

**Comment by mathomp4** [comment]
@weiyuan-jiang Could you possible "refactor" this to make `MAPL_TYPE` be something more like `MAPL_LIBRARY_TYPE`? That way the variable is a bit more "self-documenting".

**Comment by weiyuan-jiang** [comment]
@mathomp4 . That is a better name. Changed

**Comment by tclune** [comment]
Isn't the canonical term "MPI Flavor"?   Or is that just a thing we bandy about internally?

**Comment by weiyuan-jiang** [comment]
The ufs will not crash at the end with static MAPL libraries

**Comment by mathomp4** [comment]
I'll do a test build with this on macOS tomorrow to make sure it all works. If so, merge time!

**Comment by mathomp4** [comment]
Tested on Discover and zero-diff and I can run on macOS with this PR. Good enough.

**Review by mathomp4 — APPROVED** [review]

**Pull request merged**
