### PR TITLE
Fixes #563. Fixes for Leap Year Extrapolation

### LINKED ISSUE #563: Crash with ExtData when extrapolating on a leap day
In looking at OTRS Ticket 0111488, I decided to regrid MERRA2 to 2020-02-27 21z and then run a C24 run. In doing so, I managed to hit what looks to be an ExtData crash in MAPL `main`/`develop`/2.3.0 (all the same at present).  After turning on DEBUG loggers for console and CAP root_level, and then fixing #562 locally and I saw:
```
 AGCM Date: 2020/02/29  Time: 00:00:00  Throughput(days/day)[Avg Tot Run]: 1525.7  609.2 2259.8  TimeRemaining(Est) 000:01:46   24.6% :  10.6% Mem Comm:Used
        EXTDATA: DEBUG: ExtData Rune_(): Start
        EXTDATA: DEBUG: ExtData Run_(): READ_LOOP: Start
        EXTDATA: DEBUG: ExtData Run_(): READ_LOOP: variable 1 of 57: biomass
        EXTDATA: DEBUG:    ==> file: ExtData/PIESA/sfc/QFED/v2.4r6/Y%y4/M%m2/qfed2.emis_bc.005.%y4%m2%d2.nc4
        EXTDATA: DEBUG:    ==> cyclic: n
        EXTDATA: DEBUG:    ==> isConst:: F
        EXTDATA: DEBUG:    ExtData Run_: DO_UPDATE: Start. doUpdate_ is true.
        EXTDATA: DEBUG:       ExtData Run_: NOT_SINGLE: Start. Update bracketing times?
        EXTDATA: DEBUG:          ==> updateR: T
        EXTDATA: DEBUG:          ==> updateL: F
        EXTDATA: DEBUG:          ==> swap: T
        EXTDATA: DEBUG:             DO_SWAP: Swapping prev and next
        EXTDATA: DEBUG:          UPDATE_R: updating right bracket
        EXTDATA: INFO: Updating R bracket for BC_BIOMASS
        EXTDATA: DEBUG:             UpdateBracketTime: Scanning template ExtData/PIESA/sfc/QFED/v2.4r6/Y%y4/M%m2/qfed2.emis_bc.005.%y4%m2%d2.nc4 for side R
        EXTDATA: DEBUG:        UpdateBracketTime: Target time   : 2020-02-29 12:00:00
        EXTDATA: DEBUG:        UpdateBracketTime: Reference time: 1985-01-01 00:00:00
        EXTDATA: DEBUG:             UpdateBracketTime: untemplating ExtData/PIESA/sfc/QFED/v2.4r6/Y%y4/M%m2/qfed2.emis_bc.005.%y4%m2%d2.nc4
        EXTDATA: DEBUG:      ==> Target time    : 2020-02-29 12:00:00
        EXTDATA: DEBUG:      ==> Target time    : 2020-02-29 00:00:00
        EXTDATA: DEBUG:      ===> item%frequency: Reference time: 0000-00-01 00:00:00
        EXTDATA: DEBUG:      ===> # iterations until found 12842
        EXTDATA: DEBUG:             UpdateBracketTime: Target file not found: ExtData/PIESA/sfc/QFED/v2.4r6/Y%y4/M%m2/qfed2.emis_bc.005.%y4%m2%d2.nc4
        EXTDATA: DEBUG:             ==> Propagating forwards in file from reference time
        EXTDATA: DEBUG:             ==> Reference time: 1985-01-01 00:00:00
pe=00094 FAIL at line=02456    MAPL_ExtDataGridCompMod.F90              <status=516>
pe=00094 FAIL at line=01463    MAPL_ExtDataGridCompMod.F90              <status=516>
pe=00094 FAIL at line=01846    MAPL_Generic.F90                         <needs informative message>
pe=00094 FAIL at line=01088    MAPL_CapGridComp.F90                     <status=1>
pe=00094 FAIL at line=01035    MAPL_CapGridComp.F90                     <status=1>
pe=00094 FAIL at line=00743    MAPL_CapGridComp.F90                     <status=1>
pe=00094 FAIL at line=00873    MAPL_CapGridComp.F90                     <status=1>
pe=00094 FAIL at line=00359    MAPL_Cap.F90                             <status=1>
pe=00094 FAIL at line=00214    MAPL_Cap.F90                             <status=1>
pe=00094 FAIL at line=00160    MAPL_Cap.F90                             <status=1>
pe=00094 FAIL at line=00134    MAPL_Cap.F90                             <status=1>
pe=00094 FAIL at line=00032    GEOSgcm.F90                              <status=1>
Abort(77649760) on node 94 (rank 94 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 77649760) - process 94
>> Error << /usr/local/intel/2020/compilers_and_libraries_2020.2.254/linux/mpi/intel64/bin/mpirun  -np 96 ./GEOSgcm.x --logging_config logging.yaml: status = 96; at /gpfsm/dnb02/mathomp4/SystemTests/builds/AGCM_MAPLDEV/CURRENT/GEOSgcm/install-Release/bin/esma_mpirun line 378.
GEOSgcm Run Status: -1
```
The failure seems to point to an ESMF call:
https://github.com/GEOS-ESM/MAPL/blob/becc833dab725546be6e6ae185644113b52ee0fa/base/MAPL_ExtDataGridCompMod.F90#L2456
So, uh, yeah. This might be too ExtData for me. I'll ping @bena-nasa (and assign this). The full logfile can be found at:

/gpfsm/dnb02/mathomp4/Experiments/mapldev-gcm-2020Oct08-1day-c24-LeapDayTest/3day.allow_extrap.debug.fix.out

### PR DESCRIPTION
**Pull request by mathomp4**
## Description

Fixes the issue with leap year extrapolations where the code could look for, say, 2019-02-29.

## Related Issue

Fixes #563 

## Motivation and Context

If you try and extrapolate during leap years, badness happens.

## How Has This Been Tested?

I ran GEOS, but:

1. My usual test is in Y2000, so no extrapolation is done. Even if there is extrapolation, by default it's not on (but since the run didn't crash, must not be used).
2. This does let the 2020-02-27 21z run referenced in #563 work, but...is it right?

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [X] I have tested this change with a run of GEOSgcm (if non-trivial)
- [X] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [ ] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by mathomp4** [comment]
Note that I have turned on crazy labels and have not edited the CHANGELOG as I *reaaaally* want @bena-nasa to look at this. I might have gotten things all wrong!

**Comment by tclune** [comment]
I agree.  Best if @bena-nasa reviews this one.

**Review by bena-nasa — APPROVED** [review]
Fixed the crash Matt found and passed all my standalone ExtData tests so I will approve this.

**Review by bena-nasa — APPROVED** [review]

**Comment by LiamBindle** [comment]
Hi @mathomp4, thanks for this update! We are running into this error when GCHP steps onto a leap day. This PR appears to fix it! Thanks!

**Pull request merged**
