### PR TITLE
VERIFY Statement after MPI call

### PR DESCRIPTION
**Pull request by JulesKouatchou**
## Types of change(s)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist
- [ ] Tested this change with a run of GEOSgcm
- [ ] Ran the Unit Tests (`make tests`)

## Description
- We add  a `_VERIFY(ierror)` statement (where missing) after each MPI call. 
- We start with the `base` folder and make sure that `MAPL` can still build.

It is important to note that for the `_VERIFY(ierror)` statement to work, we need to have:

```
      use MAPL_ErrorHandling
```
or
```
      use MAPL_ExceptionHandling
```
We also need to declare:
```
      integer :: rc
```

### CODE REVIEW

**Review by tclune — COMMENTED** [review]
ok - this looks good.  On to another folder.

**Comment by JulesKouatchou** [comment]
Add `_VERIFY(ierror)` statements in the `Apps` folder.

**Comment by mathomp4** [comment]
> Not sure why some of the circleci tests are failing. Will have to discuss with @mathomp4 tomorrow.

Yeah, this was due to how the CircleCI setup works and how MAPL's CircleCI config is less "automatic" than other repos. I merged in #2897 and have pressed the "Update branch" button here. I think that should make it happy.

**Comment by JulesKouatchou** [comment]
Add error checking for MPI calls in the `benchmarks` folder.

Now use:

```
    call MPI_COMM_SIZE(MPI_COMM_WORLD,comm_size,_IERROR)
```

instead of:

```
    call MPI_COMM_SIZE(MPI_COMM_WORLD,comm_size, ierror)
    _VERIFY(ierror)
```

**Comment by JulesKouatchou** [comment]
Add error checking for MPI calls in the `generic` folder.

**Comment by JulesKouatchou** [comment]
Add error checking for MPI calls in the `gridcomps` folder.

**Comment by JulesKouatchou** [comment]
Add error checking for MPI calls in the `pfio` folder.

**Comment by JulesKouatchou** [comment]
Add error checking after MPI calls in the `profiler` folder.

**Comment by JulesKouatchou** [comment]
- Add error checking after MPI calls in the `Tests` folder.
- Did not modify the `shared` folder.
- The entire code can build and there is nothing else to do.

**Comment by tclune** [comment]
Wow - I guess we'll never figure out what went wrong in the 1st attempt.

**Comment by tclune** [comment]
@JulesKouatchou  As I feared, the `_IERROR` macro does not work seamlessly with all MPI variants.   See the CI failure for GNU in `pfio/MpiMutex.F90`

**Comment by JulesKouatchou** [comment]
Remove `_IERROR` as argument but use instead `_VERIFY(ierror)` statements in the `pfio` folder.

**Comment by JulesKouatchou** [comment]
Remove `_IERROR` as argument but use instead `_VERIFY(ierror)` statements in the `profiler` folder.

**Comment by JulesKouatchou** [comment]
Remove `_IERROR` as argument but use instead `_VERIFY(ierror)` statements in the `base` folder.

**Comment by JulesKouatchou** [comment]
Remove `_IERROR` as argument but use instead `_VERIFY(ierror)` statements in the `benchmarks` folder.

**Comment by JulesKouatchou** [comment]
Remove `_IERROR `as argument but use instead `_VERIFY(ierror)` statements in the `gridcomps` folder.

**Review by tclune — APPROVED** [review]
@mathomp4 I resolved the conflict - but you might want to double check it before merging.

**Comment by mathomp4** [comment]
Well, it seems to pass all tests.

@JulesKouatchou Is this still a draft PR? If not, we can merge.

**Pull request merged**
