### PR TITLE
change some associate block to fix GNU crash

### PR DESCRIPTION
**Pull request by weiyuan-jiang**
gfortran crashes at blocks that  associate an allocated string.  Those blocks are changed to fix the crash. There are some minor cleanups in this PR too.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [ ] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [x] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Review by atrayano — CHANGES_REQUESTED** [review]
The variable 'extension' has not been initialized yet when used in the __ASSERT at line 4852

**Review by atrayano — APPROVED** [review]

**Comment by mathomp4** [comment]
Note: I'm going to tag @tclune here. I think he is more a fan of snake case (`parent_gc`) than camel case (`parentGC`). So he might be doing a bit of a posteriori work on this...

**Comment by weiyuan-jiang** [comment]
Here parentGC is just a little bit more consistent among several related subroutines.  I agree the snake style makes more sense in Fortran in general.

**Comment by tclune** [comment]
Already done, but we often have to preserve existing oddities with argument names for backwards compatibility.  Probably not even worth risking for MAPL 3 unless someone is very confident ...

**Pull request merged**
