### PR TITLE
Feature/bmauer/generalized ij search

### LINKED ISSUE #680: Bug: Floating divide by zero error when reading input volcanic emissions in GOCART/SU with UFS
A `floating divide by zero` error occurs in `MAPL_BaseMod > MAPL_GetHorzIJIndex() > cube_xy()` while reading in volcanic emissions in `GOCART2G_GridComp/SU2G_GridComp/SU2G_GridCompMod.F90` when running UFS-GOCART built in debug mode on Orion. Relevant stack trace information are provided below:

```
forrtl: error (73): floating divide by zero
Image              PC                Routine            Line        Source             
ufs_model          000000000A5E9C4B  Unknown               Unknown  Unknown
libpthread-2.17.s  00002B512D4CB5D0  Unknown               Unknown  Unknown
ufs_model          00000000021385DB  mapl_basemodmapl_        3701  MAPL_Base.F90
ufs_model          0000000002134931  mapl_basemod_mp_m        3510  MAPL_Base.F90
ufs_model          0000000001DCAA5D  su2g_gridcompmod_         868  SU2G_GridCompMod.F90
ufs_model          0000000001DBC198  su2g_gridcompmod_         719  SU2G_GridCompMod.F90
```

The MAPL library (branch: `main`, revision `bc57d97c`) was built without debug flags and with `BUILD_WITH_FLAP=NO`.

### PR DESCRIPTION
**Pull request by bena-nasa**
Fixes #680 

This is an enhancement to the IJ search algorithm needed to bin point sources to a grid. This replaces the logic of the cubed-sphere with a generic bisection search testing if the point is in a spherical polygon. This fixes an issue when using this with the NOAA UFS which maybe different unit and rotation conventions. Also eliminates the save that was used, instead goes back to the old trick of stuffing the full corners in grid as attributes. This seemed like the least intrusive way to do this.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [X] I have tested this change with a run of GEOSgcm (if non-trivial)
- [X] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [X] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Review by atrayano — CHANGES_REQUESTED** [review]
@bena, could you review line 160 of base/MAPL_SphericalGeometry.F90. The usage of parentheses does not look right. If I need to guess, most likely you meant 
in_poly=(count(signs)==0) .or. (count(signs)==4)
instead of 
in_poly=(count(signs)==0) .or. (count(signs==4))

**Comment by bena-nasa** [comment]
Fixed it

**Comment by bena-nasa** [comment]
Making this contingent for now. When I ran both algorithms simultaneously and compared the assigned indices it never complained that they did not match. But now after stripping out the old algorithm I'm finding it is non-zero diff so I'm confused. I'll do some more checking but keep the PR as DNA to save retyping later.

**Review by tclune — APPROVED** [review]

**Comment by tclune** [comment]
@atrayano - I think they all need to be positive if you traverse the polygon in a counter clockwise direction.   I oversimplified when I stated the theorem last week.

**Pull request merged**
