### PR TITLE
Feature/tclune/fortran submodules

### PR DESCRIPTION
**Pull request by tclune**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [x] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [x] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by tclune** [comment]
This pull request is mostly just to see whether gfortran can compile these changes.   I found that both NAG and Intel were a bit buggy with regard to Fortran submodules and had to compromise on style in a few places to get something that works.

But this is also an opportunity to discuss style for submodules and approaches for conversion.    What I'm currently advocating is that each module now goes into its own subdirectory with two files.  Foo.F90 holds the main module and Foo_implementation.F90 holds the submodule.

Submodules also give you a choice whether to reproduce the signature in the submodule or not.   For now, I advocate that we keep the signature in both files.   While this does result is some duplication, this is not as much of a problem as duplication is in general because the compiler must detect any divergence between the two files.   It also is a slightly easier conversion this way.  And finally, it allows emacs autocompletion to work.   (Pulling rank here.)

I don't think we should drop everything and immediately do this for every file.    Rather we should 1st target those files that tend to change the most often.  (E.g., that's why I did `./base/MAPL_Base.F90` after my warmup in `shared`.      We should then just do conversions whenever we are making a nontrivial change in whatever modules we are working on.   (But do it as a separate PR either before or after the main work.)

My guess for the next most important targets would be History and ExtData, but maybe @mathomp4 can actually derive statistics on which files are changed the most frequently?

**Comment by tclune** [comment]
OK - GFortran needed more workarounds.  The good news is that most of the workarounds actually lead to better encapsulation.

**Comment by tclune** [comment]
Here are the top 30 files in terms of number of commits in MAPL:
```  41 MAPL_Base/MAPL_Generic.F90
  33 MAPL_Base/MAPL_Cap.F90
  32 base/MAPL_Generic.F90
  31 MAPL_Base/MAPL_ExtDataGridCompMod.F90
  24 MAPL_Base/MAPL_newCFIO.F90
  23 MAPL_Base/MAPL_HistoryGridComp.F90
  22 base/MAPL_Base.F90
  18 base/MAPL_HistoryGridComp.F90
  18 MAPL_Base/MAPL_CapGridComp.F90
  17 gridcomps/Cap/MAPL_CapGridComp.F90
  17 base/MAPL_ExtDataGridCompMod.F90
  17 Tests/ExtDataDriverMod.F90
  17 MAPL_Base/MAPL_sun_uc.F90
  17 MAPL_Base/MAPL_CFIO.F90
  16 MAPL_Base/MAPL_IO.F90
  15 base/MAPL_LocStreamMod.F90
  14 pfio/MultiGroupServer.F90
  14 MAPL_Base/MAPL_Base.F90
  14 MAPL_Base/FileMetadataUtilities.F90
  13 gridcomps/History/MAPL_HistoryGridComp.F90
  13 base/ServerManager.F90
  13 base/MAPL_CapGridComp.F90
  12 pfio/AbstractServer.F90
  12 base/Regrid_Util.F90
  12 base/MAPL_CubedSphereGridFactory.F90
  11 gridcomps/Cap/MAPL_Cap.F90
  11 base/MAPL_TripolarGridFactory.F90
  11 base/MAPL_IO.F90
  11 Tests/ExtDataRoot_GridComp.F90
```

**Comment by tclune** [comment]
I should also add, in case it is not obvious, that the conversion can done incrementally for any given module.  Moving the 1st procedure takes a bit of setup, but after that, one can move one procedure at a time.

**Comment by mathomp4** [comment]
Huh. The FV3 Standalone failed. That is odd. Okay. I need to do some tests. My bet is I need to fix the CI for the updated FV3? Ugh...

**Comment by mathomp4** [comment]
Huh. No. For some reason, this update seems to trigger a crash in GEOS as a whole with both Intel and GNU!

With Intel:
```
forrtl: severe (408): fort: (33): Shape mismatch: The extent of dimension 3 of array QL is 72 and the corresponding extent of array <RHS expression> is -3689348814741910324

Image              PC                Routine            Line        Source
GEOSgcm.x          000000001008D42F  Unknown               Unknown  Unknown
GEOSgcm.x          000000000BAB1A57  fvdycorecubed_gri        3452  DynCore_GridCompMod.F90
```
With GNU:
```
Error termination. Backtrace:
At line 3452 of file /discover/swdev/mathomp4/Models/GEOSgcm-TomSubmoduleTest-GCC10/GEOSgcm/src/Components/@GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSsuperdyn_GridComp/@FVdycoreCubed_GridComp/D
ynCore_GridCompMod.F90
Fortran runtime error: Array bound mismatch for dimension 1 of array 'state' (0/24)
```
Both at the same line:
```fortran
3449   │            if( trim(names(N)).eq.'QLCN' .or. &
3450   │                trim(names(N)).eq.'QLLS' ) then
3451   │                  if( state%vars%tracer(N)%is_r4 ) then
3452   │                      QL = QL + state%vars%tracer(N)%content_r4
3453   │                  else
3454   │                      QL = QL + state%vars%tracer(N)%content
3455   │                  endif
3456   │            endif
```

**Comment by mathomp4** [comment]
As far as I can tell, the "fancy number" in the Intel traceback:

-3689348814741910324

isn't anything "important". In Binary, WA says it's:

-11001100110011001100110011001100110011001100110011001100110100

which has an interesting pattern, though it's let down at the end.

**Comment by mathomp4** [comment]
Full Intel traceback:
```
forrtl: severe (408): fort: (33): Shape mismatch: The extent of dimension 3 of array QL is 72 and the corresponding extent of array <RHS expression> is -3689348814741910324

Image              PC                Routine            Line        Source
GEOSgcm.x          000000001008D42F  Unknown               Unknown  Unknown
GEOSgcm.x          000000000BAB1A57  fvdycorecubed_gri        3452  DynCore_GridCompMod.F90
libesmf_fullylink  00002AAAC2051734  _ZN5ESMCI6FTable1     Unknown  Unknown
libesmf_fullylink  00002AAAC2054F4F  ESMCI_FTableCallE     Unknown  Unknown
libesmf_fullylink  00002AAAC24BAA75  _ZN5ESMCI2VM5ente     Unknown  Unknown
libesmf_fullylink  00002AAAC2052BCA  c_esmc_ftablecall     Unknown  Unknown
libesmf_fullylink  00002AAAC26E4AED  esmf_compmod_mp_e     Unknown  Unknown
libesmf_fullylink  00002AAAC28DFB81  esmf_gridcompmod_     Unknown  Unknown
libMAPL.base.so    00002AAABC967222  mapl_genericmod_m        1834  MAPL_Generic.F90
libesmf_fullylink  00002AAAC2051734  _ZN5ESMCI6FTable1     Unknown  Unknown
libesmf_fullylink  00002AAAC2054F4F  ESMCI_FTableCallE     Unknown  Unknown
libesmf_fullylink  00002AAAC24BAA75  _ZN5ESMCI2VM5ente     Unknown  Unknown
libesmf_fullylink  00002AAAC2052BCA  c_esmc_ftablecall     Unknown  Unknown
libesmf_fullylink  00002AAAC26E4AED  esmf_compmod_mp_e     Unknown  Unknown
libesmf_fullylink  00002AAAC28DFB81  esmf_gridcompmod_     Unknown  Unknown
GEOSgcm.x          00000000006824FE  geos_superdyngrid         719  GEOS_SuperdynGridComp.F90
libesmf_fullylink  00002AAAC2051734  _ZN5ESMCI6FTable1     Unknown  Unknown
libesmf_fullylink  00002AAAC2054F4F  ESMCI_FTableCallE     Unknown  Unknown
libesmf_fullylink  00002AAAC24BAA75  _ZN5ESMCI2VM5ente     Unknown  Unknown
libesmf_fullylink  00002AAAC2052BCA  c_esmc_ftablecall     Unknown  Unknown
libesmf_fullylink  00002AAAC26E4AED  esmf_compmod_mp_e     Unknown  Unknown
libesmf_fullylink  00002AAAC28DFB81  esmf_gridcompmod_     Unknown  Unknown
libMAPL.base.so    00002AAABC967222  mapl_genericmod_m        1834  MAPL_Generic.F90
libesmf_fullylink  00002AAAC2051734  _ZN5ESMCI6FTable1     Unknown  Unknown
libesmf_fullylink  00002AAAC2054F4F  ESMCI_FTableCallE     Unknown  Unknown
libesmf_fullylink  00002AAAC24BAA75  _ZN5ESMCI2VM5ente     Unknown  Unknown
libesmf_fullylink  00002AAAC2052BCA  c_esmc_ftablecall     Unknown  Unknown
libesmf_fullylink  00002AAAC26E4AED  esmf_compmod_mp_e     Unknown  Unknown
libesmf_fullylink  00002AAAC28DFB81  esmf_gridcompmod_     Unknown  Unknown
GEOSgcm.x          00000000005562D9  geos_agcmgridcomp        2364  GEOS_AgcmGridComp.F90
libesmf_fullylink  00002AAAC2051734  _ZN5ESMCI6FTable1     Unknown  Unknown
libesmf_fullylink  00002AAAC2054F4F  ESMCI_FTableCallE     Unknown  Unknown
libesmf_fullylink  00002AAAC24BAA75  _ZN5ESMCI2VM5ente     Unknown  Unknown
libesmf_fullylink  00002AAAC2052BCA  c_esmc_ftablecall     Unknown  Unknown
libesmf_fullylink  00002AAAC26E4AED  esmf_compmod_mp_e     Unknown  Unknown
libesmf_fullylink  00002AAAC28DFB81  esmf_gridcompmod_     Unknown  Unknown
libMAPL.base.so    00002AAABC967222  mapl_genericmod_m        1834  MAPL_Generic.F90
libesmf_fullylink  00002AAAC2051734  _ZN5ESMCI6FTable1     Unknown  Unknown
libesmf_fullylink  00002AAAC2054F4F  ESMCI_FTableCallE     Unknown  Unknown
libesmf_fullylink  00002AAAC24BAA75  _ZN5ESMCI2VM5ente     Unknown  Unknown
libesmf_fullylink  00002AAAC2052BCA  c_esmc_ftablecall     Unknown  Unknown
libesmf_fullylink  00002AAAC26E4AED  esmf_compmod_mp_e     Unknown  Unknown
libesmf_fullylink  00002AAAC28DFB81  esmf_gridcompmod_     Unknown  Unknown
GEOSgcm.x          00000000004A7015  geos_gcmgridcompm        1802  GEOS_GcmGridComp.F90
libesmf_fullylink  00002AAAC2051734  _ZN5ESMCI6FTable1     Unknown  Unknown
libesmf_fullylink  00002AAAC2054F4F  ESMCI_FTableCallE     Unknown  Unknown
libesmf_fullylink  00002AAAC24BAA75  _ZN5ESMCI2VM5ente     Unknown  Unknown
libesmf_fullylink  00002AAAC2052BCA  c_esmc_ftablecall     Unknown  Unknown
libesmf_fullylink  00002AAAC26E4AED  esmf_compmod_mp_e     Unknown  Unknown
libesmf_fullylink  00002AAAC28DFB81  esmf_gridcompmod_     Unknown  Unknown
libMAPL.base.so    00002AAABC967222  mapl_genericmod_m        1834  MAPL_Generic.F90
libesmf_fullylink  00002AAAC2051734  _ZN5ESMCI6FTable1     Unknown  Unknown
libesmf_fullylink  00002AAAC2054F4F  ESMCI_FTableCallE     Unknown  Unknown
libesmf_fullylink  00002AAAC24BAA75  _ZN5ESMCI2VM5ente     Unknown  Unknown
libesmf_fullylink  00002AAAC2052BCA  c_esmc_ftablecall     Unknown  Unknown
libesmf_fullylink  00002AAAC26E4AED  esmf_compmod_mp_e     Unknown  Unknown
libesmf_fullylink  00002AAAC28DFB81  esmf_gridcompmod_     Unknown  Unknown
libMAPL.cap.so     00002AAABB92C83D  mapl_capgridcompm        1162  MAPL_CapGridComp.F90
libMAPL.cap.so     00002AAABB92B5C8  mapl_capgridcompm        1116  MAPL_CapGridComp.F90
libMAPL.cap.so     00002AAABB922A88  mapl_capgridcompm         808  MAPL_CapGridComp.F90
libesmf_fullylink  00002AAAC2051734  _ZN5ESMCI6FTable1     Unknown  Unknown
libesmf_fullylink  00002AAAC2054F4F  ESMCI_FTableCallE     Unknown  Unknown
libesmf_fullylink  00002AAAC24BAA75  _ZN5ESMCI2VM5ente     Unknown  Unknown
libesmf_fullylink  00002AAAC2052BCA  c_esmc_ftablecall     Unknown  Unknown
libesmf_fullylink  00002AAAC26E4AED  esmf_compmod_mp_e     Unknown  Unknown
libesmf_fullylink  00002AAAC28DFB81  esmf_gridcompmod_     Unknown  Unknown
libMAPL.cap.so     00002AAABB9278EF  mapl_capgridcompm         947  MAPL_CapGridComp.F90
libMAPL.cap.so     00002AAABB8F59E3  mapl_capmod_mp_ru         247  MAPL_Cap.F90
libMAPL.cap.so     00002AAABB8F4150  mapl_capmod_mp_ru         212  MAPL_Cap.F90
libMAPL.cap.so     00002AAABB8EFEE6  mapl_capmod_mp_ru         155  MAPL_Cap.F90
libMAPL.cap.so     00002AAABB8EE4C3  Unknown               Unknown  Unknown
GEOSgcm.x          000000000046CDAA  MAIN__                     32  GEOSgcm.F90
GEOSgcm.x          0000000000469F92  Unknown               Unknown  Unknown
libc-2.22.so       00002AAAC7BCF725  __libc_start_main     Unknown  Unknown
GEOSgcm.x          0000000000469EA9  Unknown               Unknown  Unknown
```
And, of course, no file in this traceback was touched by Tom.

**Comment by tclune** [comment]
Hmm.   Looking at the code above that block, N is simply a loop variable which still does not point back to any of the layers I changed.  The extent of the loop is `size(names)` which again does not point any useful fingers, and it's hard to believe that the names array is particularly large.

Yet another worrying example of small changes in MAPL triggering seemingly unrelated problems elsewhere.       We could check to see which submodule triggers this, but it is almost certainly MAPL_Base which is both larger and more widely used than the other two.

**Comment by mathomp4** [comment]
As a test, I built a GNU version where *all* of MAPL was built as `TYPE STATIC` and it still crashes at the same place...though the error is slightly different:
```
At line 3452 of file /discover/swdev/mathomp4/Models/GEOSgcm-TomSubmoduleTest-GCC10/GEOSgcm/src/Components/@GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSsuperdyn_GridComp/@FVdycoreCubed_GridComp/D
ynCore_GridCompMod.F90
Fortran runtime error: Array bound mismatch for dimension 1 of array 'state' (0/6)
```
This compares to:
```
Fortran runtime error: Array bound mismatch for dimension 1 of array 'state' (0/24)
```
So...huh.

**Comment by tclune** [comment]
The denominator is the ubound of that array index?   I've never paid close attention to such messages beyond which line in the code to look at.

**Comment by mathomp4** [comment]
Removing the blocking label this PR now seems to work. I worked with @tclune a bit with the merge with `develop` and we did find one issue. Maybe that fixed it? @atrayano or @bena-nasa do you think `MAPL_RemapBoundsFull_3dr4` matters for FV3?

**Comment by atrayano** [comment]
@mathomp4 I cannot recall anybody using this particular overload (MAPL_RemapBoundsFull_3dr4). git blame says it is your code

**Comment by mathomp4** [comment]
> @mathomp4 I cannot recall anybody using this particular overload (MAPL_RemapBoundsFull_3dr4). git blame says it is your code

Hmm. Yeah, even if I go back in time, it's just from "initial commit" so who knows. Maybe the bug here caused memory state to go wonky? But this does seem to work now! I suppose if all agree with going into the submodule realm, we pull it in.

I did a test and both GNU Make and Ninja generators seem happy with this code as well.

**Review by mathomp4 — APPROVED** [review]
This seems to be zero-diff with both Intel and GNU on discover. Approving.

**Comment by mathomp4** [comment]
I'll let @tclune press the merge button as he did the work!

**Comment by tclune** [comment]
Despite the friendly green button, I'm not sure merge buttons release endorphins the way that green lights on test frameworks do.

**Comment by tclune** [comment]
one more thing to break PGI ...

**Pull request merged**
