### PR TITLE
Submodule files for OuterMetaComponent

### PR DESCRIPTION
**Pull request by JulesKouatchou**
## Types of change(s)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist
- [ ] Tested this change with a run of GEOSgcm
- [x] Ran the Unit Tests (`make tests`)

## Description

- Create submodules for `OuterMetaComponent.F90`.
- Include submodules in individual files in the folder `OuterMetaComponent`.
- Remove unnecessary `use` statements for submodule files.

### CODE REVIEW

**Comment by mathomp4** [comment]
So, this is fun. I think this is a race condition with Intel. I tried building this on discover, and it works there.

I got a *LOT* of:
```
write_restart.i90: warning #7925: An interface-block in a subprogram that contains an interface-body for a procedure defined by that subprogram is non-standard.   [I_RUNSETSERVICES]
```
but that will require some @tclune knowledge to explain.

But I'll think on the race...

**Comment by mathomp4** [comment]
Huh. Actually, no. If it was a race, it would be "fixed" in the serial build I do after a parallel build.

And my race suspicion goes (pretty much) away when I stare at my discover build and see that Intel is decorating the smods well, so you can't get two files of the same name:
```
$ fd finalize
generic3g/CMakeFiles/MAPL.generic3g.dir/GriddedComponentDriver/finalize.F90.o
generic3g/CMakeFiles/MAPL.generic3g.dir/GriddedComponentDriver/finalize.F90.o.provides.build
generic3g/CMakeFiles/MAPL.generic3g.dir/OuterMetaComponent/finalize.F90.o
generic3g/CMakeFiles/MAPL.generic3g.dir/OuterMetaComponent/finalize.F90.o.provides.build
generic3g/CMakeFiles/MAPL.generic3g.dir/mapl3g_griddedcomponentdriver@finalize_smod.smod.stamp
generic3g/CMakeFiles/MAPL.generic3g.dir/mapl3g_outermetacomponent@finalize_smod.smod.stamp
generic3g/finalize.i90
include/MAPL.generic3g/mapl3g_griddedcomponentdriver@finalize_smod.smod
include/MAPL.generic3g/mapl3g_outermetacomponent@finalize_smod.smod
``

Now, this does show one issue that we need to discuss with @tclune. Because both GriddedComponentDriver and OuterMetaComponent have a file called `finalize.F90`, the `-save-temps` option becomes less useful because you'll only get one `finalize.i90` out.

**Comment by mathomp4** [comment]
I just pressed "Update branch" to see if anything changes...

**Comment by mathomp4** [comment]
One more interesting thing. I just noticed that the *Ninja* build of MAPL succeeded. It's the GNU Make one that failed. Hmm.

**Comment by mathomp4** [comment]
Uggggghhhh. The Intel GNU Make MAPL build now seems to work. But the GEOSadas build fails with the finalize_smod issue! As does the MAPL-without-pFLogger-and-fArgParse.

This must be a race condition to be this random. I'll have to SSH in and see what I see...

**Comment by tclune** [comment]
> Now, this does show one issue that we need to discuss with @tclune. Because both GriddedComponentDriver and OuterMetaComponent have a file called `finalize.F90`, the `-save-temps` option becomes less useful because you'll only get one `finalize.i90` out.

Hmm.  I had hoped that the subdirectory would be included in the filename of the temp file.

**Comment by tclune** [comment]
> write_restart.i90: warning #7925: An interface-block in a subprogram that contains an interface-body for a procedure defined by that subprogram is non-standard.   [I_RUNSETSERVICES]

I think we filed a bug report on this issue a while back.   If memory serves, the workaround involved eliminating the use of pFlogger (or changing how we used it).  Was a really fun one to isolate.

**Review by tclune — DISMISSED** [review]
This looks ok - modulo the build oddities reported by @mathomp4 
Am going to mark as DRAFT until those are resolved.

**Comment by mathomp4** [comment]
Closing in favor of #2867

**Pull request closed without merging**
