### PR TITLE
Added ability to print HConfig objects.

### PR DESCRIPTION
**Pull request by tclune**
Using Fortran DTIO capability with NAG, so may fail on other compilers.

Using CI to test with gfortran and Intel.

### CODE REVIEW

**Comment by tclune** [comment]
@mathomp4  When I build with Intel on discover I do not get the problem reported by CI:
```
tclune@borgf191:/discover/swdev/tclune/GEOS-ESM/MAPL3/ifort/generic3g/tests> module list

Currently Loaded Modules:
  1) git/2.40.1     4) other/tig/2.5.4     7) other/gh          10) comp/gcc/11.2.0      13) python/GEOSpyD/Min4.11.0_py3.9_AND_Min4.8.3_py2.7
  2) cmake/3.26.3   5) ImageMagick/7.1.0   8) other/tree/2.1.0  11) comp/intel/2021.6.0
  3) other/mepo     6) git-lfs/3.2.0       9) GEOSenv           12) mpi/impi/2021.6.0
```

Any thoughts?

**Comment by mathomp4** [comment]
Graaaaah! I need to update my GEOSadas tracking branches.

**Comment by mathomp4** [comment]
GEOSadas branches updated. I've restarted the test. If it fails this time hopefully it's the usual GSI race condition.

**Comment by mathomp4** [comment]
Wooo! All pass!

**Review by bena-nasa — APPROVED** [review]

**Pull request merged**
