### PR TITLE
Add GEOSldas CI Build Tests to MAPL

### PR DESCRIPTION
**Pull request by mathomp4**
## Description

Recently, a change in MAPL caused a *build* failure in GEOSldas using GNU. This is something we'd rather not have happen. GEOSldas I think is cheap enough to build that this shouldn't hurt our account.

## Motivation and Context

We don't want to break GEOSldas at least in the *build*. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Trivial change (affects only documentation or cleanup)

## Checklist:

- [ ] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [x] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by mathomp4** [comment]
Of course, I just now realize that we can't add this until @weiyuan-jiang can figure out the GEOSldas issue with MAPL `develop`.

Still, I'll keep this PR here and when GEOSldas has a fix, I'll re-run the CI and get this merged in.

**Comment by mathomp4** [comment]
And I'll ping @gmao-rreichle so that he knows about this here.

**Comment by mathomp4** [comment]
Well, good thing is the CI build worked for Intel and failed for GNU. So that means I got the yaml right 😄

**Comment by mathomp4** [comment]
Woooo! Undrafting!

**Comment by mathomp4** [comment]
Also, that is a *lot* of reused code in that file... Time to make an issue.

**Review by tclune — APPROVED** [review]

**Pull request merged**
