### PR TITLE
Fix incorrect value for _FAILURE

### LINKED ISSUE #1734: incorrect value for `_FAILURE`
The existing logic in MAPL error handling interprets a return code of "1" as a very specific type of failure.  Then, because `_FAILURE` is defined as "1" we do not get the `<unknown error>` that is appropriate.

Probably fix is just to change the value to "-1", but another fix would be to edit the list of failures to make the first item be `<unknown error>`.

### PR DESCRIPTION
**Pull request by darianboggs**
Fixes #1734 incorrect value for _FAILURE

## Description

This PR defines the `_FAILURE` macro as -1, which is consistent with `shared/MAPL_ErrorHandling.F90`.

## Motivation and Context

Previously the `_FAILURE` macro was defined as 1 in `include/MAPL_ErrLog.h`, but in `shared/MAPL_ErrorHandling.F90` another constant has this value. This resulted in incorrect error descriptions. 

## How Has This Been Tested?

I tested the PR with a cmpscratch zero-diff test, which passed successfully.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [x] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [x] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by darianboggs** [comment]
For now, I just changed `_FAILURE` to -1. A fuller modification of the error codes in `shared/MAPL_ErrorHandling.F90` may be prudent, but that is a modification, and it would be part of a broader feature.

**Review by atrayano — APPROVED** [review]
Looks good

**Comment by darianboggs** [comment]
Return codes in *nix operating systems are nonnegative, so if `_FAILURE` is passed by the executable (with the current value of -1), it would violate the standard. If `_FAILURE` is caught by MAPL error/exception handling, which then sets the return code, the value of `_FAILURE` must only be internally consistent. On the other hand, if the codes in `shared/MAPL_ErrorHandling.F90` are changed so that `_FAILURE` can be defined as 1, the changes in the internal error codes, including the current error code = 1, may have side effects.

**Comment by tclune** [comment]
@darianboggs makes a good point about the *nix requirements on return codes.   The "larger" fix is really still a rather small fix.

**Pull request closed without merging**
