### PR TITLE
WORK IN PROGRESS: Add GCM run to MAPL CI

### PR DESCRIPTION
**Pull request by mathomp4**
## Description

This PR adds a GCM run step to the MAPL CI. 

At the moment, I'm trying this out to see how much it would cost in CircleCI credits versus our "normal" MAPL tests.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Trivial change (affects only documentation or cleanup)

## Checklist:

- [ ] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [x] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by mathomp4** [comment]
For my own accounting, our current MAPL testing uses about 1250 credits.

**Comment by mathomp4** [comment]
Okay. With the GCM runs, we get 1830 credits in 30 minutes.

Now, for fun, let's turn on an ADAS build and see what that's like...

**Comment by mathomp4** [comment]
Welp, adas on CI seems mighty broken for reasons I don't know. I mean:
```
/root/project/GEOSadas/src/Components/@GEOSana_GridComp/GEOSaana_GridComp/GSI_GridComp/prepbykx.f(36): error #5120: Unterminated character constant
         print *, 'usage: prepbykx.x {-r} infilename {-o outfilename} {-k kxlist}'
------------------^
```
I don't actually see anything wrong there. 

But I'm going to disable ADAS.

**Comment by mathomp4** [comment]
I am going to see how much more adding in FV3 would be...

**Comment by mathomp4** [comment]
So, doing FV3 and GCM uses 1900 credits in 30 minutes. Hmm.

**Comment by mathomp4** [comment]
Note. Closing this. CircleCI will soon charge for storage at *real-time*:

https://circleci.com/docs/2.0/persist-data/#how-to-calculate-an-approximation-of-your-monthly-costs

and with MAPL's speed of PR this could be...unpleasant. Indeed, I'm going to clean up GEOS now...

**Comment by tclune** [comment]
Is this maybe a "beyond column 72" issue that we see with gfortran sometimes?

**Pull request closed without merging**
