### PR TITLE
Remove tab characters from Fortran and C code

### PR DESCRIPTION
**Pull request by mathomp4**
## Description

I removed tab characters from some MAPL code. Since tab characters are not part of the Fortran Character set, this seemed like a good thing.

Plus, well, I'm on the spaces side of the tabs v. spaces debate/war. :smile:

Also, EditorConfig when *crazy* as well with whitespace.

## Motivation and Context

Spaces good, tabs bad.

## How Has This Been Tested?

I plan to test soon. I'm going to draft this until I can!

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Trivial change (affects only documentation or cleanup)

## Checklist:

- [x] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [x] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by mathomp4** [comment]
If you select "Hide whitespace" on the comparison page, this is an amusing PR. The only substantive change is the `CHANGELOG.md`. 😆

**Comment by mathomp4** [comment]
Note: I still need to test this out. My fear is that somehow I've found the magic Fortran or C code where whitespace matters...

**Comment by mathomp4** [comment]
Tested together with #1206. zero-diff with GEOS.

**Comment by mathomp4** [comment]
Still surprised no conflicts yet with this branch and updating it! Whitespace always seems to trigger git 😄

**Review by bena-nasa — APPROVED** [review]

**Pull request merged**
