### PR TITLE
Feature/wjiang/statistic_print_out_warning

### PR DESCRIPTION
**Pull request by weiyuan-jiang**
Warn and skip but not exit if the varaible cannot be shown statistics
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Trivial change (affects only documentation or cleanup)

## Checklist:

- [ ] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [ ] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by atrayano** [comment]
@weiyuan-jiang , these print statements are potentially executed on every processor, and this might clutter the output too much. How about printing on only one (it is extremely unlikely the conditions to print warning exist only on a specific processor)

**Comment by weiyuan-jiang** [comment]
Your concern is addressed @atrayano

**Comment by mathomp4** [comment]
Ooh. Nice. The push triggered a new check and CircleCI is not there anymore. I finally got it!

**Comment by mathomp4** [comment]
I have tested this PR (along with all the others in progress) at C48 and the run was zero-diff as well as all MAPL tests successful.

**Pull request merged**
