### PR TITLE
Feature/ewl/rename profiler demo exe

### PR DESCRIPTION
**Pull request by lizziel**
## Description
Change MAPL_Profiler executable name from demo.x to profiler_demo.x.

## Related Issue
See also https://github.com/Goddard-Fortran-Ecosystem/gFTL-shared/issues/22.

## Motivation and Context
This update prevents a CMake name conflict for executable demo.x if building gFTL-shared within the source same tree as MAPL, such as in GCHPctm.

## How Has This Been Tested?
This update has not been tested in the context of GEOSgcm. I am not sure how demo.x is used outside of MAPL. I am assuming it is a trivial update, and that is reflected in my checked boxes below.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Trivial change (affects only documentation or cleanup)

## Checklist:

- [ ] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [x] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by atrayano** [comment]
@lizziel , I will make the change that Tom mentioned and resubmit the PR

**Comment by atrayano** [comment]
@tclune I made the correction you have suggested

**Comment by lizziel** [comment]
@tclune and @atrayano, thanks! Apologies for ineptness at making this PR. I shouldn't do anything like this after 6 pm.

**Comment by atrayano** [comment]
Lizzie, no need to apologize. I never considered 9-5 to be the limit of making requests.

Also, the reason for my “intervention” was that we want to release v2.2 very soon (with some luck by tomorrow) and we wanted to get in your request

Atanas

**Comment by tclune** [comment]
@atrayano I think @lizziel was referring to the likelihood of making a mistake when tired.    My corollary is to never trust positive results late on a Friday.

**Comment by lizziel** [comment]
@tclune , exactly right. My intention was to commit on top of develop and then do the PR to merge into develop. Besides working late I think I also skipped lunch that day...

**Pull request merged**
