### PR TITLE
Hotfix/bmauer/fixes #1977

### LINKED ISSUE #1977: Bug in stretched grid checkpoint global attributes TARGET_LAT and TARGET_LON
GCHP stretched grid runs using MAPL 2.26.0 crash when restarting using an output checkpoint file. The problem is the global attributes for `TARGET_LAT` and `TARGET_LON`. For example, I am running a simulation with the following settings in GCHP.rc:

```
GCHP.STRETCH_FACTOR: 4.0
GCHP.TARGET_LON: -64.0
GCHP.TARGET_LAT: 32.0
```

My initial restart file contains these global attributes:

```
// global attributes:
                :STRETCH_FACTOR = 4.f ;
                :TARGET_LAT = 32.f ;
                :TARGET_LON = -64.f ;
```

My output checkpoint file used to start the next run contains these:

```
// global attributes:
                :STRETCH_FACTOR = 4.f ;
                :TARGET_LAT = 0.5585054f ;
                :TARGET_LON = -1.117011f ;
```

The restarted run crashes with this error:

```
pe=00012 FAIL at line=06123    MAPL_Generic.F90                         <Factories not equal>
pe=00012 FAIL at line=01609    MAPL_Generic.F90                         <unknown error>
pe=00012 FAIL at line=01047    MAPL_Generic.F90                         <status=-1>
pe=00012 FAIL at line=01175    Chem_GridCompMod.F90                     <status=-1>
pe=00012 FAIL at line=01807    MAPL_Generic.F90                         <status=-1>
pe=00012 FAIL at line=00167    BaseProfiler.F90                         <Timer <GCHP> does not match start timer <GCHPchem>>
pe=00012 FAIL at line=01825    MAPL_Generic.F90                         <status=1>
pe=00012 FAIL at line=00655    MAPL_CapGridComp.F90                     <status=1>
pe=00012 FAIL at line=00959    MAPL_CapGridComp.F90                     <status=1>
pe=00012 FAIL at line=00299    MAPL_Cap.F90                             <status=1>
pe=00012 FAIL at line=00258    MAPL_Cap.F90                             <status=1>
pe=00012 FAIL at line=00192    MAPL_Cap.F90                             <status=1>
pe=00012 FAIL at line=00169    MAPL_Cap.F90                             <status=1>
pe=00012 FAIL at line=00031    GCHPctm.F90                              <status=1>
```

This issue was first reported in https://github.com/geoschem/GCHP/issues/287.

### PR DESCRIPTION
**Pull request by bena-nasa**
Fixes issue #1977 

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [X] I have tested this change with a run of GEOSgcm (if non-trivial)
- [X] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [X] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by mathomp4** [comment]
@bena-nasa I assume this is sort of trivially zero-diff for GEOS (at present) because we don't really use the stretched grid yet? 

@lizziel can you try this change locally to see if it fixes the GCHP issue?

**Comment by bena-nasa** [comment]
> @bena-nasa I assume this is sort of trivially zero-diff for GEOS (at present) because we don't really use the stretched grid yet?
> 
> @lizziel can you try this change locally to see if it fixes the GCHP issue?

It should be zero diff, as yes we don't use this in GEOS normally..., even if we did, it still should be zero diff

**Comment by lizziel** [comment]
I tried this out but it is failing. It appears to be because check_and_fill_consistency is called multiple times. I printed target_lat and target_lon in the subroutine and it starts out okay:
```
 ewl: target_lat:    32.0000000
 ewl: target_lon:   -64.0000000
```
Then in the next call it's messed up and fails on the check that lat is less than 90. 
```
 ewl: target_lat:    1833.46497
 ewl: target_lon:   -3666.92993
pe=00019 FAIL at line=00649    MAPL_CubedSphereGridFactory.F90          <Latitude should be less th\
an 90.0 degrees>
pe=00019 FAIL at line=00438    MAPL_CubedSphereGridFactory.F90          <status=1>
pe=00019 FAIL at line=00310    MAPL_GridManager.F90                     <status=1>
pe=00019 FAIL at line=00242    MAPL_GridManager.F90                     <status=1>
pe=00019 FAIL at line=04366    ExtDataGridCompMod.F90                   <status=1>
```

**Comment by lizziel** [comment]
@bena-nasa, I'm going to investigate our MAPL further to figure it out what is going on.  I wonder if the MAPL code we are working with is different in ways that would impact this fix. I am printing from within `check_and_fill_consistency` right before the assert that lat and lon are within acceptable bounds. The 1833 and -3666 numbers mean somewhere it is doing a radian to degree conversion, but the values being converted are degrees when they should be radians. 

As for ExtData, we do not input files on the stretched grid other than the restart file. However, it is failing right at the beginning of ExtData so I wonder if it is creating the target grid again for the regridding? I'll see what I can find out.

**Comment by bena-nasa** [comment]
> @bena-nasa, I'm going to investigate our MAPL further to figure it out what is going on. I wonder if the MAPL code we are working with is different in ways that would impact this fix. I am printing from within `check_and_fill_consistency` right before the assert that lat and lon are within acceptable bounds. The 1833 and -3666 numbers mean somewhere it is doing a radian to degree conversion, but the values being converted are degrees when they should be radians.
> 
> As for ExtData, we do not input files on the stretched grid other than the restart file. However, it is failing right at the beginning of ExtData so I wonder if it is creating the target grid again for the regridding? I'll see what I can find out.
@lizziel 
I'll put the same sort of print in, but now if you do not ingest any data on the stretched grid into extdata why would it be going into the cubed-sphere factory at all from the code path have shown there? You clearly have input files the stretched grid, no other way it could in that code path.

**Comment by bena-nasa** [comment]
> @bena-nasa, I'm going to investigate our MAPL further to figure it out what is going on. I wonder if the MAPL code we are working with is different in ways that would impact this fix. I am printing from within `check_and_fill_consistency` right before the assert that lat and lon are within acceptable bounds. The 1833 and -3666 numbers mean somewhere it is doing a radian to degree conversion, but the values being converted are degrees when they should be radians.
> 
> As for ExtData, we do not input files on the stretched grid other than the restart file. However, it is failing right at the beginning of ExtData so I wonder if it is creating the target grid again for the regridding? I'll see what I can find out. @lizziel I'll put the same sort of print in, but now if you do not ingest any data on the stretched grid into extdata why would it be going into the cubed-sphere factory at all from the code path have shown there? You clearly have input files the stretched grid, no other way it could in that code path.

@lizziel you might have to explain to me what you are doing in GCHP. I now have my model testing frame both reading a restart that is on this stretched grid and I have extdata ingesting input that is on the same grid, I'm not seeing that warning going off about the target lon/lat being out of bounds.
However, if those are in radians the checks are bad anyway. I'll fix that and update the PR and try what I can to induce failures in my model testing framework but so far no luck.

**Comment by bena-nasa** [comment]
@lizziel well, I'm seeing oddities.
First when I write output via history on the stretched grid, for some reason the stretch factor is not being written.
Second, then when this file is ingested back in ExtData, I don't think it is being picked up as a stretched grid at all.

Not sure how to square anything of this what you are see but there are clearly still some issues I will fix.

**Comment by bena-nasa** [comment]
Arg, I see one problem, since the restarts and History/ExtData go through different code paths, I screwed up the capitalization consistency, the grid factory used by ExtData and History was assuming "stretch_factor" etc were capitalized when looking for the attributes, but the but factory wrote them as lower case, where as NCIO.F90 wrote them as upper case :(

**Comment by bena-nasa** [comment]
@lizziel 
can you re-pull and see if what I just did fixes anything? If not, we will have to talk further about hit, I just don't know how to exercise this anymore than I am how I am exercising all this or how could be any different than GCHP does within MAPL's capabilities. So far everything appears to be working now, the factory is picking up the stretched factor now in any case I can exercise.

**Comment by bena-nasa** [comment]
> I added the fix but it is still failing in the same place. To be clear, it is failing in the very first run of the stretched grid model, not the second run using the previously generated checkpoint file. I traced it to this call at the start of ExtData.
> 
> ```
>  ewl: calling initialize_from_config_with_prefix, using prefix ExtData.
>  ewl: TARGET_LAT and TARGET_LON retrieved from config as:   -3666.92993       1833.46497 
> ```
> 
> I have no idea why `initialize_from_config_with_prefix` is called several times and need to dig in further, but it does appear we initialize from a config file rather than from input file. The initialize subroutine is called in `MAPL_GridManager.F90` subroutine `make_factory_from_config` and points to the `MAPL_CubedSphereGridFactory.F90` subroutine `initialize_from_config_with_prefix`.
> 
> I can't work on this further this week but can revisit next week.

Ok, lets talk next week, clearly you are reading a file that is on the cube stretched or not into extdata, not that I see a problem with that in my testing. I will bang it harder and see if I can break this...

**Comment by mathomp4** [comment]
I'm going to block this with a label until we are sure all is okay...

**Comment by lizziel** [comment]
I'll get to this as soon as I can. We are somewhat short-staffed right now so things have piled up.

**Comment by lizziel** [comment]
I tested this with GCHP again and it works. I think I must have messed up the implementation last time when I put in the updates manually. For what it's worth, I also found an even easier fix if you want to bypass this approach of creating new variables for degrees. You can simply change Matt's fix in `NCIO.F90`:

```
 call cf%add_attribute('TARGET_LON',target_lon*MAPL_RADIANS_TO_DEGREES)
 call cf%add_attribute('TARGET_LAT',target_lat*MAPL_RADIANS_TO_DEGREES)
```

to this:

```
 call cf%add_attribute('TARGET_LON',target_lon*180.0/MAPL_PI)
 call cf%add_attribute('TARGET_LAT',target_lat*180.0/MAPL_PI)
```

It appears that the problem with Matt's fix was simply a slight change in the order of operations.

**Comment by lizziel** [comment]
Actually, I spoke too soon. My new test uses the transport tracer simulation which is much simpler than the full chemistry simulation. I did a new test with full chemistry and get the same error I got before when using Ben's code. This is because of the extra call to `initialize_from_config_with_prefix` at the start of ExtData in the full chemistry simulation. I am not seeing that extra call in the GCHP transport tracer simulation and hence was not seeing the issue. I can dig further to figure out what file is prompting this, but from the traceback it looks like it is a file that is getting vertically interpolated.

```
pe=00011 FAIL at line=00702    MAPL_CubedSphereGridFactory.F90          <Latitude should \
be less than 90.0 degrees>
pe=00011 FAIL at line=00484    MAPL_CubedSphereGridFactory.F90          <status=1>
pe=00011 FAIL at line=00310    MAPL_GridManager.F90                     <status=1>
pe=00011 FAIL at line=00242    MAPL_GridManager.F90                     <status=1>
pe=00011 FAIL at line=04366    ExtDataGridCompMod.F90                   <status=1>
pe=00011 FAIL at line=04741    ExtDataGridCompMod.F90                   <status=1>
pe=00011 FAIL at line=01021    ExtDataGridCompMod.F90                   <status=1>
pe=00011 FAIL at line=01807    MAPL_Generic.F90                         <status=1>
pe=00011 FAIL at line=00808    MAPL_CapGridComp.F90                     <status=1>
pe=00011 FAIL at line=00661    MAPL_CapGridComp.F90                     <status=1>
pe=00011 FAIL at line=00959    MAPL_CapGridComp.F90                     <status=1>
 ewl: Initialize_from_config_with_prefix: setting stretched grid lat/lon attributes in Cu\
bedSphereGridFactory object. Before:    3.40282347E+38   3.40282347E+38
 ewl: Initialize_from_config_with_prefix: setting stretched grid lat/lon attributes in Cu\
bedSphereGridFactory object. After:    1833.46497      -3666.92993
```

I also tested the fix of replacing `MAPL_RADIANS_TO_DEGREES` with `180.0/MAPL_PI` in `NCIO.F90`. That works as an alternative regardless of simulation type.

**Comment by mathomp4** [comment]
I'm going to close this PR. #2048 was the equivalent and it went into `develop just now. So now this is essentially "Merge `develop` into `main`"

**Pull request closed without merging**
