### PR TITLE
Refactors MAPL_IO to separate Binary and NetCDF subroutines.

### PR DESCRIPTION
**Pull request by Gvilla1000-nasa**
## Description

This PR separates MAPL_IO.F90 into a binary (BinIO.F90) and NetCDF (NCIO.F90) modules. A shared file containing common subroutines has been created called FileIOShared.F90.

I tried refactoring this into a new directory but the MAPL_IO modules depend on base and sun_uc and gridded factory depend on MAPL_IO so there needs to be some refactoring effort done there first before moving this outside of base. 

## Related Issue

#641
## Motivation and Context

By separating MAPL_IO into binary and NetCDF modules it allows to continue development of the NetCDF routines without needing to touch the Binary routines.

## How Has This Been Tested?

Compiled with intel/gnu in release and debug mode. MAPL by itself was also compiled with NAG.
Single day run for gnu/intel were performed

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Trivial change (affects only documentation or cleanup)

## Checklist:

- [x] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [x] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Review by tclune — DISMISSED** [review]
I'm fine with the overall approach, but am relatively unfamiliar with this layer.   I defer to @bena-nasa to spot any further gotchas.

**Comment by bena-nasa** [comment]
I'm looking at this now. Before merging we should test do additional tests for safety
1.) Make sure replay is still zero-diff as that uses the memory checkpointing
2.) Test with binary restarts. I see Matt has some MERRA2 binary restarts that can be used.

**Comment by Gvilla1000-nasa** [comment]
Let me provide some background for the change in the CMakeLists.txt. When I was splitting MAPL_IO into NCIO and BinIO, I was getting a compilation error in cub2latlon specifically with MAPL_Sort (part of MAPL.Shared) while everything else was compiling fine. In the end, that addition. wasn't strictly needed since the compilation issue was due to a missing `use MAPL_SortMod` in one of the new files I added. Thats why in the cleanup I removed that line from the CMakeLists.txt. Should I remove it again?

**Comment by Gvilla1000-nasa** [comment]
Thanks Ben for the suggestions. I ran the second test using binary restarts and it was 0diff. As discussed offline, I'm currently unable to run the 1st test due to permission issues.

**Comment by bena-nasa** [comment]
I'm seeing more things that should be in the FileIOSharedMod
Arrdescr was moved there, but NCIO.F90 still has
```
  public ArrDescrSet
  public ArrDescrInit
```
Those should probably be in shared as well.

**Review by bena-nasa — CHANGES_REQUESTED** [review]
See previous comment I made

**Comment by bena-nasa** [comment]
The replay test was zero diff

**Review by bena-nasa — APPROVED** [review]

**Review by tclune — APPROVED** [review]

**Pull request merged**
