### PR TITLE
Bypass the majority of MAPL_FlapCapOptions.F90 if not using FLAP

### PR DESCRIPTION
**Pull request by lizziel**
## Description

Nearly the entire MAPL_FlapCapOptions module in enclosed with an USE_FLAP ifdef to avoid compile errors when not using FLAP.

## Related Issue

See issue https://github.com/GEOS-ESM/MAPL/issues/451.

## Motivation and Context

When using MAPL 2.2 in GCHP, which does not use FLAP, there are compiler errors in MAPL_FlapCapOptions.F90 due to the FLAP dependency.

## How Has This Been Tested?

I am testing only in the context of building GCHP without FLAP.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [ ] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [x] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by mathomp4** [comment]
PR broke MAPL build. Removing trivial label as full model build should be required.

**Comment by lizziel** [comment]
Thanks all. I was surprised to see it broke the build, and the errors were a bunch of MPI errors seemingly unrelated to my change. Could you explain what happened?

**Comment by tclune** [comment]
I'd like to know as well.  Seems most likely that it was not your change per se but some other change that we're unaware is folded in.  (e.g., system issue)

**Comment by mathomp4** [comment]
Tested at C48 with a run that passed in a command-line option.

**Pull request merged**
