### PR TITLE
Use ESMF_Finalize in Cap

### LINKED ISSUE #817: Use ESMF_Finalize instead of MPI_Finalize
Per discussions with @rsdunlapiv and @theurich, it was determined that to use ESMF built-in profiling with GEOS, one needs to use `ESMF_Finalize` and not `MPI_Finalize` to end GEOS. This is a change in Cap.

### PR DESCRIPTION
**Pull request by mathomp4**
## Description

This PR moves to use `ESMF_Finalize` instead of `MPI_Finalize`. This comes from the want of the ESMF folks (@rsdunlapiv, @theurich) to use ESMF Profiling. Turns out, that doesn't happen if you don't have 

## Related Issue

Closes #817 

## Motivation and Context

Allows the use of the ESMF profiler.

## How Has This Been Tested?

I've tested using `ESMF_Finalize` and the model doesn't seem to crash GEOSgcm. 

That said, we should ask our friends at Harvard (@lizziel, et al) and UFS (@rmontuoro or @weiyuan-jiang as a proxy) to try this out in their codes. That is, if they call the Cap? I do not know if they do. If they don't, then this is moot for them.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [X] I have tested this change with a run of GEOSgcm (if non-trivial)
- [X] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [X] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by mathomp4** [comment]
I've added a blocking tag just until we know if this is happy with how UFS and Harvard run (@tclune might be able to tell us immediately).

**Review by atrayano — DISMISSED** [review]
Looks good!

**Comment by lizziel** [comment]
GCHP calls `cap%run` which includes the call to `mpi_finalize` so I think theanswer is yes. Will this update be be backwards compatible with ESMF 8.0?

**Review by tclune — CHANGES_REQUESTED** [review]
I thought we were going to add a run-time switch (if possible) just to be safe.   If @atrayano is correct, it might cause problems, and it would be better not to have to patch again.

**Comment by weiyuan-jiang** [comment]
I am trying to run ufs system in debugging mode. The error shifted. But I can try this branch without debugging flag first


 88: forrtl: severe (408): fort: (8): Attempt to fetch from allocatable variable DTDT_M when it is not allocated
 88:
 88: Image              PC                Routine            Line        Source
 88: ufs_model          000000000A6A6BCF  Unknown               Unknown  Unknown
 88: ufs_model          0000000002917902  fv_dynamics_mod_m         762  fv_dynamics.F90
 88: ufs_model          00000000026B8A06  atmosphere_mod_mp        1746  atmosphere.F90
 88: ufs_model          00000000025E3EEA  atmosphere_mod_mp         501  atmosphere.F90
 88: ufs_model          000000000240BD5D  atmos_model_mod_m         490  atmos_model.F90
 88: ufs_model          00000000023D5609  module_fcst_grid_         380  module_fcst_grid_comp.F90

**Comment by weiyuan-jiang** [comment]
Still print out the error message in the end

**Review by tclune — APPROVED** [review]

**Comment by mathomp4** [comment]
> GCHP calls `cap%run` which includes the call to `mpi_finalize` so I think the answer is yes. Will this update be backwards compatible with ESMF 8.0?

@lizziel That should be safe as `ESMF_Finalize()` has always been in ESMF

**Comment by mathomp4** [comment]
Well, it looks like this should be safe? @weiyuan-jiang says it ran on Orion and from what @lizziel said, I think GCHP should be safe. Shall we merge, @tclune ?

**Comment by mathomp4** [comment]
Or should I build in a run-time flag?

**Comment by lizziel** [comment]
Would it be advantageous for GCHP to use ESMF profiling as well? Do you have an example of what it looks like?

**Comment by mathomp4** [comment]
> Would it be advantageous for GCHP to use ESMF profiling as well? Do you have an example of what it looks like?

@lizziel I don't have much experience with it as, well, without this change, it doesn't work! But you can see some examples here:
https://earthsystemmodeling.org/docs/nightly/develop/ESMF_refdoc/node6.html#SECTION060130000000000000000

The text output is roughly like the new MAPL profiler output in ways. It can also output in binary so that [Cupid](https://cupid.readthedocs.io/en/latest/index.html) can show traces that look a bit like Ninja traces you can view in Chrome. I think?

**Review by atrayano — APPROVED** [review]
Looks OK

**Review by tclune — APPROVED** [review]

**Pull request merged**
