### PR TITLE
Feature/wjiang/oserver forward data

### PR DESCRIPTION
**Pull request by weiyuan-jiang**
change one-sided mpi_put to mpi_send and receive in the class MultiGroupServer.
change the cml option to --npes_backend_pernode to clarify the meaning of the option
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [x] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [x] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by weiyuan-jiang** [comment]
@mathomp4 , I have made changes here: https://github.com/GEOS-ESM/MAPL/blob/f5615cfce6a0e4e256418460f9aec5f855520fcf/pfio/LocalMemReference.F90#L365-L373 
Last time my changes satisfy the nag unit tests but they create a lot of problems for ifor and gfortran.  I believe in the future when we build GEOSgcm with Nag, the problem here will show up again.

**Comment by weiyuan-jiang** [comment]
After I merge develop into this branch, the error shows up:
@MAPL/base/MAPL_Base.F90(243): error #6618: The INTERFACE/CONTAINS stack is full. This means that modules are being 'used' in a circular way.
contains

**Comment by weiyuan-jiang** [comment]
@bena-nasa , when testing this branch, the option --npes_output_backend should be changed to --npes_backend_pernode

**Review by tclune — DISMISSED** [review]

**Comment by tclune** [comment]
I don't see it in the ticket, but at some point in the email chain there was an observation about  a circular dependency.   This took me a couple of days to track down 1-2 weeks ago and is simply because CMake needs to start again from scratch when you toggle my recent directory reorganization.   If you are not careful, you are left with a stale copy of a .mod file in one directory and then the "new" .mod gets created in the other directory.   Intel "sees" both directories and gets confused.

**Comment by mathomp4** [comment]
Pinging @tclune as I think my merge of `develop` into this nuked his approval. Oh fickle GitHub...

**Comment by weiyuan-jiang** [comment]
Do we need your approval again to merge to develop? @tclune

**Review by tclune — APPROVED** [review]

**Comment by tclune** [comment]
Apparently yes.    Did not have time to look closely, hopefully only good things have happened.

**Pull request merged**
