### PR TITLE
Mapl3/#2868 multiple coupler sources

### PR DESCRIPTION
**Pull request by tclune**
## Types of change(s)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist
- [ ] Tested this change with a run of GEOSgcm
- [x] Ran the Unit Tests (`make tests`)

## Description

Extended generic3g couplers to allow for multiple sources (dependencies)

### CODE REVIEW

**Comment by atrayano** [comment]
@tclune Are you sure you want to merge with "main"?
There are differences in 610 files...

**Comment by tclune** [comment]
> @tclune Are you sure you want to merge with "main"? There are differences in 610 files...

Ah - thanks.   Got rusty with 2 weeks off.

**Review by atrayano — DISMISSED** [review]

**Review by mathomp4 — APPROVED** [review]
Ridiculous!

**Comment by mathomp4** [comment]
The ADAS failure is the usual occasional GSI race condition. I think we are good.

**Pull request merged**
