### PR TITLE
Pull Develop into Main for MAPL 2.3 Release

### PR DESCRIPTION
**Pull request by mathomp4**
## Description

This is a pull of `develop` into `main` for a MAPL 2.3 release.

## Motivation and Context

Brings a lot of new MAPL functionality to the `main` 

## How Has This Been Tested?

Runs of GEOSgcm with both Intel and GCC have been made.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [X] I have tested this change with a run of GEOSgcm (if non-trivial)
- [X] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [X] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by mathomp4** [comment]
I'm pulling the blocker label off of this now that the logger update from #561 is in. Once the CI is done, I think we are ready!

**Review by tclune — APPROVED** [review]
Technically the date for 2.3.0 is now off a bit, but that's ok.

**Comment by mathomp4** [comment]
> Technically the date for 2.3.0 is now off a bit, but that's ok.

I could change it if you like?

**Comment by tclune** [comment]
Seems like it would be just as easy to correct on the next PR into develop.  the "Release" page will automatically have the true date.

**Pull request merged**
