### PR TITLE
set logical values through Flap without specifying true or false

### PR DESCRIPTION
**Pull request by weiyuan-jiang**
Now it can get the logical values without specifying true or false.
For example, --with_io_profiler  would give a true value. To avoid confusion, we change the command_line from --use_comm_world to --use_sub_comm and --isolate_nodes to --no_isolated_nodes .

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Trivial change (affects only documentation or cleanup)

## Checklist:

- [ ] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [x] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by weiyuan-jiang** [comment]
address issue #870

**Comment by mathomp4** [comment]
@weiyuan-jiang You tested all this, correct? 

And would we need to inform anyone about this change? (I don't know if people outside of GEOS are using these options or if they mainly exist for testing/development work)

**Review by tclune — COMMENTED** [review]
GCHP should be fine - they only use CapOptions struct which is unchanged here.

I'm more concerned about backward compatibility.  @mathomp4 do the gcm run scripts already use the options being modified?

**Comment by mathomp4** [comment]
@tclune Nope. By default the only options the GCM would use are:

* `--npes_model`
* `--nodes_output_server`
* `--logging_config`

Anything beyond that is usually "Ask @weiyuan-jiang" for me because you are often in Fancy MAPL Land™

**Comment by weiyuan-jiang** [comment]
I changed two interfaces ( --use_comm_world to --use_sub_comm,  --isolate_nodes to --no_isolated_nodes) because it does not make sense if default is true and "--use_comm_world" becomes false.  The same applies to "--no_isolated_nodes".  However, as far as I can tell, nobody is using these two parameters at this moment.  So it is probably safe

**Review by tclune — COMMENTED** [review]
My remaining concern is that it is a bit awkward to have options that have negation in their name:  `--no_isolated_nodes`.

Of course at the same time, it is highly desirable to have default values be `.false.`.

Maybe something like `--compress_nodes` would work better?

**Comment by weiyuan-jiang** [comment]
@tclune That seems better.

**Review by tclune — APPROVED** [review]

**Pull request merged**
