### PR TITLE
Fix a problem with Fortran arrays in Test_FieldArithmetic and Test_FieldBLAS

### PR DESCRIPTION
**Pull request by darianboggs**
## Description

In `Test_FieldArithmetic` and `Test_FieldBLAS`, the field values for the test fields were set incorrectly with a `=>` instead of `=` assignment for a pointer. This PR replaces the `=>` with `=`. Now tests pass. Also, comments and commented code were cleaned up
## Related Issue

Fixes Issue #2549 
## Motivation and Context

Fix failing tests
## How Has This Been Tested?

Ran MAPL tests successfully
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [ ] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [x] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by darianboggs** [comment]
I'll look at it. I'm surprised that Intel did not give an error.

**Review by tclune — DISMISSED** [review]
I'm glad these are working now.

I don't immediately see just what was different about R4 vs R8 - not that either was truly working correctly before.  But, perhaps offline, you could update me on that ultimate resolution.

**Comment by mathomp4** [comment]
@darianboggs I swear this was working once. You might need to fix a test.

**Comment by darianboggs** [comment]
Tom fixed this in `release/MAPL-v3`. I ran the MAPL tests with `release/MAPL-v3`, and they passed. I copied over the changes from `field_utils/tests` in `release/MAPL-v3` to `bugfix/wdboggs/#2549-fix_field_utils`, and the tests passed, except for a new error. Checking for differences now.

**Comment by darianboggs** [comment]
Closed by PR #2584.

**Pull request closed without merging**
