### PR TITLE
Fixes #530 NF90 string support

### LINKED ISSUE #530: Bug when handling string attributes in NetCDF-4 files under Jason
Reported by @mmanyin:

Luke Oman has found that some netCDF-4 data files  (the FEER biomass burning emissions*)
don't work with Jason  (v10.12.5),   even though they DO work with Icarus.
Apparently if there are NF90_STRING attributes in a file,  the reader aborts.
Do you know if there are any work-arounds, present or planned for GEOS?
We would rather not edit the attributes of all such files.

I'm not sure if this would help, but I ran across nf90_get_att_text  in
https://github.com/Unidata/netcdf-fortran/blob/master/fortran/netcdf_attributes.f90
However that doesn't seem to be the answer  (I tried adding it into NetCDF4_FileFormatter.F90
but the compiler balked.)
-Mike

* example file: /discover/nobackup/projects/gmao/merra2_gmi/work/ExtData/FEER/2004/FEERv1.0-G1.2_so2_20041210.nc4

(@mathomp4 cc'd)

### PR DESCRIPTION
**Pull request by mathomp4**
## Description

NetCDF still does not provide a proper interface for `NF90_String`.
As a workaround, this PR introduces a C wrapper that is then accessed
from Fortran.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [x] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [x] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by bena-nasa** [comment]
@weiyuan-jiang I tried your latest push to the branch. I was the print you added that is the attribute name you are trying to get, but this and then another silent failure of the code:
```
Conventions passed in
NetCDF error: NetCDF: Attribute not found
```

**Comment by weiyuan-jiang** [comment]
It should be working now. but still need to test...

**Comment by bena-nasa** [comment]
I pulled again and tried running. It got past the initial file open, but now threw a strange error later in the server:
```
 Reading HISTORY RC Files:
 -------------------------
   EXTDATA: EXTDATA::Initialize_: ACTIVE

   EXTDATA: *******************************************************
   EXTDATA: ** Variables to be provided by the ExtData Component **
   EXTDATA: *******************************************************
   EXTDATA: ---- 00001: VAR2D
   EXTDATA: *******************************************************

   EXTDATA: Updating L bracket for VAR2D
   EXTDATA:  ... file processed: /discover/nobackup/projects/gmao/merra2_gmi/work/ExtData/FEER/2009/FEERv1.0-G1.2_so2_20090201.nc4
   EXTDATA: Updating R bracket for VAR2D
   EXTDATA:  ... file processed: /discover/nobackup/projects/gmao/merra2_gmi/work/ExtData/FEER/2009/FEERv1.0-G1.2_so2_20090202.nc4
forrtl: severe (408): fort: (7): Attempt to use pointer I_PTR when it is not associated with a target

Image              PC                Routine            Line        Source
ExtDataDriver.x    00000000005EAE7F  Unknown               Unknown  Unknown
libMAPL.pfio.so    00002AAABE273FF2  pfio_serverthread         468  ServerThread.F90
libMAPL.pfio.so    00002AAABE2A8F49  pfio_serverthread        1098  ServerThread.F90
libMAPL.pfio.so    00002AAABE0B3CB8  pfio_messagevisit          87  MessageVisitor.F90
libMAPL.pfio.so    00002AAABE0B14BA  pfio_abstractmess         112  AbstractMessage.F90
libMAPL.pfio.so    00002AAABE12FD74  pfio_simplesocket         105  SimpleSocket.F90
libMAPL.pfio.so    00002AAABE2E01E2  pfio_clientthread         413  ClientThread.F90
libMAPL.pfio.so    00002AAABE30FAF2  pfio_clientmanage         353  ClientManager.F90
libMAPL.ExtData.s  00002AAABA51DAE6  mapl_extdatagridc        1537  ExtDataGridCompMod.F90
```
Not sure what is going on, maybe I have a mistake in my ExtDataDriver setup but I don't think so. I'll dig in to this when I get back.

**Comment by tclune** [comment]
I wonder if this is the attempt to write said string back out as metadata in the file?    I'd not properly anticipated that.

One approach might be to convert to NF90_CHAR when reading NF90_STRING.   OTOH, I suspect @weiyuan-jiang can readily construct analogous wrappers for the write phase and then pf90 is a more fully functioning companion for netcdf.

**Comment by bena-nasa** [comment]
> I wonder if this is the attempt to write said string back out as metadata in the file? I'd not properly anticipated that.
> 
> One approach might be to convert to NF90_CHAR when reading NF90_STRING. OTOH, I suspect @weiyuan-jiang can readily construct analogous wrappers for the write phase and then pf90 is a more fully functioning companion for netcdf.

@tclune @weiyuan-jiang 
This is during read it is like it got a bad address for the data pointer it is reading to...
``` 465               if (this%containing_server%Innode_Rank == innode_rank) then ! pick a rank from each node to read
 466                  ! (1) get address where data should put
 467                  offset    = this%containing_server%prefetch_offset%at(i_to_string(q%request_id))
 468                  address   = c_loc(i_ptr(offset+1))
 469                  ! (2) read data
 470                  call this%get_DataFromFile(q, address, rc=status)
 471                  _VERIFY(status)
```

**Comment by weiyuan-jiang** [comment]
I have a very simple test program for read and write. It seems fine. I will double check pfio's conversion.

program main
  use pFIO_NetCDF4_FileFormatterMod
  use pFIO_FileMetadataMod
  use pfio_NetCDF_Supplement
  use pFIO_ConstantsMod
  implicit none

  character(*), parameter :: filename= "test.nc4"

  type (NetCDF4_FileFormatter) :: formatter
  type (NetCDF4_FileFormatter) :: formatter1
  type(Filemetadata) :: cf
  ! Open file

  call formatter%open( filename, pFIO_READ)
  cf = formatter%read()
  call formatter%close()
  call formatter1%create( 'testout.nc4')
  call formatter1%write(cf)
  call formatter1%close()

end program

**Comment by weiyuan-jiang** [comment]
@bena-nasa , How does extdata send the request?

**Comment by bena-nasa** [comment]
> @bena-nasa , How does extdata send the request?

@weiyuan-jiang this ultimately happens in request_data_from_file in griddedio/GriddedIO.F90, however, something is going wrong as I put a print right before the 2D datareference (this is a 2D varible) is created which I do not see. I'll have to keep tracing this back and see what is causing it to not enter the correct branch here.

**Comment by bena-nasa** [comment]
And that is a configuration error, my setup for the tester was defining a 3D variable (should I have been 2D) so when it actually goes to read it was reading to null data reference. When I fix this it is able to ingest the file.

**Comment by weiyuan-jiang** [comment]
I suspect it goes wrong  when pFIO is preparing for serializing or deserializing of the metadata with string attribute.

**Comment by bena-nasa** [comment]
> I suspect it goes wrong when pFIO is preparing for serializing or deserializing of the metadata with string attribute.

@weiyuan-jiang  All is good as far as ingesting that file via ExtData is concerned. The error today was my setup. As far as I'm concerned the draft status can be removed from this PR.

**Review by bena-nasa — APPROVED** [review]

**Comment by tclune** [comment]
@bena-nasa Do we need a more informative error when there is a 2D vs 3D mismatch?   Or is that not even possible?

**Review by tclune — APPROVED** [review]

**Comment by bena-nasa** [comment]
> @bena-nasa Do we need a more informative error when there is a 2D vs 3D mismatch? Or is that not even possible?

@tclune Yes, possible, can be done in ExtData. Actually surprised this didn't throw an error so I need to check what is going on.

**Comment by mathomp4** [comment]
Should we have @mmanyin test this again before we merge into `develop`?

**Comment by tclune** [comment]
Ideally we wait for @mmanyin, but if he's too busy today, let's be optimistic and get this off the to-do list.

**Comment by mmanyin** [comment]
@tclune @mathomp4  Yes, this PR finally allows us to use files w/ nc4 strings. Very good!  (Thanks to @mathomp4 for explaining that it also requires ESMA_env v3.5.0 ).

**Comment by mathomp4** [comment]
As @mmanyin seems happy, I've removed the blocking label and updated the branch.

**Pull request merged**
