### PR TITLE
Bugfix/wdboggs/convert mapl resource macros

### PR DESCRIPTION
**Pull request by darianboggs**
## Description

Fix a problem with line lengths (in macros in `base/MAPL_Resource.F90`) encountered with the NVIDIA Fortran compiler.
1. Remove macros in `base/MAPL_Resources.F90`.
2. Create include files (`.h`) with macros from `base/MAPL_Resource.F90` as well new macros to allow processing information from `base/MAPL_Resource.F90` in the include files.
## Related Issue

#2325
## Motivation and Context

The NVIDIA Fortran compiler produced an error.
## How Has This Been Tested?

I ran all the tests in the `MAPL` testsuite successfully.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [ ] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [x] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by darianboggs** [comment]
I may need to minor changes based on feedback (eg filenames, file locations, efficiency.) In particular, I think that the `base/MAPL_Resource_MakeString.h` and `base/MAPL_Resource_SetValue` include files can be merged for efficiency and code quality. I still need to see if that works.

**Comment by darianboggs** [comment]
I noticed that there are no tests in the testsuite for this module. I will add them to verify the changes, and change the PR from being *draft* to normal.

**Review by tclune — DISMISSED** [review]
Looks right.   I presume there are some sanity checks somewhere that cover most of the cases?

CI tests are failing in an odd way - more of an issue for @mathomp4

**Comment by tclune** [comment]
What is the status here?   I really wanted to get this PR in so that we could report on "next" issue to PGI at 4:00 meeting this afternoon.

**Review by tclune — DISMISSED** [review]

**Comment by mathomp4** [comment]
@darianboggs I think it's close. Passes at least. However, now there seem to be quotes everywhere:
```
 'Real*4 ', 'Resource Parameter: 'NCAR_PRNDL:.500000, (default value)
```
and a slew of:
```
pe=00000 FAIL at line=08517    MAPL_Generic.F90                         <status=-858993460>
pe=00000 FAIL at line=08517    MAPL_Generic.F90                         <status=-858993460>
```

Also, this seems to be empty when it shouldn't be:
```
 'Character ', 'Resource Parameter: 'BERES_FILE_NAME:[Empty formatted value]
```

**Comment by mathomp4** [comment]
Confirmed zero-diff. There is a tweak I'd like to make to the output, but that can happen in a future PR.

Also, confirmed builds with NAG and NVIDIA can build MAPL_Resource now.

**Review by mathomp4 — APPROVED** [review]

**Review by mathomp4 — APPROVED** [review]
Reapprove after I pushed up a minor change

**Pull request merged**
