### PR TITLE
Feature/tclune/refactor generic

### PR DESCRIPTION
**Pull request by tclune**
## Motivation and Context

Refactoring MAPL_Generic - reducing code duplication.

## How Has This Been Tested?

C12 run on laptop

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [x] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [ ] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Review by atrayano — DISMISSED** [review]
Looks OK. I cannot see immediately the need for line 140 in MAPL_CapGridCompCreate, but this should not hurt

**Comment by mathomp4** [comment]
Putting a blocker label on this. A trial MOM6 run sort of went kaboom.

**Comment by mathomp4** [comment]
Huh. Even a c24 run seems to have issues. It gets to checkpointing time and:
```
 Using parallel NetCDF for file: fvcore_internal_checkpoint
 error - wrong type (other)
 error - wrong type (other)
...
forrtl: severe (190): for allocate(source=), source needs to be allocated
Image              PC                Routine            Line        Source
GEOSgcm.x          00000000032BFD12  Unknown               Unknown  Unknown
libMAPL.generic.s  00002B049C153F11  Unknown               Unknown  Unknown
libMAPL.generic.s  00002B049C15368B  Unknown               Unknown  Unknown
libMAPL.profiler.  00002B049F10FCF1  mapl_simplecolumn          54  SimpleColumn.F90
libMAPL.profiler.  00002B049F1199D3  mapl_percentageco          54  PercentageColumn.F90
libMAPL.profiler.  00002B049F112CCC  mapl_formattedtex         107  FormattedTextColumn.F90
libMAPL.profiler.  00002B049F122638  mapl_multicolumn_          96  MultiColumn.F90
libMAPL.profiler.  00002B049F122638  mapl_multicolumn_          96  MultiColumn.F90
libMAPL.profiler.  00002B049F10E6EF  mapl_profilerepor          48  ProfileReporter.F90
libMAPL.generic.s  00002B049C0CB77B  mapl_genericmodma        2276  MAPL_Generic.F90
libMAPL.generic.s  00002B049C0C5272  mapl_genericmod_m        2207  MAPL_Generic.F90
GEOSgcm.x          000000000286CEB8  fvdycorecubed_gri        7301  DynCore_GridCompMod.F90
```

**Comment by mathomp4** [comment]
I built this with Debug and the MOM6 run dies with:
```
forrtl: severe (194): Run-Time Check Failure. The variable 'mapl_genericmod_mp_addchildfromdso_$META' is being used in '/discover/swdev/mathomp4/Models/GEOSgcm-TomMAPL/GEOSgcm/src/Shared/@MA
PL/generic/MAPL_Generic.F90(4835,15)' without being defined
Image              PC                Routine            Line        Source
libMAPL.generic.s  00002B6339C00E4C  mapl_genericmod_m        4835  MAPL_Generic.F90
GEOSgcm.x          000000000F31AEB2  geos_oceangridcom         124  GEOS_OceanGridComp.F90
libesmf.so         00002B63407B335B  _ZN5ESMCI6FTable1     Unknown  Unknown
libesmf.so         00002B63407B708F  ESMCI_FTableCallE     Unknown  Unknown
libesmf.so         00002B6340D52ABA  _ZN5ESMCI3VMK5ent     Unknown  Unknown
libesmf.so         00002B6340D402B5  _ZN5ESMCI2VM5ente     Unknown  Unknown
libesmf.so         00002B63407B499A  c_esmc_ftablecall     Unknown  Unknown
libesmf.so         00002B63407B454E  _ZN5ESMCI6FTable1     Unknown  Unknown
libesmf.so         00002B63407B4285  c_esmc_setservice     Unknown  Unknown
libesmf.so         00002B63412F7335  esmf_gridcompmod_     Unknown  Unknown
libMAPL.generic.s  00002B6339BEF14F  mapl_genericmod_m        4609  MAPL_Generic.F90
libMAPL.generic.s  00002B6339BFC623  mapl_genericmod_m        4801  MAPL_Generic.F90
GEOSgcm.x          000000000E0B73C0  geos_ogcmgridcomp         235  GEOS_OgcmGridComp.F90
```

**Comment by mathomp4** [comment]
Re-blocking. Still not working with MOM6. Will update soon.

**Comment by mathomp4** [comment]
@tclune Should this be our first try at adding a `Deprecated` entry to the CHANGELOG since we now have a deprecated interface?

**Review by mathomp4 — APPROVED** [review]
Looks good. MOM6 runs just fine in both Release and Debug modes.

**Comment by tclune** [comment]
That was indeed the motivation for the other issue.

**Pull request merged**
